/* cases.js — 29 case files, zero-background format, from MODULE_D PART1 + PART2 */
const CASES = [
{id:"c01", n:1, title:"State of Madras v. Champakam Dorairajan", year:1951, arts:"Art. 15(4), 29(2)", tags:["equality"],
 bg:"Madras ran medical/engineering seats by a Communal G.O. — fixed community quotas (only 2 of 14 seats for her community, already full). Champakam Dorairajan, denied despite higher marks, said the denial was because of caste. Honest detail the Court recorded: she had not filled the form — she asked, learned refusal was certain, and sued; the State even agreed to keep one seat if she won.",
 steps:["She moved court: denial because of caste.","State defence: we follow Art. 46 (DPSP duty to weaker sections).","Court framed the clash: DPSP (Part IV) vs Fundamental Right (Part III) — which wins?"],
 held:"Fundamental Rights win — a goal cannot crush a right. The G.O. violated Art. 29(2) and was void under Art. 13. Parliament replied within months with the 1st Amendment inserting Art. 15(4) — so reservation in education exists because she won. Round 1 of the FR-vs-DPSP war.",
 analogy:"Rulebook Section A (right: no refusal by background) vs Section B (goal: help weaker students). Principal cites B; court says A wins; management rewrites the book — that rewrite is the 1st Amendment.",
 take:"FR beats DPSP (1951 position). 1st Amendment = reply. Rounds 2–4: Golaknath, Kesavananda, Minerva.",
 asked:"Which amendment followed Champakam? First, 1951 (Art. 15(4)). Also asked reversed."},
{id:"c02", n:2, title:"E.P. Royappa v. State of Tamil Nadu (decided Nov 1973, quoted 1974)", year:1974, arts:"Art. 14, 16, 311", tags:["equality","police"],
 bg:"Royappa, IAS, Chief Secretary of Tamil Nadu, was shifted to Deputy Chairman, Planning Commission, then Officer on Special Duty — same Rs 3,500 pay but side posts. He alleged bad faith, hidden punishment, breach of Arts. 14, 16 and 311.",
 steps:["He challenged the transfer as arbitrary.","Old Art. 14 test asked only: was the classification reasonable? Here there was no classification — one man simply moved.","That exposed the hole: whimsy against one person escaped the old test."],
 held:"Bhagwati J (5-judge bench): equality is living law — cannot be cribbed, cabined and confined. Equality and arbitrariness are sworn enemies: a reasonless State act violates Art. 14 by itself. (Royappa lost — same pay, no bad faith proved — but the idea won.) Two doors now: grouping test AND no-arbitrariness test.",
 analogy:"Teacher with a fair 3-absence rule vs teacher cutting one disliked student's marks with no rule. No classification to examine — yet plainly unfair. Royappa: that unfairness itself violates equality.",
 take:"No reason = no equality. Valid rule applied arbitrarily still fails Art. 14.",
 asked:"Equality is the antithesis of arbitrariness → Royappa 1974. Scenario Qs with valid law + arbitrary application."},
{id:"c03", n:3, title:"Maneka Gandhi v. Union of India", year:1978, arts:"Art. 14, 19, 21", tags:["freedom","police"],
 bg:"Old rule — A.K. Gopalan (1950): Art. 21 procedure established by law meant any legislature-made procedure sufficed; Arts. 14/19/21 were watertight compartments. A coin-toss detention law would pass. Maneka Gandhi's passport (1976) was impounded in public interest (July 1977) with no reasons and no hearing.",
 steps:["Passport issued 1976; surrender ordered 1977.","She asked for reasons; government refused (not in public interest).","No hearing, no reasons, no defence chance — she moved the Supreme Court."],
 held:"Procedure under Art. 21 must be right, just and fair — not merely existing. Arts. 14+19+21 form the Golden Triangle; a liberty law must satisfy all three. Natural justice (right to be heard) read into Art. 21. India imported due-process substance. Chain: Gopalan (narrow) → Maneka (wide) → Puttaswamy (privacy). Root of D.K. Basu arrest rules.",
 analogy:"Warden expels a student citing rulebook power. Gopalan: case closed. Maneka: was he told why? Heard? Is the rule reasonable? Any no fails — though a rule existed.",
 take:"Fair, just, reasonable — not merely existing. Golden Triangle = 14+19+21.",
 asked:"Fair-just-reasonable test → Maneka 1978. Trap: some-procedure-exists option = overruled Gopalan (period transplant)."},
{id:"c04", n:4, title:"Indra Sawhney v. Union of India (Mandal)", year:1992, arts:"Art. 16(4)", tags:["equality"],
 bg:"Mandal Commission (1979, reported 1980) recommended 27% central-job quota for OBCs. Unused a decade; V.P. Singh implemented it in Aug 1990 → nationwide protests → petitions → nine-judge bench → answer 16 Nov 1992, 6:3.",
 steps:["27% OBC quota challenged as violating Art. 16(1) equality of opportunity.","State defence: Art. 16(4) permits backward-class reservation.","Core question: is 16(4) an exception to 16(1), or part of what equality means?"],
 held:"Four holdings: (1) 16(4) is a facet of equality, NOT an exception. (2) 50% ceiling, extraordinary situations only. (3) Creamy layer excluded. (4) No promotion quota + Sept 1991 poor-only 10% memo struck (economic criterion alone invalid under 16(4) as it stood). Aftermath: 77th (1995)/16(4A) SC/ST promotion; 81st/16(4B) backlog; 85th seniority. Janhit Abhiyan (2022, 3:2): ceiling not basic structure; EWS outside it.",
 analogy:"Extra coaching for unschooled pupils is fairness, not favour — but cap half the slots, exclude well-off kids, and limit help to getting in, not moving up.",
 take:"Facet not exception. 50% + creamy layer + no promotion (later amended). Nine judges, 1992 — anchor all reservation dates here.",
 asked:"50% with automatically/never wording; creamy layer → 1992; chain Royappa 1974 → Sawhney 1992 → amendments → Janhit 2022."},
{id:"c05", n:5, title:"Kesavananda Bharati v. State of Kerala", year:1973, arts:"Art. 368, Preamble", tags:["structure"],
 bg:"1950s–60s land-reform battle: States took estates; owners cited property (then an FR); Parliament amended to bypass judgments. Shankari Prasad (1951)/Sajjan Singh (1965): yes, FRs amendable. Golaknath (1967): no — amendment is law under 13(2). Parliament hit back with the 24th Amendment (1971): amendment is NOT law under Art. 13.",
 steps:["Kesavananda, head of a Kerala mutt, challenged land acquisition.","Case ballooned into Parliament's amending power.","Thirteen judges, 68 days, 700+ pages, split 7:6."],
 held:"Middle path: Golaknath overruled — Parliament CAN amend any part including FRs — BUT cannot damage the basic structure (open list: supremacy, rule of law, separation, review, federalism, secularism, free elections, judicial independence, FR–DPSP balance). Preamble IS part of the Constitution (overrules Berubari). 24 April 1973 became the Ninth Schedule cut-off (I.R. Coelho 2007).",
 analogy:"Owner may repaint, rewindow, add floors — but not remove foundation and pillars, else it stops being that building. Parliament = owner; basic structure = foundation.",
 take:"13 judges, 7:6, 1973. Amend yes; destroy no. No exhaustive basic-features list.",
 asked:"Basic-structure doctrine → Kesavananda 1973. Chain Shankari 1951 → Sajjan 1965 → Golaknath 1967 → 24th 1971 → Kesavananda 1973."},
{id:"c06", n:6, title:"Minerva Mills v. Union of India", year:1980, arts:"Art. 31C, 368", tags:["structure"],
 bg:"Minerva Mills (Karnataka textiles) taken over under the 1974 sick-units law. Meanwhile the 42nd Amendment (1976) barred courts from questioning amendments (no limits on amending power) and widened Art. 31C so ANY DPSP law beat Arts. 14/19.",
 steps:["Owners challenged the takeover.","Challenge widened to the two 42nd-Amendment changes.","Question: can limited amending power remove its own limits?"],
 held:"Both struck down. A limited power cannot make itself unlimited; judicial review is basic structure. Widened 31C struck — shield reverted to 39(b)–(c) laws only. Balance of FRs and DPSP is itself basic structure. Update — Property Owners Association (Nov 2024, 9 judges): unamended 31C survives; 39(b) narrowed — not all private property is community resource.",
 analogy:"Committee whose rules say never abolish elections amends to say its amendments are unquestionable. Court: a limited power cannot grant itself unlimited power.",
 take:"42nd widening cut back. 31C = 39(b)+(c) only — any-DPSP option is the struck-down version. FR–DPSP balance = basic.",
 asked:"Widened 31C cut by? Minerva 1980. Trap: any-Directive-Principle immunity = false."},
{id:"c07", n:7, title:"Balaji Raghavan v. Union of India (decided Dec 1995, quoted 1996)", year:1996, arts:"Art. 18", tags:["equality"],
 bg:"Art. 18(1) bans State-conferred titles (except military/academic) — repudiation of Rai Bahadur/knighthood ranks. Question: are Bharat Ratna/Padma awards (started by Presidential notifications, Jan 1954) banned titles?",
 steps:["Petitions said National Awards are the distinction Art. 18 kills.","Court examined purpose: preventing artificial social ranks.","Distinguished recognising achievement from conferring status."],
 held:"Awards are NOT titles under 18(1) — valid — BUT must not prefix/suffix names; misuse can lose the award (Regulation 10); court urged a high-level selection committee. Separately: 18(2) citizen + foreign title = barred outright; 18(3) consent route is for non-citizen office-holders. Most notes blur these.",
 analogy:"Employee-of-the-Year plaque: fine as recognition; wrong if winner signs letters as Employee-of-the-Year Ramesh as a rank.",
 take:"Awards valid; titles banned. No prefix/suffix. Citizen needs no consent — barred outright.",
 asked:"National awards vs titles → valid, Balaji Raghavan 1996. Trap: citizen-needs-consent option."},
{id:"c08", n:8, title:"Kathi Kalu Oghad (1961) + Selvi (2010): Art. 20(3)", year:1961, arts:"Art. 20(3)", tags:["freedom","police"],
 bg:"Art. 20(3): accused shall not be compelled to be a witness against himself. IO's question: may I take fingerprints, handwriting, blood?",
 steps:["Kathi Kalu Oghad (11 judges): to be a witness = furnish TESTIMONY — convey personal knowledge by speech/document.","Merely giving comparison material is not testimony.","Selvi (2010): narco/polygraph/brain-mapping WITHOUT consent extract mind contents — barred under 20(3)+21."],
 held:"Outside 20(3): fingerprints, palm/footprints, specimen handwriting/signature, blood/hair/DNA, photos, ID parades. Inside: compelled confession/statement, forced production of knowledge-conveying documents, non-consensual mind tests. Applies only to accused persons, only against compulsion.",
 analogy:"Copying suspect: asking him to write a line for comparison = allowed (body measured); forcing yes-I-copied = barred (mind forced). Mouth protected, body not.",
 take:"Mouth, not body. Most common false statement in Part III: handwriting specimens violate 20(3) — they do not.",
 asked:"Handwriting/fingerprint options; narco-without-consent options."},
{id:"c09", n:9, title:"ADM Jabalpur v. Shivkant Shukla (Habeas Corpus)", year:1976, arts:"Art. 21, 359", tags:["freedom","structure"],
 bg:"June 1975 Emergency (internal disturbance); opponents detained under MISA; Art. 359 order suspended court access for Arts. 14/21/22. Detainees filed habeas corpus; High Courts sided with them; government appealed. AG conceded even wrongful killing would be remediless on his argument.",
 steps:["Question: during Emergency, can a detenu approach court at all?","Five judges, 4:1 for government: Art. 21 sole repository of life/liberty; access suspended = no habeas corpus whatever the facts.","Khanna J dissented alone: life/liberty pre-exist the Constitution; State needs lawful authority even in Emergency — dissent cost him the CJI-ship."],
 held:"Majority: no locus standi under Art. 21 while the order lasts. Reversed by the 44th Amendment (1978): Arts. 20/21 NEVER suspendable; internal disturbance → armed rebellion; Art. 19 auto-suspension only for war/external aggression. Puttaswamy (2017, 9 judges) expressly overruled ADM Jabalpur.",
 analogy:"Fire alarm off during a drill; management says no fire may be reported and burnt building has no remedy. Khanna: the right not to burn does not depend on the alarm. 44th wrote that into the Constitution.",
 take:"4:1, Khanna dissent, reversed by 44th, overruled 2017. Chain: ADM 1976 → 44th 1978 → overruled 2017.",
 asked:"Can Art. 21 be suspended today? No. Chronology with 44th, Maneka, Puttaswamy."},
{id:"c10", n:10, title:"K.S. Puttaswamy v. Union of India (Privacy)", year:2017, arts:"Art. 21", tags:["freedom","police"],
 bg:"Aadhaar biometrics challenged as privacy invasion. Government: no FR to privacy (citing 8-judge M.P. Sharma 1954 + 6-judge Kharak Singh 1962). Only a 9-judge bench could overrule them — so one was formed; unanimous verdict 24 Aug 2017.",
 steps:["Narrow question: is privacy an FR?","Nine judges, unanimous verdict."],
 held:"Privacy IS an FR — intrinsic to Art. 21 life/liberty and Part III generally. M.P. Sharma/Kharak Singh overruled on this point; ADM Jabalpur expressly overruled too. Not absolute — restriction needs (i) law, (ii) legitimate aim, (iii) proportionality. Policing bite: surveillance, interception, device search, biometrics, CCTV need legal basis + proportionality (backdrop to BSA 2023 electronic records).",
 analogy:"Room always in the house, now name-plated Art. 21. Door opens only with a valid key (law), for good reason, only as wide as necessary.",
 take:"9 judges, unanimous, 2017. Test: legality + aim + proportionality. Absolute-privacy option always false.",
 asked:"Privacy FR case+year → Puttaswamy 2017."},
{id:"c11", n:11, title:"D.K. Basu v. State of West Bengal (decided Dec 1996, quoted 1997)", year:1997, arts:"Art. 21, 22", tags:["freedom","police"],
 bg:"D.K. Basu (legal-aid chairman) wrote a letter to the CJI on custodial deaths/torture reports. Treated as a writ petition (epistolary jurisdiction).",
 steps:["Court took up custody safeguards.","Laid down 11 binding requirements (memo, witnesses, relative, diary, medical, magistrate copies, lawyer access, control room).","Later codified: CrPC 41B/41C/41D/50A → now BNSS (custody display duties, s.176(3) forensics for 7yr+ offences)."],
 held:"Core: name tags + register; memo attested by family/local witness + countersigned, date/time; relative informed ASAP (8–12 hrs if outside district via Legal Aid + local station); diary entry; injury memo both-signed; 48-hourly panel-doctor medicals; papers to Magistrate; lawyer access during (not throughout) interrogation; control room + notice board in 12 hrs. Operational face of Arts. 21–22, now in BNSS.",
 take:"Letter-become-petition. Memo + witness + relative + medical + magistrate = the five to memorise.",
 asked:"Arrest-guidelines case? D.K. Basu 1997. Scenario: no memo/no relative informed → violation."},
{id:"c12", n:12, title:"S.R. Bommai v. Union of India", year:1994, arts:"Art. 356", tags:["structure"],
 bg:"Art. 356 (President's Rule) used 100+ times by 1994, often politically. Bommai (Karnataka CM, 1989) was dismissed on a Governor's letter-count though he offered a floor test and even offered to advance the session. Post-Babri dismissals heard together — nine judges, judgment 11 March 1994.",
 steps:["Question 1: is a 356 proclamation justiciable or a political question?","Question 2: floor test vs Governor satisfaction?","Question 3: can courts restore a government?"],
 held:"(a) Justiciable — reviewable. (b) Floor test only; Assembly alone decides majority — letters do not. (c) Mala-fide/extraneous-material proclamations struck; dissolved Assembly/ministry can be revived. (d) Secularism is basic structure. Assembly not to be dissolved before Parliament approves. Sarkaria (1988)/Punchhi (2010) last-resort advice became enforceable; 356 use fell after 1994.",
 analogy:"Club president removed on patron's note though he demanded a vote. Bommai: count hands in the room, not letters in the office — and wrongful removal is reversible.",
 take:"9 judges, 1994. Justiciable + floor test + restoration + secularism-basic. Pre-1994 political-question option now false.",
 asked:"Governor recommends 356 sans floor test → challengeable."},
{id:"c13", n:13, title:"D.C. Wadhwa v. State of Bihar (decided Dec 1986, quoted 1987)", year:1987, arts:"Art. 123, 213", tags:["structure"],
 bg:"Ordinances (President 123 / Governor 213) are temporary: lapse 6 weeks after reassembly unless enacted. Prof. Wadhwa found Bihar (1967–81) promulgated 256 ordinances, re-promulgating identical ones for up to 14 years — dozens reissued together on some days — without legislative enactment. He challenged the practice plus 3 live ordinances.",
 steps:["Documented the re-promulgation loop.","Challenged it as bypassing the legislature."],
 held:"Systematic re-promulgation without legislative placement = fraud on the Constitution and subversion of democracy. Ordinance = emergency power, not parallel legislation (rare backlog exception only). Follow-up — Krishna Kumar Singh (2017, 7 judges): laying before the House is mandatory; re-promulgation impermissible; executive satisfaction checkable for fraud/abuse (courts won't weigh sufficiency lightly).",
 analogy:"Principal reissuing temporary notices for 14 years instead of placing them before the committee has replaced the committee with himself.",
 take:"Wadhwa 1987 + 256 ordinances/14 years. Lasts 6 weeks from reassembly — until-next-session option false.",
 asked:"Re-promulgation unconstitutional → Wadhwa 1987."},
{id:"c14", n:14, title:"Epuru Sudhakar v. Govt. of Andhra Pradesh", year:2006, arts:"Art. 72, 161", tags:["AP","police"],
 bg:"Clemency: President (72) — pardon/commute/remit incl. court-martial + death sentences. Governor (161) — State-law offences only; NO court-martial, NO death-sentence pardon. Long argued as unguided grace. An AP Governor remitted a political-killing convict's remainder on political/irrelevant grounds.",
 steps:["Order challenged as mala fide on wrong facts.","Question: can courts examine clemency at all?"],
 held:"Reviewable on limited grounds: non-application of mind; mala fide; irrelevant/extraneous considerations; suppressed/ignored material facts. Order set aside. Power is on ministerial advice, not personal discretion. Rule-of-law basis. AP case — doubly likely in APSLPRB papers.",
 analogy:"Principal waiving punishment for a friend's relative on a false report: power real, use set aside — not for lacking power but for wrong reason/wrong facts.",
 take:"72 pardons death + martial; 161 neither. Reviewable limitedly. Advice, not discretion.",
 asked:"Pardoning power justiciable? Yes, limitedly — Epuru Sudhakar 2006. Constant 72-vs-161 comparison."},
{id:"c15", n:15, title:"In re Berubari Union", year:1960, arts:"Preamble", tags:["structure"],
 bg:"Berubari (West Bengal) was to go partly to East Pakistan under the Nehru pact. Doubt: can India cede territory by ordinary law? President referred under Art. 143 (advisory). Preamble-based objection: territory of We the People cannot be ceded.",
 steps:["Court had to fix the Preamble's legal status to answer.",],
 held:"Preamble NOT part of the Constitution — interpretive key only, not power source/limit. Cession needs constitutional amendment (9th Amendment, 1960 followed). REVERSED by Kesavananda (1973): Preamble IS part, amendable short of basic-structure damage. Amended exactly once: 42nd (Socialist, Secular, Integrity). Date in Preamble = adoption 26 Nov 1949, NOT commencement 26 Jan 1950.",
 analogy:"Textbook preface: 1960 — not syllabus, only tells what the book is about. 1973 — is part of the book, editable without changing the book.",
 take:"Berubari 1960 NOT part; Kesavananda 1973 IS part + amendable. Once only.",
 asked:"Multi-statements mixing Berubari with more-than-once or commencement-date claims."},
{id:"c16", n:16, title:"Zee Telefilms v. Union of India", year:2005, arts:"Art. 12, 32, 226", tags:["equality","structure"],
 bg:"Art. 12 State test (instrumentality: funds, monopoly, functions, control). BCCI cancelled Zee's TV-rights deal; Zee filed Art. 32 writ (needs State respondent). BCCI: private society, no state funds/control — but picks national team, runs all Indian cricket.",
 steps:["Is BCCI State?","If not, any remedy?"],
 held:"BOTH halves: NOT State under Art. 12 (fails funds/control) → no Art. 32. BUT amenable to Art. 226 (public functions) since 226 runs against any person or authority. Remedy shifts SC→HC. Rule: Art. 12 governs 32; 226 needs no Art. 12. 226 wider in scope; 32 stronger guarantee (itself an FR).",
 analogy:"Private club owning the only ground: not government, yet town-dependent function reviewable under wider power.",
 take:"Not-State→no-32 + public-function→226-available. Half-remembered answers lose marks.",
 asked:"Statement pairs: BCCI not amenable to HC (false) + not State under 12 (true)."},
{id:"c17", n:17, title:"Judges Cases + NJAC (1981 · 1993 · 1998 · 2015)", year:2015, arts:"Art. 124", tags:["structure"],
 bg:"Art. 124: President appoints SC judges after CONSULTATION (CJI always consulted). Whole fight: does consultation mean ask-then-decide or obtain-agreement?",
 steps:["First (S.P. Gupta, decided 30 Dec 1981): consultation ≠ concurrence — executive primacy.","Second (1993, 9 judges): reversed — consultation = concurrence; CJI-collective primacy → collegium born.","Third (1998, Art. 143 reference): CJI + 4 senior-most (SC) / +2 (HC); unconsulted advice not binding.","99th Amendment + NJAC Act (2014): CJI + 2 senior judges + Law Minister + 2 eminent persons (PM/CJI/LoP picked), any 2 could veto. Struck down 4:1 (Oct 2015): judicial independence (basic) violated; collegium revived."],
 held:"Consultation = concurrence (1993). Collegium = CJI+4 (1998). NJAC/99th struck (2015) — Law Minister + veto = executive interference. Note: S.P. Gupta famous twice — First Judges Case AND PIL expansion.",
 analogy:"Teacher hiring v1 (management consults head, may ignore) → v2 (head+seniors decide) → v3 (mixed panel, any 2 veto) struck as management capture → back to v2.",
 take:"NJAC never operational — replaced-collegium statements false.",
 asked:"Did NJAC replace collegium? No — struck before operating."},
{id:"c18", n:18, title:"PIL birth: Hussainara, S.P. Gupta, Bandhua Mukti Morcha", year:1984, arts:"Art. 21, 32, 39A", tags:["freedom","police"],
 bg:"Strict locus standi (only injured may sue) left undertrials, bonded labourers,hazard-working children remediless — they cannot reach courts.",
 steps:["Hussainara Khatoon (Bihar, 1979) — first PIL: newspaper on undertrials jailed beyond max sentences → speedy trial + free legal aid (21 + 39A) part of fair procedure; thousands released.","S.P. Gupta (1981): any bona-fide public member may move for the disadvantaged; letter = petition (epistolary).","Bandhua Mukti Morcha (1984): Haryana quarry bonded-labour letter → Art. 32 petition; commissioners appointed; bonded labour violates 21 + 23; release + rehabilitation ordered."],
 held:"PIL ≠ private disputes in public garb (costs for publicity-interest misuse). Mechanism: DPSP (39A) becomes enforceable when read into an FR (21). Village-well analogy: sick cannot walk to office; honest neighbour may report by letter.",
 take:"1979 first PIL + speedy trial + legal aid; 1981 locus relaxed + letters; 1984 bonded labour + commissioners.",
 asked:"A-R with 39A reason + enforceable assertion: both true, R does NOT explain A — missing link Art. 21."},
{id:"c19", n:19, title:"PUDR v. Union of India (Asiad Workers, 18 Sept 1982)", year:1982, arts:"Art. 23, 24", tags:["equality","police"],
 bg:"1982 Asian Games Delhi construction: migrants via contractors at Rs 9.25/day — below minimum wage — women paid less, under-14s on site. PUDR's letter to Bhagwati J became a writ. Contractors: paid-something ≠ forced labour; at most a Minimum Wages Act issue; workers came voluntarily.",
 steps:["Art. 23 bans begar/forced labour — historically unpaid work.","Here payment existed but below statutory minimum.","Question: is economic compulsion force?"],
 held:"Yes. Force includes hunger/poverty compulsion. Below-minimum-wage work is accepted only to avoid starvation — NOT free choice. So sub-minimum wage = FORCED LABOUR = Art. 23 violation, against private contractors (horizontal, all persons). Art. 24 also breached (under-14s in construction). SI lesson: trigger is WAGES/DEBT, not chains — kiln advances + sub-minimum pay attract Art. 23 + Bonded Labour Abolition Act 1976 without proving confinement. Art. 35 → central trafficking/bonded statutes.",
 analogy:"Kidney sold for a fraction under surgery pressure: technical consent, no free choice. Same logic for wages.",
 take:"Sub-minimum wage = forced labour. 23 binds private persons, protects all persons.",
 asked:"Sub-minimum-wage statement → true."},
{id:"c20", n:20, title:"M.C. Mehta v. State of Tamil Nadu (Sivakasi, 10 Dec 1996)", year:1996, arts:"Art. 24, 21A", tags:["equality","police"],
 bg:"Sivakasi fireworks/match belt; factory fire exposed mass under-14 hazardous employment. Art. 24: no under-14 in factory/mine/hazardous work.",
 steps:["Court went beyond declaration to a scheme: employer ₹20,000/child + government ₹5,000/child into a Rehabilitation-cum-Welfare Fund; withdrawn children into education funded by it; survey + monitoring.","Reasoning tied 24 to 21A/45 (education) + 39(e)–(f) (child protection). Removing children without family support pushes them back — fund + schooling are the road home."],
 held:"Trap table: Art. 24 = under-14 in factory/mine/hazardous ONLY. 2016 Amendment Act = ALL under-14 work except family-enterprise help after school hours + entertainment; adolescents (14–18) barred from hazardous jobs (jail up to 2 yrs + Rs 50,000 fine). All-employment-below-14 statement: false under Art. 24, true under the 2016 Act — read which instrument is asked. Arts. 23–24 bind private employers.",
 analogy:"Pulling a child from a river needs towel, dry clothes, road home — not just rescue.",
 take:"Sivakasi 1996 = fund + rehab + education. Constitution vs statute ban distinction is the trap.",
 asked:"Statement pairs contrasting constitutional vs statutory bans."},
{id:"c21", n:21, title:"T.M.A. Pai Foundation v. State of Karnataka (31 Oct 2002, 11 judges)", year:2002, arts:"Art. 30, 15(5)", tags:["equality"],
 bg:"Art. 30(1): minorities (religion/language) may establish + administer educational institutions. Open: minority vs what — India or State? (Sikhs: national minority, Punjab majority.) How far does administer go — admissions/fees/staff beyond regulation?",
 steps:["Eleven-judge bench mapped both questions."],
 held:"Minority unit = STATE (linguistic reorganisation logic). Art. 30 not absolute: State may regulate for excellence/administration (teacher qualifications, standards, service conditions, anti-maladministration) but not destroy minority character. Unaided privates: autonomy in admissions/fees subject to no-profiteering/capitation ban. Link: 93rd/Art. 15(5) quota for private unaided institutions EXPRESSLY excepts Art. 30 minority institutions. Needs BOTH limbs: established AND administered.",
 analogy:"Community school for language survival: State may demand qualified teachers, safe building, honest accounts — not dictate admissions/staff till it stops being the community's school.",
 take:"11 judges, 2002. Unit = State. Regulate yes, destroy no. Both limbs needed. 15(5) excepts minorities.",
 asked:"Minority unit → State. Which institutions excepted from 15(5)? Art. 30 minorities."},
{id:"c22", n:22, title:"Sabarimala — PENDING, never settled (2018 → 2026)", year:2018, arts:"Art. 14, 15, 25, 26", tags:["equality","freedom"],
 bg:"Sabarimala (Lord Ayyappa, Kerala) custom barred women aged 10–50. Challenged under 14/15/17/25. Temple: essential practice (Art. 25) + denomination rights (Art. 26). Opponents: sex discrimination; not essential; Art. 25(2)(b) opens Hindu public institutions to all classes.",
 steps:["28 Sept 2018, 4:1: devotees NOT a separate denomination; exclusion NOT essential; women's worship + equality violated. Indu Malhotra J dissented (courts should not lightly test deep faith); Kerala Rule 3(b) struck down on paper.","Reviews (50+) → 14 Nov 2019, 3:2: reviews kept pending; larger 25-vs-26/essential-practices questions referred to NINE judges (10 Feb 2020 reference held maintainable).","Nine-judge bench notified 4 April 2026 (CJI Surya Kant), hearing from 7 April 2026 — NO final verdict yet."],
 held:"2018 exists on paper but the rulebook is under revision — quoting 2018 as final is incorrect. Correct line: 2018 (4:1) + reference pending before nine judges. Empowering provision: 25(2)(b) (Hindus incl. Sikhs/Jains/Buddhists).",
 take:"2018 4:1 + dissent; 2019 referral; 2026 nine-judge hearings live. Never mark settled.",
 asked:"Settled-law statement (false) + reference-pending statement (true). Trap: Malhotra concurred (she dissented); devotees separate denomination (majority: no)."},
{id:"c23", n:23, title:"Maratha quota — 102nd → 105th (Jaishri Patil, 5 May 2021)", year:2021, arts:"Art. 338B, 342A", tags:["equality","structure"],
 bg:"102nd (2018): NCBC constitutional status (338B) + 342A (President-notified SEBC lists; Parliament amends). Maharashtra's Maratha quota breached 50%; 5 May 2021 five-judge bench (Jaishri Patil) struck it (Marathas not shown SEBC; no extraordinary case past 50%) and, 3:2 (Rao/Gupta/Bhat vs Bhushan/Nazeer), read 342A as Centre-only SEBC identification — States lose power → State lists paralysed.",
 steps:["Maratha law → struck on 50% + identification-power reading.","States' lists frozen.","105th (19 Aug 2021): States/UTs keep own SEBC lists; Central list for Central purposes."],
 held:"102nd = 338B + 342A. 2021 = quota struck + States stripped (majority reading). 105th = States restored. General rule: two same-Article amendments years apart usually have a judgment between them.",
 analogy:"Head-office circular standardising forms read as killing branch lists; branches halt; clarification: circular was head-office-list only — branches keep theirs (= 105th).",
 take:"102nd (2018) → Maratha (2021) → 105th (2021).",
 asked:"A-R: 105th enacted BECAUSE 102nd was read as stripping States → both true, R explains A."},
{id:"c24", n:24, title:"Janhit Abhiyan v. Union of India (EWS, 7 Nov 2022, 3:2)", year:2022, arts:"Art. 15(6), 16(6)", tags:["equality"],
 bg:"103rd (2019): 15(6)+16(6), up to 10% EWS (non-SC/ST/OBC) in education/jobs. Novel: economic-criteria-only; SC/ST/OBC excluded; total past 50% (Indra Sawhney).",
 steps:["3:2 (7 Nov 2022) upheld — Maheshwari/Trivedi/Pardiwala vs Lalit/Bhat."],
 held:"Majority: economic-only affirmative action valid; excluding SC/ST/OBC avoids double benefit; 50% ceiling NOT basic structure — prudence rule for 16(4); EWS OUTSIDE it; 15(6) valid even for private unaided institutions. Dissent: excluding poor SC/ST/OBC discriminatory. Unlearn never-cross-50%: 50% governs 16(4), not EWS.",
 take:"103rd upheld 3:2. Economic-only valid. 50% ≠ basic; EWS outside.",
 asked:"A-R with automatically above-50 assertion (false) + ceiling reason (true) → A false, R true."},
{id:"c25", n:25, title:"Governor's assent saga — EVOLVING, in flux (2023 → 2025)", year:2025, arts:"Art. 200, 201", tags:["structure"],
 bg:"Art. 200 (Governor, State Bills): 4 options — assent / withhold / return (non-Money; repassed shall-not-withhold; Money Bills can't be returned) / reserve for President (then 201). Gap: NO TIME LIMIT (pocket veto). Art. 111 (President, Central Bills): 3 options. Art. 361 immunity is personal only.",
 steps:["Punjab (Nov 2023, Chandrachud): cannot sit indefinitely; as-soon-as-possible has content; withholding without return message violates Art. 200.","Tamil Nadu (8 April 2025, Pardiwala + Mahadevan): 1–3 month timelines for 200/201 + 10 Bills deemed assented on default.","Presidential Reference opinion (20 Nov 2025, unanimous, Gavai — on President's 14 questions of 13 May 2025): NO judicial timelines; NO deemed assent via Art. 142 — cannot forge signature; but prolonged unexplained inaction reviewable via limited mandamus to decide (merits untouched)."],
 held:"Position in flux — present BOTH steps, never TN-April alone as settled. Common ground: Governor cannot kill law-making by silence. Difference: timelines + deemed assent (Apr 2025) vs no timelines, no deemed assent, mandamus-to-decide only (Nov 2025). Verify pre-exam — fastest-moving item.",
 take:"200 = 4 options; 111 = 3. Deemed assent dead; mandamus-to-decide alive.",
 asked:"Chronology of three stages; at-present statements."},
{id:"c26", n:26, title:"I.R. Coelho v. State of Tamil Nadu (11 Jan 2007, 9 judges unanimous)", year:2007, arts:"Art. 31B, Ninth Schedule", tags:["structure"],
 bg:"1st Amendment (1951): Art. 31B + Ninth Schedule — listed laws immune from FR challenge. Built for land reform; swelled to 284 entries by 2007 (~218 post-1973), many unrelated — a legislative safe-deposit box that could bypass basic structure. Waman Rao (1981) background; reference from 1999.",
 steps:["Question: can any law be parked beyond review?","Nine judges, effect-based test (rights test + essence-of-right)."],
 held:"Post-24-April-1973 (Kesavananda date) Schedule entries ARE challengeable for basic-structure damage. Pre-date entries stay protected. Safe-deposit analogy: pre-date contents sealed; post-date inspectable.",
 take:"Ninth Schedule NOT absolute. Cut-off 24 April 1973. Nine judges, 2007.",
 asked:"A-R: Schedule immunity (false post-2007) + 31B text (true) → A false, R true."},
{id:"c27", n:27, title:"PESA 1996 — Scheduled Areas self-governance", year:1996, arts:"Art. 243M, Fifth Schedule", tags:["AP","police"],
 bg:"73rd (1992)/Part IX constitutionalised panchayats — but Art. 243M EXCLUDES Fifth-Schedule Scheduled Areas, Sixth-Schedule tribal areas, Nagaland/Meghalaya/Mizoram, Manipur hill council areas, Darjeeling Gorkha areas. Protective exclusion (own traditions) left NO local-government framework. 243M(4)(b) let Parliament extend Part IX with modifications → PESA (Bhuria Committee).",
 steps:["Gap → enabling clause → 1996 Act."],
 held:"Gram Sabha (ALL village voters) becomes PRIMARY authority, not the Panchayat: approves plans, identifies beneficiaries; consulted before land acquisition/rehabilitation; blocks/restores tribal land alienation; owns minor forest produce; regulates intoxicants; controls ST money-lending; manages minor water bodies; recommendation needed for minor-mineral prospecting/mining. AP Scheduled Areas: Alluri Sitharama Raju, Parvathipuram Manyam, Eluru, Palnadu, Srikakulam, Anakapalli, Kakinada. SI scenario: mineral contractor with State permit vs villagers — FIRST verify Gram Sabha resolution before treating obstruction as an offence. Five powers: land, forest produce, minerals, intoxicants, money-lending.",
 take:"Excluded by 243M → restored by PESA. Sabha over Panchayat. Operational AP law.",
 asked:"A-R: Part IX extended by separate Parliament Act BECAUSE 243M excludes → both true, R explains A."},
{id:"c28", n:28, title:"AP chain: Sri Bagh → Gentlemen's → Six-Point → 371D", year:1973, arts:"Art. 16(3), 371D, 371E", tags:["AP","equality"],
 bg:"Mergers scare smaller regions (jobs, seats, capital). Each pact reassures the weaker partner pre-merger.",
 steps:["Sri Bagh (16 Nov 1937): coastal Andhra + Rayalaseema — share capital/HC/university, Rayalaseema irrigation priority (met at Kashinathuni Nageswara Rao's Sri Bagh residence, Madras).","Gentlemen's Agreement (20 Feb 1956): Andhra State + Telangana (ex-Nizam, feared job/seat loss, Mulki protections) — employment/education/expenditure safeguards + Regional Council; CM/DyCM convention → AP formed 1 Nov 1956.","Agitations: Telangana 1969 (safeguards betrayed) + Jai Andhra 1972–73 (Mulki ruling backlash) → President's Rule Jan 1973.","Six-Point Formula (21 Sep 1973): backward-area development + local-cadre education/employment preference + Hyderabad Central University + end Mulki/Regional Committee + amendment + Tribunal.","32nd Amendment (1973): 371D (President by ORDER: local cadres/areas/recruitment + Tribunal via 1975 Presidential Order — local-candidate/zonal quotas) + 371E (Central University → Hyderabad 1974). Survived 2014 bifurcation (AP + Telangana)."],
 held:"Comparison table: 16(3) = Parliament by LAW, residence rule; 371D = President by ORDER, local cadres; 16(4) = State, backward classes. Two-schools-merging analogy: handshake (Gentlemen's) failed → constitutional writing (371D).",
 take:"1937 Sri Bagh; 1956 pre-merger Gentlemen's; 1969 + 1972–73 agitations; Sep 1973 Formula → 32nd → 371D/371E; 1975 Order operative.",
 asked:"Chronology (Gentlemen's BEFORE AP formation); Formula precedes Amendment; region-pair matching."},
{id:"c29", n:29, title:"Potti Sriramulu + two formations (1953 and 1956)", year:1956, arts:"States Reorganisation", tags:["AP"],
 bg:"Telugu Madras-Presidency districts demanded a province since Bapatla Andhra Mahasabha (May 1913, B.N. Sarma) — NOT Jogipet 1930 Hyderabad-State (Telangana) Sabha; examiners swap them. Dar (10 Dec 1948) + JVP (1 April 1949: Nehru, Patel, Pattabhi) said NO to pure-language states (Andhra allowed only if Madras-city claim dropped).",
 steps:["Sriramulu fasted 19 Oct 1952 for Andhra State, died 15 Dec 1952 (58 days) → grief/riots → Nehru announcement 19 Dec 1952 → Centre conceded."],
 held:"Andhra State 1 Oct 1953 (Andhra State Act assented 14 Sept 1953; 11 Madras districts; capital Kurnool, HC Guntur; India's FIRST linguistic State) vs Andhra Pradesh 1 Nov 1956 (SRC Fazl Ali/Panikkar/Kunzru appointed 1953 → report 1955; States Reorganisation Act + 7th Amendment; Andhra State + Telugu Hyderabad areas; capital Hyderabad; first CM Neelam Sanjiva Reddy). Trap: 1953 predates SRC report — SRC-attributes-1953 statements false.",
 take:"Fast 19 Oct 1952; death 15 Dec 1952; 1953 Kurnool from DEATH; 1956 from COMMISSION.",
 asked:"Multi-statements attributing 1953 to SRC — highest-yield AP-history trap."},
];
