/* September 30 — Test 4: Extreme General Studies Mock — 25 Questions
   SSC CGL Pattern · Very Difficult · Statement-based · Chronology · Matching
   ============================================================ */

/* EXAM INSTRUCTIONS */
"use strict";
/* Questions: 25 · Time: 30 minutes · Max Marks: 25 · Negative Marking: 0.5 */
"Use careful question selection. Statement-based questions require analysing all options. Chronology questions need exact dates. Negative marking applies. Submit after completing."

/* ============================================================
   QUESTIONS — 25 Very Difficult SSC CGL-General Studies Questions
   Pattern: Statement-based, Chronology, Matching, Assertion-Reason
   Difficulty: 70% Difficult/Tricky, 30% Moderate
   ============================================================ */

const questions = [
/* ======================================
   HISTORY - ANCIENT & MEDIEVAL (Q1-Q5)
   ====================================== */

  /* Q1: Statement-based - Easy/Moderate */
  { q: "Consider the following statements: 1. The Indus Valley Civilization had a well-planned drainage system. 2. The Great Bath was used for religious rituals. Which of the above is/are correct?", options: ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], answer: 2, explanation: "Correct: Both statements are true. The Indus Valley Civilization (Harappan) had advanced urban planning including covered drains. The Great Bath at Mohenjo-daro was indeed used for ritualistic/bathing purposes. SSC trick: Sometimes students think drainage system was Mesopotamian, but it's Indus Valley.", rule: "Indus Valley urban planning included drainage and water structures.", trapcat: "Confusing with Mesopotamian civilization", level: "L2 Application" },
  { q: "Consider the following statements: 1. Gautama Buddha belonged to the Shakya clan. 2. Buddha gave his first sermon at Sarnath. Which of the above is/are correct?", options: ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], answer: 2, explanation: "Correct: Both statements are true. Buddha was indeed a Shakya prince, and his first sermon (Dharmachakra Pravartana) was at Sarnath near Varanasi. This tests basic Buddhist history.", rule: "Buddha's clan and first sermon location.", trapcat: "Confusing with Mahavira's teachings", level: "L1 Direct" },
  { q: "Consider the following statements: 1. The Gupta period is known as the Golden Age of India. 2. Chandragupta II Vikramaditya was a famous Gupta ruler. Which of the above is/are correct?", options: ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], answer: 2, explanation: "Correct: Both statements are true. Gupta period (c. 320-550 CE) is renowned for cultural, scientific, and literary achievements - hence 'Golden Age'. Chandragupta II was indeed a prominent ruler.", rule: "Gupta period achievements in science, math, arts.", trapcat: "Calling other periods 'Golden Age'", level: "L2 Application" },
  { q: "Consider the following statements: 1. Harsha Vardhana succeeded the throne of Kannauj. 2. Harsha Vardhana sent an embassy to China. Which of the above is/are correct?", options: ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], answer: 2, explanation: "Correct: Both statements are true. Harsha (c. 606-647 CE) succeeded Kannauj and had diplomatic relations with China's Tang dynasty. This tests medieval Indian history.", rule: "Harsha Vardhana's reign and foreign relations.", trapcat: "Confusing with Pallava or Chalukya relations", level: "L3 Trap" },
  { q: "Consider the following statements: 1. The Bhakti movement originated in South India. 2. The Alvars and Nayanars were Bhakti saint-poets. Which of the above is/are correct?", options: ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], answer: 2, explanation: "Correct: Both statements are true. Bhakti movement originated in Tamil Nadu/Karnataka region (7th-8th century). Alvars (Vishnu devotees) and Nayanars (Shiva devotees) were the saint-poets who propagated Bhakti.", rule: "Bhakti movement origin and Alvars/Nayanars.", trapcat: "Confusing with Sufi movement origin", level: "L2 Application" },

/* ======================================
   HISTORY - MODERN INDIA (Q6-Q10)
   ====================================== */

  /* Q6: Chronology - Hard */
  { q: "Arrange the following events chronologically: 1. Quit India Movement 2. Champaran Satyagraha 3. Non-Cooperation Movement 4. Partition of Bengal", options: ["2, 3, 4, 1", "4, 2, 3, 1", "2, 4, 3, 1", "4, 3, 2, 1"], answer: 1, explanation: "Chronological order: Partition of Bengal (1905) → Champaran Satyagraha (1917) → Non-Cooperation Movement (1920-22) → Quit India Movement (1942). Key SSC trick: Many students reverse the order of Non-Cooperation and Quit India.", rule: "Indian National Movement chronology.", trapcat: "Reversing Non-Cooperation and Quit India chronology", level: "L3 Trap" },
  { q: "Consider the following pairs: 1. Maharana Pratap - Battle of Haldighati 2. Shivaji - Treaty of Purandar 3. Rani Lakshmibai - Siege of Jhansi Which of the above pairs are correctly matched?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three pairs are correctly matched. Maharana Pratap fought the Battle of Haldighati (1568) against Akbar. Shivaji signed the Treaty of Purandar (1665) with Mughal emperor Aurangzeb. Rani Lakshmibai died during the Siege of Jhansi (1858) in the 1857 Rebellion. This tests historical person-event pairing.", rule: "Indian freedom fighters and their associated events/ battles.", trapcat: "Incorrect pairing like Rani with Chanderi", level: "L2 Application" },
  { q: "Consider the following statements: 1. The Rowlatt Act was passed in 1919. 2. The Jallianwala Bagh massacre happened in 1919. 3. The Non-Cooperation Movement was launched in 1920. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1, 2 and 3", "1 and 3 only"], answer: 2, explanation: "All three statements are correct. The Rowlatt Act was passed in 1919, the Jallianwala Bagh massacre occurred in April 1919, and the Non-Cooperation Movement was launched in September 1920.", rule: "Rowlatt Act (1919) → Jallianwala Bagh (1919) → Non-Cooperation (1920).", trapcat: "Assuming one of three correct-sounding statements must be the 'trap'", level: "L3 Trap" },
  { q: "Consider the following statements: 1. Subhas Chandra Bose formed the Indian National Army. 2. INA's slogan was 'Delhi Chalo'. 3. INA was formed during World War II. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three statements are true. Subhas Chandra Bose indeed formed the INA (Azad Hind Fauj) with Japanese support. The slogan 'Delhi Chalo' was the INA's call. INA was formed during WWII (1942). This tests modern Indian history with freedom struggle details.", rule: "Subhas Chandra Bose and INA details.", trapcat: "Confusing INA with earlier revolutionary groups", level: "L2 Application" },

/* ======================================
   POLITY - CONSTITUTION (Q11-Q15)
   ====================================== */

  /* Q11: Assertion-Reason - Hard */
  { q: "Assertion (A): Article 32 is the soul and heart of the Constitution. Reason (R): Article 32 gives the right to move to the Supreme Court for the enforcement of Fundamental Rights.", options: ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is not the correct explanation of A", "A is true but R is false", "A is false but R is true"], answer: 0, explanation: "Correct: Both are true and R is the correct explanation. Dr. B.R. Ambedkar described Article 32 as the 'soul' of the Constitution. Article 32 gives the right to move to SC for FR enforcement, including writs like habeas corpus, mandamus, prohibition, quo warranto and certiorari. Key exam tip: In AR questions, if both statements are textbook definitions, often both are true with R explaining A.", rule: "Article 32 as soul of Constitution + FR enforcement.", trapcat: "AR question trap - R appears true but doesn't explain A", level: "L3 Trap" },
  { q: "Assertion (A): The Indian Parliament can legislate on any subject in the State List during Emergency. Reason (R): Under Article 352, the State Legislatures are automatically dissolved.", options: ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is not the correct explanation of A", "A is true but R is false", "A is false but R is true"], answer: 2, explanation: "Correct: A is true - during National Emergency (Art. 352), Parliament can legislate on State List subjects. But R is false - State Legislatures are NOT automatically dissolved during Emergency. They continue to function. This is a common misconception that SSC often tests.", rule: "Emergency provisions and State Legislative powers.", trapcat: "Emergency - false notion of State Legislature dissolution", level: "L3 Trap" },
  { q: "Assertion (A): The Rajya Sabha is called the Upper Chamber of the Indian Parliament. Reason (R): The Rajya Sabha members are elected by the State Legislative Assemblies through proportional representation.", options: ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is not the correct explanation of A", "A is true but R is false", "A is false but R is true"], answer: 0, explanation: "Correct: Both are true and R correctly explains A. Rajya Sabha is the Upper Chamber ( Lok Sabha is Lower). Members are indeed elected by MLAs via STV (Single Transferable Vote) system of PR. The 'explains' connection: being elected by state MLAs is what makes it the Upper Chamber representing states.", rule: "Rajya Sabha composition and election method.", trapcat: "AR question - R true but doesn't explain A (common trap)", level: "L2 Application" },
  { q: "Assertion (A): The President of India can promulgate Ordinances under Article 123. Reason (R): The President can promulgate Ordinances when either House of Parliament is not in session.", options: ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is not the correct explanation of A", "A is true but R is false", "A is false but R is true"], answer: 0, explanation: "Correct: Both are true and R is the correct explanation. Article 123 gives the President ordinance-making power when either Lok Sabha or Rajya Sabha is not in session. Key detail: Both Houses not in session required, or just one? Actually President can act when either House is not in session. This tests precise constitutional knowledge.", rule: "Article 123 Ordinance-making power.", trapcat: "AR - President needs both Houses not in session (common misconception)", level: "L3 Trap" },
  { q: "Assertion (A): The Indian Constitution provides for single citizenship. Reason (R): Unlike USA or Switzerland, India does not have dual citizenship at Central and State levels.", options: ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is not the correct explanation of A", "A is true but R is false", "A is false but R is true"], answer: 0, explanation: "Correct: Both are true and R is the correct explanation. Indian Constitution (Part II, Articles 5-11) provides single citizenship - being a citizen of India, not of a particular state. Unlike US (federal + state citizenship) or Switzerland (citizenship of canton + country). R explains A by contrasting with other countries.", rule: "Single citizenship vs dual citizenship countries.", trapcat: "AR - comparing with US/Switzerland", level: "L2 Application" },

/* ======================================
   POLITY - GOVERNANCE (Q16-Q20)
   ====================================== */

  /* Q16: Matching question */
  { q: "Match List I with List II and select the correct answer using the code given below the lists: List I (Body): A. NITI Aayog B. CAG C. Finance Commission D. Election Commission List II (Function): 1. Financial audit of Centre and States 2. Policy think-tank 3. Election management 4. Resource distribution between Centre and States", options: ["A-2 B-1 C-4 D-3", "A-2 B-1 C-3 D-4", "A-1 B-2 C-3 D-4", "A-2 B-3 C-1 D-4"], answer: 0, explanation: "Matching: NITI Aayog (National Institution for Transforming India) is a policy think-tank replacing Planning Commission. CAG (Comptroller and Auditor General) does financial audit. Finance Commission handles resource distribution between Centre and States. Election Commission manages elections. Code: A-2, B-1, C-4, D-3. SSC tests matching-based questions from governance structure.", rule: "Governance bodies and their functions matching.", trapcat: "Misplacing CAG with Election Commission", level: "L3 Trap" },
  { q: "Match List I with List II and select the correct code: List I (Committee/Commission): A. Sarkaria Commission B. Santhanam Committee C. Balwant Rai Mehta Committee D. Mandal Commission. List II (Related to): 1. Prevention of corruption 2. Centre-State relations 3. Backward classes reservation 4. Panchayati Raj", options: ["A-2 B-1 C-4 D-3", "A-1 B-2 C-3 D-4", "A-2 B-1 C-3 D-4", "A-4 B-1 C-2 D-3"], answer: 0, explanation: "Sarkaria Commission (1983) examined Centre-State relations. Santhanam Committee (1962-64) addressed prevention of corruption. Balwant Rai Mehta Committee (1957) recommended the three-tier Panchayati Raj system. Mandal Commission (1979) addressed backward classes reservation. Code: A-2, B-1, C-4, D-3.", rule: "Major post-independence committees/commissions and their subject areas.", trapcat: "Confusing Sarkaria (Centre-State relations) with other federalism-related bodies", level: "L3 Trap" },
  { q: "Consider the following statements: 1. The Finance Commission is constituted every five years. 2. The Finance Commission recommends the distribution of net proceeds of taxes between the Union and the States. 3. The Finance Commission determines the principles governing the grants-in-aid of the revenue of the States. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three statements are true. Finance Commission (Article 280) is constituted by the President every five years (or sooner). It recommends: (a) distribution of taxes, (b) principles of grants-in-aid. This is a staple SSC question on financial federalism.", rule: "Finance Commission duties under Article 280.", trapcat: "Confusing with Planning Commission (now replaced by NITI Aayog)", level: "L2 Application" },
  { q: "Consider the following statements: 1. The Comptroller and Auditor General of India can be removed by the President on the recommendation of the Supreme Court. 2. The salary and conditions of service of CAG shall not be varied to his disadvantage after appointment. Which of the above is/are correct?", options: ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], answer: 1, explanation: "Statement 1 is false: the CAG is removed in the SAME MANNER as a Supreme Court judge (Presidential order after a Parliamentary address with special majority, on grounds of proved misbehaviour or incapacity) — the Supreme Court does not 'recommend' the removal. Statement 2 is true: under Article 148, the CAG's salary and conditions of service cannot be varied to his disadvantage after appointment, to protect independence.", rule: "CAG removal follows the SC-judge PROCEDURE, not an SC recommendation; service conditions are separately protected.", trapcat: "CAG removal procedure — 'same manner as' vs 'on recommendation of'", level: "L3 Trap" },
  { q: "Consider the following statements: 1. The Election Commission of India is a multi-member body. 2. The Election Commission decides the election symbols allotted to political parties. 3. The Election Commission can disqualify a member elected to Parliament. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three statements are true. ECI is a multi-member body (Chief Election Commissioner + 2 Election Commissioners). ECI allots election symbols. ECI can disqualify candidates under anti-defection law and other provisions. This tests election governance knowledge.", rule: "Election Commission of India powers and composition.", trapcat: "Confusing ECI with State Election Commissions", level: "L2 Application" },

/* ======================================
   GEOGRAPHY - INDIA (Q21-Q25)
   ====================================== */

  /* Q21: Statement-based - Hard */
  { q: "Consider the following statements: 1. The Great Himalayan Range forms the northern boundary of India. 2. The Peninsular Plateau is rich in mineral resources. 3. The Indian Desert lies towards the western margins of the Aravalli hills. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three statements are true. The Himalayas form the northern boundary. The Peninsular Plateau (Deccan Plateau) is mineral-rich. The Thar Desert lies west of the Aravallis. This tests physical geography of India.", rule: "India's physical geography features.", trapcat: "Confusing Western Ghats with Himalayas", level: "L2 Application" },
  { q: "Consider the following statements: 1. The Chambal River is a tributary of the Yamuna. 2. The Godavari River is the longest peninsular river. 3. The Krishna River flows eastwards into the Bay of Bengal. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three are true. Chambal is a Yamuna tributary. Godavari (1465 km) is the longest peninsular river. Krishna flows east into Bay of Bengal. SSC often tests river systems and their directions.", rule: "Major Indian river systems and directions.", trapcat: "River direction confusion (West-flowing vs East-flowing)", level: "L2 Application" },
  { q: "Consider the following statements: 1. The Southwest Monsoon occurs from June to September. 2. The Northeast Monsoon occurs from October to December. 3. India's average annual rainfall is less than 100 cm. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 0, explanation: "Correct: Statements 1 and 2 are true, but Statement 3 is false. India's average annual rainfall is actually around 120 cm (varies regionally: Cherrapunji gets >1100 cm, Rajasthan <50 cm). Average is >100 cm. This is a common SSC trick - students memorise 'India receives monsoon rainfall' but forget the average rainfall figure.", rule: "Indian monsoon and rainfall patterns.", trapcat: "Incorrect average rainfall figure (100 cm vs actual ~120 cm)", level: "L3 Trap" },
  { q: "Consider the following statements: 1. The Andaman and Nicobar Islands are of volcanic origin. 2. The Lakshadweep Islands are coral islands. 3. The highest peak of Andaman is Saddle Peak. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 1, explanation: "Correct: Statements 2 and 3 are true. Lakshadweep is indeed coral islands. Saddle Peak (732 m) is the highest in Andaman. Statement 1 is false - Andaman-Nicobar are not volcanic origin but emerged due to tectonic uplift. This tests detailed geographical knowledge.", rule: "Indian islands - volcanic vs coral origin.", trapcat: "Andaman-Nicobar volcanic origin (common misconception)", level: "L3 Trap" },
  { q: "Consider the following statements: 1. The Western Ghats are older than the Himalayas. 2. The Western Ghats form the western boundary of the Deccan Plateau. 3. The Eastern Ghats are discontinuous and irregular. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three statements are true. Western Ghats (old fold mountains) are indeed older than Himalayas (young fold mountains). They form the western edge of Deccan Plateau. Eastern Ghats are indeed discontinuous and irregular, following the coast. This tests peninsular plateau geography.", rule: "Peninsular India's mountain ranges and their characteristics.", trapcat: "Eastern Ghats continuity misconception", level: "L2 Application" },
];

/* ============================================================
   TEST CONFIGURATION
   ============================================================ */
const testConfig = {
  testId: "sept30_test4_extreme_gs",
  date: "September 30",
  testNumber: 4,
  name: "Extreme General Studies Mock",
  subject: "General Studies",
  totalQuestions: questions.length,
  timeLimitMinutes: 30,
  maxMarks: 25,
  negativeMarking: 0.5,
  examMode: true,
  instructions: "Questions: 25 · Time: 30 minutes · Max Marks: 25 · Negative Marking: 0.5 · Difficulty: 70% Difficult/Tricky, 30% Moderate. Question types: Statement-based (Q1-Q5, Q21-Q25), Chronology (Q6), Matching (Q16), Assertion-Reason (Q11-Q12). Strategy: ROUND 1 (10 min): Read all questions, mark statement-based. ROUND 2 (12 min): Attempt chronology + matching + AR. ROUND 3 (8 min): Review difficult statement-based. Manage time strictly - 1.2 min per question average."
};

/* ============================================================
   EXPORT FOR INTEGRATION
   ============================================================ */
module.exports = { questions, testConfig };