/* takeaways.js — last-day rapid revision: takeaway + SI relevance + 3 how-asked patterns each.
   Source: MODULE_D_TAKEAWAYS_PART1/PART2 (audited). Rendered as cards in Cases tab. */
const TAKEAWAYS = [
{n:1, title:"Champakam Dorairajan (1951)", take:"FRs beat DPSP — Art 29(2) killed the Communal G.O. denying admission only on caste. Led to 1st Amendment inserting Art 15(4).",
 si:"You enforce rights on the ground; no order or goal justifies caste/religion-based denial of a right.",
 how:["Match: Champakam = Art 15(4) origin / 1st Amend 1951. WRONG: 15(4) existed before, or case created reservation directly.",
 "Multi-statement: FR prevails (T) + Art 37 DPSP unenforceable (T) + order void under Art 13 (T). Trap drops one true statement.",
 "Scenario: Brahmin girl denied seat despite higher marks. RIGHT: Art 29(2). WRONG: Art 16 or Art 46 DPSP defence (State argued it and lost)."]},
{n:2, title:"E.P. Royappa (decided Nov 1973, quoted 1974)", take:"Equality = no arbitrariness. Art 14 breaks even with no group classification if the State act has no reason. 5 judges, Bhagwati: equality and arbitrariness are sworn enemies.",
 si:"Any station order, transfer, seizure or lock-up decision without recorded reason can fail Art 14.",
 how:["Quote match: sworn enemies / cribbed, cabined and confined = Royappa. WRONG: Maneka or Sawhney.",
 "Multi-statement: Royappa LOST on facts (same Rs 3,500 pay, no bad faith proved) but idea won. Trap: he won his post back — false.",
 "Scenario: same-pay side transfer, no file reason. RIGHT: arbitrariness pleading needs no group comparison. WRONG: Art 14 needs two groups (pre-Royappa law)."]},
{n:3, title:"Maneka Gandhi (1978)", take:"Art 21 procedure must be right, just and fair — not any paper procedure. Gopalan (1950) overruled. 14+19+21 = Golden Triangle; hearing + reasons read into liberty.",
 si:"Arrest/detention/search lawful only if section + fair method — inform grounds, hear, record reasons. Root of D.K. Basu.",
 how:["Chain: Gopalan 1950 narrow / Maneka 1978 fair / Puttaswamy 2017 privacy. Trap jumbles years or says Maneka upheld Gopalan.",
 "Multi-statement: passport sans reasons/hearing (T) + fair procedure demanded (T) + 14/19/21 separate rooms (F — together). All-true is trap.",
 "Scenario: warden/officer says rule book allows, no reason needed. RIGHT: violates Maneka. WRONG: valid since procedure exists (dead Gopalan)."]},
{n:4, title:"Indra Sawhney / Mandal (1992)", take:"27% OBC quota upheld; 16(4) is emphatic restatement of 16(1), NOT exception; 50% ceiling (normal); creamy layer out; no promotion quota then; Sept 1991 poor-only memo struck. 9 judges 6:3, 16 Nov 1992. Later: 77th/81st/85th + Janhit 2022.",
 si:"Roster, reservation, creamy-layer exclusion in recruitment you face and implement without bias.",
 how:["Bench/year: 9 judges, 1992, 50% + creamy layer. WRONG: 1973/5 judges, or Mandal gave EWS (that is 103rd + 2022).",
 "Multi-statement: 16(4) is exception (F) + creamy layer excluded (T) + never cross 50% (F now — extraordinary + EWS outside). All-true is trap.",
 "Scenario: dept reserves 65% + promotion quota under unamended 16(4). RIGHT: violates Sawhney-1992 (needs 77th/extraordinary). WRONG: fully valid."]},
{n:5, title:"Kesavananda Bharati (1973)", take:"Parliament can amend any part incl. FRs but cannot destroy basic structure. Golaknath overruled. 13 judges 7:6, 24 April 1973; Preamble IS part; no closed basic-features list.",
 si:"Constitution supremacy, rule of law, judicial review protect your uniform authority — no order above basic structure stands.",
 how:["Numbers: 13 judges, 7:6, 1973, basic structure born. WRONG: 9 judges, 6:5 (Golaknath), or full final list given (deliberately open).",
 "Chain: Shankari 1951 yes / Sajjan 1965 yes / Golaknath 1967 no / 24th 1971 yes / Kesavananda middle path. Trap: Golaknath still holds.",
 "Scenario: amendment removes judicial review, says unchallengeable. RIGHT: void (basic structure). WRONG: valid, power unlimited."]},
{n:6, title:"Minerva Mills (1980)", take:"Struck 42nd clauses making amending power unlimited + shielding ANY DPSP law from 14/19. 31C back to 39(b)–(c) only. FR–DPSP balance itself is basic structure. Follow-up: Property Owners Assn (Nov 2024, 9 judges) narrowed 39(b).",
 si:"Neither rights nor goals crush each other — you balance duty (DPSP aim) with rights procedure daily.",
 how:["Match: Minerva 1980 cut 42nd; 31C = 39(b)+(c) only. WRONG: any-DPSP-law safe (dead 42nd version).",
 "Multi-statement: limited power can't unlimit itself (T) + judicial review basic (T) + FR–DPSP balance basic (T). Trap adds: all private property is 39(b) material (rejected 2024).",
 "Scenario: Art 47 health law claims 31C immunity from Art 14. RIGHT: no shield — only true 39(b)/(c). WRONG: shielded as any DPSP."]},
{n:7, title:"Balaji Raghavan (decided Dec 1995, quoted 1996)", take:"Bharat Ratna/Padma (from Jan 1954 notifications) are NOT Art 18(1) titles — valid, but no prefix/suffix; misuse can lose award (Regulation 10).",
 si:"Protocol at functions — never write Padma Shri X as rank; honour without creating class.",
 how:["Direct: awards not titles — 1996. WRONG: awards banned, or year 1992/1994.",
 "Multi-statement: 18(1) bars State titles except military/academic (T) + no prefix/suffix (T) + citizen can take foreign title with consent (F — 18(2) full bar; consent is 18(3) non-citizen office-holder).",
 "Scenario: invite prints Padma Bhushan Ramesh Kumar IPS (Retd). RIGHT: misuse (recognition ok, rank-use barred). WRONG: prefix allowed."]},
{n:8, title:"Kathi Kalu Oghad (1961) + Selvi (2010)", take:"Art 20(3) bars compelled testimony (mind), not body material. Prints, handwriting specimen, blood/DNA, photos, ID parade allowed; forced confession / mind-revealing paper barred. Selvi: forced narco/polygraph/BEAP violates 20(3)+21. 11 judges 1961; needs accused + compulsion; covers investigation stage.",
 si:"You CAN take prints/specimen/DNA; CANNOT force confession or narco without free magistrate-recorded consent + lawyer safeguards.",
 how:["Classic false: forcing specimen handwriting violates 20(3) — FALSE, allowed. Forced confession / forced narco violates.",
 "Multi-statement: to-be-witness = share personal knowledge (T) + body measurements are testimony (F) + Selvi result alone isn't confession; only later-found material via S.27 usable (T). All-true is trap.",
 "Scenario: accused refuses fingerprint vs refuses non-consensual narco. RIGHT: compel first, not second. WRONG: both barred / both compellable."]},
{n:9, title:"ADM Jabalpur (1976)", take:"Emergency majority 4:1: no habeas corpus while Art 359 shut 14/21/22; Khanna dissented — life/liberty pre-exist Constitution. Overruled by 44th Amend 1978 + Puttaswamy 2017.",
 si:"Today Arts 20 and 21 NEVER suspendable; illegal detention always challengeable even in Emergency.",
 how:["Chain: ADM 1976 4:1 Khanna dissent → 44th 1978 non-suspendable 20/21 → Puttaswamy 2017 overruled. WRONG: 2:1, or 21 still suspendable.",
 "Multi-statement: internal disturbance was ground (T then) + now armed rebellion (T) + Art 19 auto-shut under 358 unchanged (F — now war/external aggression only).",
 "Scenario: MISA-1975 detenu asks court to check legality. Then: no standing (majority). Today: maintainable — applying 1976 rule today is wrong."]},
{n:10, title:"Puttaswamy (2017)", take:"Privacy IS FR under Art 21 + Part III; M.P. Sharma 1954 (8 judges) + Kharak Singh 1962 (6 judges) overruled on this; ADM Jabalpur also overruled. Limits need legality + legitimate aim + proportionality. 9 judges unanimous, 24 Aug 2017, Aadhaar background.",
 si:"Tapping, phone/laptop search, body data, CCTV retention need law + narrow need; overreach = Art 21 violation.",
 how:["Direct: privacy FR — 2017. WRONG: 1978 (Maneka), or absolute right — not absolute.",
 "Three-test trap: legality + aim + proportionality ALL needed. Dropping proportionality or adding public sentiment = wrong.",
 "Scenario: officer opens suspect phone for quick check, no law cited. RIGHT: violates Puttaswamy. WRONG: allowed, privacy not FR (dead Sharma/Kharak)."]},
{n:11, title:"D.K. Basu (decided Dec 1996, quoted 1997)", take:"Binding arrest rules from 21+22: name tags; memo + witness sign; inform friend/relative (8–12 hrs if outside district via Legal Aid); diary entry; injury memo; 48-hr medical; papers to Magistrate; lawyer access during interrogation; control room + notice board in 12 hrs. Letter = writ (epistolary). Later into CrPC, now BNSS.",
 si:"Custody checklist — no memo + no info = violation story in exam and real liability.",
 how:["List match: memo + witness + inform relative + 48-hr medical + control room. WRONG: 24/72 hrs, or lawyer throughout every minute (meeting allowed, not throughout).",
 "Scenario: night arrest, no memo, family untold, no medical. RIGHT: DK Basu. WRONG: Maneka only or Selvi.",
 "Multi-statement: rules entered CrPC now BNSS (T) + Magistrate copies required (T) + control room in 24 hrs (F — 12 hrs). All-true is trap."]},
{n:12, title:"S.R. Bommai (1994)", take:"Art 356 reviewable; floor test in Assembly ONLY forum — Governor letters insufficient; mala fide proclamation without relevant material struck; Assembly/ministry restorable; secularism basic; don't dissolve before Parliament approval. 9 judges, 11 March 1994. Sarkaria 1988 / Punchhi 2010 background.",
 si:"Law-and-order report for 356 must cite relevant material, not politics; courts check relevance.",
 how:["Forum match: majority proved only on floor. WRONG: Governor satisfaction final, non-justiciable (pre-1994 view).",
 "Multi-statement: 356 immune as political question (F now) + court checks relevant material not correctness (T) + bad proclamation reversible (T). Trap: all false / non-reviewable.",
 "Scenario: Governor recommends 356 on defect letters, refuses floor test, dissolves pre-approval. RIGHT: violates Bommai thrice. WRONG: valid exercise."]},
{n:13, title:"D.C. Wadhwa (decided Dec 1986, quoted 1987)", take:"Re-promulgation without placing before legislature = fraud on Constitution. Ordinance (123/213) urgent-temporary: lives 6 weeks from reassembly unless passed. Bihar: 256 ordinances 1967–81, some 14 years, dozens reissued same day. Krishna Kumar Singh 2017 (7 judges): laying mandatory; satisfaction checkable for fraud/abuse.",
 si:"Temporary-power limits bind you too — emergency shortcut cannot replace legislature; same logic for temporary orders you execute.",
 how:["Number match: Wadhwa 1987 — 256 Bihar ordinances — fraud on Constitution. WRONG: valid till next session (correct: 6 weeks from reassembly).",
 "Multi-statement: placing mandatory (T) + one-session backlog reissue excusable rarely (T) + rule-by-ordinance if house inconvenient (F). All-true is trap.",
 "Scenario: same ordinance lapsed + reissued 5 times, never tabled. RIGHT: unconstitutional/subversion. WRONG: valid, each issue fresh satisfaction."]},
{n:14, title:"Epuru Sudhakar (2006, Andhra Pradesh)", take:"Pardon (72 President / 161 Governor) reviewable on limited grounds — no application of mind, mala fide, irrelevant/extraneous ground, hidden/ignored facts. 72 covers court martial + can pardon death; 161 neither (may suspend/remit/commute death in State-law setting). On ministerial advice.",
 si:"AP case — expect in State paper; remission on politics/false record can be quashed with liberty to reconsider.",
 how:["72 vs 161: 72 court-martial yes + death pardon yes; 161 both no. Trap flips or says Governor fully pardons death.",
 "Multi-statement: clemency fully beyond courts (F after 2006) + review on mala fide/irrelevant/no-mind/wrong-facts (T) + Governor acts personally (F — on Council advice).",
 "Scenario: Governor remits political-killer citing good political worker + wrong facts. RIGHT: set aside, liberty to reconsider. WRONG: immune mercy."]},
{n:15, title:"Berubari (1960)", take:"Preamble only a key in 1960, not a part; cession of Indian territory needs Art 368 amendment (9th Amend 1960 followed), not Art 3 law. Kesavananda (1973): Preamble IS part, amended once only (42nd 1976). Date 26 Nov 1949 = adoption, not commencement.",
 si:"Cession question = amendment; Preamble: 1960 No, 1973 Yes.",
 how:["Berubari cession needs only Art 3 law — WRONG. Needs 368 amendment; Art 3 is internal reorganisation.",
 "Berubari held Preamble is part — WRONG. 1960 NOT part; 1973 IS part. Examiner swaps years.",
 "Preamble amended many times / date is commencement — both WRONG. Once only (42nd); date is adoption."]},
{n:16, title:"Zee Telefilms v. BCCI (2005)", take:"BCCI NOT State under Art 12 → Art 32 fails; but public functions → Art 226 High Court writ lies. 226 wider scope (any person/authority); 32 stronger guarantee (itself a right).",
 si:"Private body doing public job (school, sports body, contractor) can still face High Court writ though Art 32 closed.",
 how:["Zee held BCCI is State — WRONG. NOT State: no govt money/control; Art 32 not maintainable.",
 "No writ against BCCI even in High Court — WRONG. 226 runs against any person/authority; selecting national team attracts 226.",
 "Art 32 wider than 226 as FR — WRONG on width. 32 stronger guarantee but narrower scope (needs State)."]},
{n:17, title:"Judges Cases + NJAC (1981/1993/1998/2015)", take:"Consultation = concurrence after 1993; collegium (CJI + 4 seniors for SC, 2 for HC) has primacy; NJAC (99th Amend 2014: CJI + 2 SC judges + Law Minister + 2 eminent, any-2 veto) struck 4:1 Oct 2015 — judicial independence is basic structure. Collegium revived.",
 si:"Did NJAC replace collegium? No — struck before working.",
 how:["First Judges (S.P. Gupta, 30 Dec 1981) held concurrence — WRONG. 1981: NOT concurrence, executive primacy; reversal 1993.",
 "Collegium = CJI + 2 seniors / NJAC had no veto — WRONG. CJI + 4 (SC); NJAC had any-2 veto.",
 "99th/NJAC survived, collegium ended — WRONG. Both struck Oct 2015 (5-judge 4:1); collegium revived."]},
{n:18, title:"Birth of PIL (1979/1981/1984)", take:"Locus relaxed for those who cannot come — letter can be writ (epistolary). Hussainara 1979 (first PIL, undertrials: speedy trial + free legal aid from 21+39A). S.P. Gupta 1981 (bona fide public member). Bandhua 1984 (bonded labour, 21+23, commissioners).",
 si:"Delay itself violates Art 21; legal aid is duty, not charity.",
 how:["Only injured can move; letter can't be petition — WRONG after PIL. S.P. Gupta allows bona fide move; letter = writ.",
 "Hussainara was about bonded labour — WRONG. Speedy trial + releases; Bandhua (1984, Haryana quarries, 21+23) is bonded labour.",
 "A: legal aid enforceable (T). R: Art 39A alone makes it so (T). R does NOT explain A — 39A Directive; enforceable only read INTO Art 21."]},
{n:19, title:"PUDR / Asiad workers (18 Sept 1982)", take:"Below-minimum wage (Rs 9.25/day) = forced labour under Art 23; hunger/poverty is force. Art 23 horizontal (private contractors), protects all persons. Under-14s on site also breached Art 24. Art 35 → central trafficking/bonded laws.",
 si:"Look for wages and debt, not chains — kiln on advance + sub-minimum pay attracts Art 23 + Bonded Labour Act 1976.",
 how:["Below-minimum only Minimum Wages Act issue, not Art 23 — WRONG. Economic compulsion = force.",
 "Art 23 only vs State / only citizens — WRONG. Horizontal + all persons.",
 "Children on site only Art 23 — WRONG. Under-14 hazardous construction also Art 24; Part III punishments only by Parliament (Art 35)."]},
{n:20, title:"M.C. Mehta / Sivakasi (10 Dec 1996)", take:"Art 24 bans only under-14 in factory/mine/hazardous. Court: Rs 20,000 employer + Rs 5,000 govt per child into rehab fund + education + survey. 2016 Act: ALL under-14 work banned (except family help after school + entertainment); adolescents 14–18 no hazardous (jail up to 2 yrs + Rs 50,000).",
 si:"Arts 23–24 bind private employers; check whether question asks Constitution (narrow) or 2016 Act (wide).",
 how:["Art 24 bans all under-14 employment — WRONG for Constitution (factory/mine/hazardous only). ALL-ban is 2016 Act.",
 "Fund = 20,000 employer + 5,000 govt — RIGHT. Swapped figures wrong.",
 "Pulling child out suffices — WRONG. Linked 24 + 21A/45 + 39(e)-(f): withdrawal + education + fund income."]},
{n:21, title:"T.M.A. Pai (31 Oct 2002, 11 judges)", take:"Minority unit = STATE, not all-India (Sikhs majority in Punjab). Art 30 needs established AND administered. Regulation for excellence allowed (teachers, accounts, no capitation); destroying minority character barred. 15(5)/93rd quota excepts Art 30 institutions.",
 si:"Unit question = State; 15(5) expressly excludes minority institutions.",
 how:["Sikhs minority everywhere, unit all-India — WRONG. Unit is State.",
 "Art 30 needs only administration — WRONG. BOTH limbs: established AND administered.",
 "Govt can't fix qualifications / ban profiteering in minority schools — WRONG. Reasonable regulation allowed; takeover destroying character barred."]},
{n:22, title:"Sabarimala — PENDING, never settled", take:"4:1 on 28 Sept 2018 struck 10–50 bar (devotees NOT denomination, bar NOT essential; Indu Malhotra dissented). 14 Nov 2019 (3:2) kept reviews pending, referred to 9 judges. 10 Feb 2020 reference maintainable; bench notified 4 April 2026 (CJI Surya Kant), hearing from 7 April 2026 — NO final verdict.",
 si:"On duty/answer never quote 2018 as final — write 2018 (4:1) + reference pending.",
 how:["2018 is settled law — WRONG. Exists on paper; larger reference unresolved = pending.",
 "Reviews rejected, no reference — WRONG. 50+ reviews; 14 Nov 2019 referral on Arts 25/26 + essential practices.",
 "Malhotra concurred / devotees separate denomination — WRONG. She dissented; majority: not denomination, bar not essential; Kerala Rule 3(b) struck on paper."]},
{n:23, title:"Maratha quota — 102nd → 105th (2021)", take:"Jaishri Patil 5 May 2021 struck Maratha quota (no SEBC proof, no extraordinary case past 50%) + 3:2 read 102nd (2018: 338B + 342A) as Centre-only SEBC list (Rao/Gupta/Bhat vs Bhushan/Nazeer). 105th (19 Aug 2021) restored States' own lists.",
 si:"Two amendments close together = judgment sits between.",
 how:["Maratha quota upheld, 64–65% valid — WRONG. Struck: not SEBC-shown + 50% breach.",
 "102nd always let States list SEBCs — WRONG as read May 2021. Majority: President + Parliament only; State lists froze.",
 "A: Parliament passed 105th (T). R: 102nd read as taking States' power (T). R EXPLAINS A."]},
{n:24, title:"Janhit Abhiyan / EWS (7 Nov 2022, 3:2)", take:"103rd (2019) 15(6)/16(6) 10% EWS (non-SC/ST/OBC) upheld — Maheshwari/Trivedi/Pardiwala vs Lalit/Bhat. 50% ceiling NOT basic structure; EWS sits outside it. 15(6) valid even for private unaided.",
 si:"Unlearn never-cross-50%: 50% governs 16(4) backward quotas, not EWS.",
 how:["Any total above 50% automatically unconstitutional — WRONG now. A false, R (Sawhney ceiling) true.",
 "Economic-only EWS breaks basic structure / excluding SC-ST-OBC discriminates — WRONG per majority. Exclusion avoids double benefit.",
 "103rd can't apply to private unaided — WRONG. Majority: 15(6) application valid."]},
{n:25, title:"Governor vs Bills — EVOLVING, in flux", take:"Art 200 silent on days → fight. Punjab Nov 2023 (Chandrachud): can't sit forever. TN 8 April 2025 (Pardiwala + Mahadevan): 1–3 month timelines + 10 Bills deemed assented. Reference 20 Nov 2025 unanimous (Gavai, on President's 14 questions of 13 May 2025): NO judicial timelines, NO deemed assent via Art 142 — but limited mandamus to decide OK. Art 361 immunity personal only; Money Bills can't be returned.",
 si:"University/police Bills affect your orders; courts can prod to decide, not sign as Governor.",
 how:["Governor can sit indefinitely / pocket veto allowed — WRONG under both 2025 steps. Silence killing law-making violates Art 200.",
 "TN April 2025 alone is final settled law — WRONG/out of date. Present BOTH: Nov 2025 says no timelines, no deemed assent.",
 "After Nov 2025 courts can't touch inaction — WRONG. Limited mandamus to decide in reasonable time survives."]},
{n:26, title:"I.R. Coelho (11 Jan 2007, 9 judges unanimous)", take:"Post-24 April 1973 Ninth Schedule insertions open to basic-structure challenge (effect/essence test on 14/19/21); pre-1973 sealed; Art 31B itself kept. 284 entries by 2007 (~218 post-1973). Waman Rao 1981 background.",
 si:"Ninth Schedule = full immunity is false after 2007; cut-off 24 April 1973 (Kesavananda date) is heart.",
 how:["Any Schedule law immune from Part III — WRONG. A false; R (31B text protects) true; post-1973 testable.",
 "Cut-off 1973/1975/1st-Amendment date — only 24 APRIL 1973 RIGHT. 1951 created 31B; Waman Rao background.",
 "Coelho struck Art 31B itself — WRONG. 31B kept; only post-basic-structure-date misuse checked."]},
{n:27, title:"PESA 1996 (24 Dec 1996, Bhuria Committee)", take:"Part IX excluded by 243M from Fifth/Sixth Schedule + NL/ML/MZ etc. (protective). PESA under 243M(4)(b) restores with changes — Gram Sabha (all voters) is boss: plans/beneficiaries, land-acquisition consultation, tribal-land restoration, minor forest produce, intoxicants, money-lending, minor water bodies/markets, minor-mineral lease recommendation. AP: ASR, Parvathipuram Manyam, Eluru, Palnadu, Srikakulam, Anakapalli, Kakinada.",
 si:"Check Gram Sabha resolution before obstruction case on minor minerals/land in Scheduled Areas.",
 how:["Part IX directly applies / PESA is 73rd itself — WRONG. Excluded by 243M; extended via PESA.",
 "Sarpanch supreme; Sabha advisory — WRONG. Sabha supreme.",
 "Sabha has no say on intoxicants/money-mind-minerals — WRONG. Five-word key: land, forest produce, minerals, intoxicants, money-lending."]},
{n:28, title:"AP chain: Sri Bagh → Gentlemen's → Six Points → 371D", take:"Pacts calm smaller region's fear before merger: Sri Bagh 16 Nov 1937 (Coastal–Rayalaseema; Kashinathuni Nageswara Rao's house, Madras) → Gentlemen's 20 Feb 1956 (before 1 Nov 1956 AP) → agitations 1969 + 1972–73 → Six Points 21 Sept 1973 → 32nd Amend + 371D (President by ORDER, local cadres) + 371E (Central Univ Hyderabad 1974). 371D survives 2014 for AP + Telangana. 1975 Presidential Order operative.",
 si:"Zone-wise SI posting = 371D Order (local cadres/candidates).",
 how:["Gentlemen's came after formation — WRONG. 20 Feb 1956 BEFORE 1 Nov 1956; promise led to formation.",
 "Formula after 32nd / Mulki continues — WRONG. Formula 21 Sept 1973 → 32nd → 371D/371E; Mulki abolished.",
 "16(3) = 371D / 371D ended 2014 — WRONG. 16(3) Parliament by LAW residence; 371D President by ORDER cadres; survives both States."]},
{n:29, title:"Potti Sriramulu — 1953 vs 1956", take:"1953 Andhra State from DEATH (fast 19 Oct–15 Dec 1952, 58 days; Nehru announcement 19 Dec 1952; Act assented 14 Sept 1953; 11 Madras districts; Kurnool; Prakasam) vs 1956 AP from COMMISSION (SRC Fazl Ali 1953–report 1955; Reorganisation Act + 7th Amend; Hyderabad; Sanjiva Reddy). Bapatla May 1913 (B.N. Sarma) ≠ Jogipet 1930; Dar 10 Dec 1948 + JVP 1 April 1949 said NO (JVP: Andhra only if Madras claim dropped).",
 si:"Never write 1953 on SRC recommendation — SRC reported 1955, after 1953.",
 how:["1953 on SRC recommendation — WRONG on dates alone.",
 "1956 = capital Kurnool / CM Prakasam — WRONG (1953 facts). 1956: Hyderabad + Sanjiva Reddy.",
 "Bapatla 1913 = Hyderabad Sabha / Dar+JVP favoured linguistic states — WRONG. Bapatla = Madras demand; Jogipet 1930 different; Dar+JVP said no."]},
];

/* Exam-hall cautions — read with Q1 of every mock */
const EXAM_CAUTIONS = [
"106th Amendment (Nari Shakti, 2023: Arts 330A/332A/239AA/334A) — one-third women in Lok Sabha + Assemblies ONLY after first census after commencement PLUS delimitation; not operative alone; 15 years; rotation after delimitation; NO Rajya Sabha / Councils.",
"Lok Sabha maximum 550 = 530 States + 20 UTs (Art 81). 552 before 104th removed Anglo-Indian nomination (Jan 2020). Present elected strength 543.",
"AP: 26 districts since 4 April 2022. Polavaram town/project = Eluru district (Assembly 67). Nov 2025 Polavaram-district proposal is only a proposal.",
];
