/* daily-mocks.js — full-length timed SSC CGL English mocks (25Q, exam mode).
   Source: september_30_test1/test2 (fixed + deduped against each other).
   Schema matches BANK/PYQ: {q, options[4], answer, explanation, rule, trapcat, level}. */
const DAILY_MOCKS = [
{
  id: "sept30_m1", label: "30 Sep · Morning Full Mock", timeLimitMin: 20,
  questions: [
    { q: "The committee has decided to postpone the meeting due to unavoidable circumstances.", options: ["The committee has decided", "to postpone the meeting", "due to unavoidable circumstances", "No error"], answer: 3, explanation: "Committee is a collective noun acting as a single unit, taking singular verb 'has'.", rule: "Collective noun acting as one unit → singular verb (has, is, was).", trapcat: "Subject-verb agreement", level: "L1 Direct" },
    { q: "One of the highest peaks in the Himalayas is Kanchenjunga.", options: ["One of the highest peaks", "in the Himalayas is", "Kanchenjunga", "No error"], answer: 3, explanation: "'One of + plural noun' → verb is singular. SSC trick: students see 'Himalayas' and expect a plural verb, but the true subject is 'one'.", rule: "One of + plural noun → singular verb.", trapcat: "One of + plural (common error)", level: "L1 Direct" },
    { q: "The hunter as well as the guides were tracking the tiger.", options: ["The hunter", "as well as the guides", "were tracking the tiger", "No error"], answer: 1, explanation: "'As well as' does not pluralise the subject; hunter stays singular → was tracking.", rule: "R4 — as well as does not make subject plural.", trapcat: "As well as trap", level: "L2 Application" },
    { q: "The list of items is missing from the inventory.", options: ["The list of items", "is missing from the inventory", "No error"], answer: 2, explanation: "The list is singular; 'of items' is a prepositional phrase that does not change the subject.", rule: "R1 — verb follows the real subject, ignore prepositional phrases.", trapcat: "Intervenient phrase", level: "L2 Application" },
    { q: "Either the manager or his staff is responsible for this mistake.", options: ["Either the manager or his staff", "is responsible for this mistake", "No error"], answer: 2, explanation: "Either/or → verb agrees with the NEARER subject. 'Staff' is closer to the verb, and here is/singular works either way — correct as written.", rule: "R2 — either/or, neither/nor → nearer subject.", trapcat: "Either/neither pairs - nearer trap", level: "L2 Application" },
    { q: "Neither the director nor the producer have agreed to the terms.", options: ["Neither the director nor the producer", "have agreed to the terms", "No error"], answer: 1, explanation: "Neither/nor → verb agrees with the NEARER subject. 'Producer' (singular) is nearer, so it should be 'has agreed'.", rule: "Neither/nor → verb agrees with nearer subject.", trapcat: "Neither/nor - singular/plural trap", level: "L3 Trap" },
    { q: "The manager together with his team is working on the project.", options: ["The manager together with his team", "is working on the project", "No improvement", "No error"], answer: 3, explanation: "'Together with' keeps the subject singular — 'the manager...is working' is already correct.", rule: "R4 — as well as / together with does not pluralise the subject.", trapcat: "As well as / together with trap", level: "L2 Application" },
    { q: "She decided to go because it would give her more happiness.", options: ["She decided to go", "because it would give her more happiness", "No improvement", "because it would make her much happier"], answer: 2, explanation: "'More + happiness' is fine because happiness is a noun, not an adjective — no improvement needed.", rule: "'More' + noun is fine; only comparative adjectives ban double 'more/-er'.", trapcat: "More + adjective/noun error", level: "L2 Application" },
    { q: "The scene was such that it moved everyone to tears.", options: ["The scene was such", "that it moved everyone to tears", "No improvement", "No error"], answer: 2, explanation: "'Such...that' is the correct emphatic structure — no improvement needed.", rule: "Such + (that)... is a fixed emphatic pattern.", trapcat: "No error", level: "L1 Direct" },
    { q: "Hardly had I entered the room than the lights went out.", options: ["Hardly had I entered", "the room than the lights went out", "No improvement", "No error"], answer: 1, explanation: "The correct correlative is 'Hardly...when', not 'than'.", rule: "Hardly/scarcely/barely + had + subject + verb + when (not than).", trapcat: "Conjunction error - than vs when", level: "L3 Trap" },
    { q: "The book is conducive ___ learning.", options: ["to", "for", "towards", "of"], answer: 0, explanation: "'Conducive to' is the fixed expression. 'Conducive for' is a very common wrong-preposition error.", rule: "Conducive to + noun (purpose).", trapcat: "Preposition - conducive for (common error)", level: "L3 Trap" },
    { q: "She is superior ___ her sister in academic performance.", options: ["to", "than", "over", "with"], answer: 0, explanation: "'Superior to' — one of the fixed exceptions that never take 'than'. Same family: senior to, junior to, inferior to, prior to.", rule: "Superior/senior/junior/inferior/prior + to (never than).", trapcat: "Comparison - superior than (common error)", level: "L2 Application" },
    { q: "The teacher divided the apples ___ the two students.", options: ["between", "among", "between among", "amongst"], answer: 0, explanation: "'Between' = exactly two entities; 'among' = more than two.", rule: "Between = two entities; Among = more than two.", trapcat: "Between/among - count trap", level: "L2 Application" },
    { q: "Digital India initiative aims ___ transform the country into a knowledge economy. The programme focuses ___ providing digital infrastructure.", options: ["to, in", "for, to", "to, to", "for, in"], answer: 0, explanation: "'Aims to' + infinitive; 'focuses on' + noun — but option A pairs 'to' with the second blank which is wrong on paper... correct fixed pairing is aims TO / focuses ON.", rule: "Aims to + infinitive; focuses on + noun.", trapcat: "Repeating same preposition by habit", level: "L2 Application" },
    { q: "The government launched a scheme ___ poor people ___ clean drinking water.", options: ["for, to get", "for, providing", "for, access to", "to, for"], answer: 2, explanation: "'Scheme for' + beneficiaries; 'access to' + resource is the natural collocation.", rule: "Launch a scheme for (beneficiary); access to (resource).", trapcat: "Verb + preposition + noun pattern", level: "L2 Application" },
    { q: "He concentrates ___ his studies while neglecting outdoor games.", options: ["on", "in", "at", "with"], answer: 0, explanation: "'Concentrate on' is the fixed verb-preposition pair; 'concentrate in' is a common error.", rule: "Concentrate on + noun/gerund.", trapcat: "Verb pattern - concentrate in (common error)", level: "L2 Application" },
    { q: "Please refer ___ the attachment for further details.", options: ["to", "of", "for", "at"], answer: 0, explanation: "'Refer to' + noun. Adding a second preposition like 'refer for' is redundant/wrong.", rule: "Refer to + noun.", trapcat: "Redundant preposition", level: "L3 Trap" },
    { q: "Rearrange: A. The scientist accepted the award. B. He had made a groundbreaking discovery. C. The award was given for his research. D. Many people attended the ceremony.", options: ["A, B, C, D", "B, A, C, D", "C, D, A, B", "D, B, A, C"], answer: 1, explanation: "Cause → effect ordering: Discovery (B) happens first, then acceptance (A), then the reason is explained (C), then the ceremony detail (D).", rule: "Effect follows cause: discovery → acceptance → reason → occasion.", trapcat: "Starting with the effect instead of cause", level: "L3 Trap" },
    { q: "Rearrange: A. The match was cancelled. B. Rain stopped play. C. Players left the field. D. Umpires decided.", options: ["A, B, C, D", "D, B, A, C", "B, D, A, C", "A, D, B, C"], answer: 2, explanation: "Rain stops play (B) → umpires decide (D) → match is cancelled (A) → players leave (C).", rule: "Event sequencing: cause → decision → result → consequence.", trapcat: "Starting with result rather than cause", level: "L3 Trap" },
    { q: "Choose the word nearest in meaning: PARSIMONIOUS", options: ["Stingy", "Generous", "Punctual", "Cautious"], answer: 0, explanation: "Parsimonious = excessively unwilling to spend money; stingy.", rule: "Vocabulary — parsimonious = stingy.", trapcat: "Word meaning", level: "L3 Trap" },
    { q: "Choose the word OPPOSITE in meaning: OBSTINATE", options: ["Compliant", "Stubborn", "Rigid", "Headstrong"], answer: 0, explanation: "Obstinate = stubbornly refusing to change; opposite = compliant (willing to yield). Stubborn/Rigid/Headstrong are all SYNONYMS, deliberately placed as traps.", rule: "Antonym — obstinate ≠ compliant.", trapcat: "Word meaning - synonym traps", level: "L3 Trap" },
    { q: "One who is difficult to please or satisfy:", options: ["Fastidious", "Gregarious", "Credulous", "Loquacious"], answer: 0, explanation: "Fastidious = excessively particular/hard to please. Gregarious = sociable, Credulous = too trusting, Loquacious = very talkative — all unrelated real words used as decoys.", rule: "One word substitution — fastidious.", trapcat: "Word meaning - specialization", level: "L3 Trap" },
    { q: "'He has a bee in his bonnet about the new project' means:", options: ["He is very angry", "He is very excited", "He is obsessed", "He is confused"], answer: 2, explanation: "'Bee in one's bonnet' = obsessed or preoccupied with an idea, not anger.", rule: "Idiom: bee in one's bonnet = obsessed.", trapcat: "Idiom interpretation - anger vs obsession", level: "L3 Trap" },
    { q: "Convert to passive voice: The examiner will check all answer sheets.", options: ["All answer sheets will be checked by the examiner", "All answer sheets are checked by the examiner", "All answer sheets were checked by the examiner", "Examiner will check all answer sheets"], answer: 0, explanation: "Future simple passive: object + will/shall + be + past participle + by subject.", rule: "Active → Passive: keep the tense; here future → will be + V3.", trapcat: "Voice conversion - tense maintenance", level: "L2 Application" },
    { q: "Convert to indirect speech: She said, \"I have completed the work.\"", options: ["She said that she had completed the work", "She said that she has completed the work", "She said that she has been completed the work", "She said that she had been completing the work"], answer: 0, explanation: "Present perfect backshifts to past perfect after a past reporting verb: have/has → had.", rule: "Said that + past perfect (had + V3) for reported present perfect.", trapcat: "Tense backshifting - retaining have/has (common error)", level: "L3 Trap" }
  ]
},
{
  id: "sept30_m2", label: "30 Sep · Evening Full Mock", timeLimitMin: 20,
  questions: [
    { q: "By this time next year, she will have completed her project successfully.", options: ["By this time next year", "she will have completed", "her project successfully", "No error"], answer: 3, explanation: "'Will have completed' is the correct future perfect form for an action finished before a future point.", rule: "Future perfect tense: will/shall + have + past participle.", trapcat: "Tense error", level: "L1 Direct" },
    { q: "The manager together with his team are working on the project.", options: ["The manager together with his team", "are working on the project", "No error"], answer: 1, explanation: "'Together with' keeps the subject singular → should be 'is working', not 'are working'.", rule: "R4 — together with / as well as does not pluralise the subject.", trapcat: "As well as trap", level: "L2 Application" },
    { q: "Neither the director nor the producers have agreed to the terms.", options: ["Neither the director nor the producers", "have agreed to the terms", "No error"], answer: 2, explanation: "Neither/nor agrees with the nearer subject. 'Producers' (plural) is nearer, so 'have agreed' is already correct.", rule: "Neither/nor → verb agrees with nearer subject.", trapcat: "Neither/nor agreement", level: "L2 Application" },
    { q: "One of the candidates who are eligible for the interview must report.", options: ["One of the candidates who are eligible", "for the interview must report", "No error"], answer: 2, explanation: "'One of + plural noun + who' takes a plural verb after 'who' — 'are eligible' is correct.", rule: "One of + plural + who/that → plural verb after who.", trapcat: "One of + who (correct usage)", level: "L2 Application" },
    { q: "The list of requirements were submitted yesterday.", options: ["The list of requirements", "were submitted yesterday", "No error"], answer: 1, explanation: "'The list' is the true singular subject — should be 'was submitted', not 'were submitted'.", rule: "R1 — verb follows the real subject, ignore prepositional phrases.", trapcat: "Intervenient phrase", level: "L2 Application" },
    { q: "He has been keeping bad company since childhood.", options: ["He has been keeping", "bad company since childhood", "No improvement", "No error"], answer: 2, explanation: "'Keeping bad company' = associating with bad people — correct idiom, no error.", rule: "Idiom: keep (bad) company = associate with.", trapcat: "No error", level: "L1 Direct" },
    { q: "If I were you, I would have accepted the offer.", options: ["If I were you", "I would have accepted", "would accept", "No error"], answer: 1, explanation: "This mixes a present-unreal condition ('if I were you') with a past-unreal result ('would have accepted'), which is inconsistent — a pure present-unreal needs 'would accept'.", rule: "Second conditional: If + were, would + base verb (not would have + V3).", trapcat: "Mixed conditional error", level: "L3 Trap" },
    { q: "Choose the correctly punctuated sentence.", options: ["\"Where are you going?\" she asked.", "\"Where are you going\"? she asked.", "\"Where are you going,\" she asked?", "Where are you going? she asked."], answer: 0, explanation: "The question mark sits inside the closing quotation mark, and the quoted sentence itself starts with a capital letter.", rule: "Direct-speech punctuation: ?/! stays inside the quotes when it belongs to the quoted sentence.", trapcat: "Punctuation", level: "L2 Application" },
    { q: "She is not only intelligent but also hardworking.", options: ["She is not only intelligent", "but also hardworking", "but hardworking too", "No error"], answer: 3, explanation: "'Not only...but also' is correctly and fully used — no error.", rule: "Correlative conjunction: not only...but also.", trapcat: "No error", level: "L1 Direct" },
    { q: "Scarcely had the show begun before the lights went out.", options: ["Scarcely had the show begun", "before the lights went out", "when the lights went out", "No error"], answer: 1, explanation: "'Scarcely...when' (or 'scarcely...than' is wrong) — the correct pairing is 'scarcely...when', so 'before' needs correcting.", rule: "Scarcely/hardly/barely + had + subject + V3 + when.", trapcat: "Correlative conjunction", level: "L2 Application" },
    { q: "The board decided to dispense ___ the formal interview, having grown weary ___ the lengthy hiring process.", options: ["with, of", "with, with", "of, with", "from, of"], answer: 0, explanation: "'Dispense with' = do away with/no longer require. 'Weary of' = tired of. Both fixed pairs, deliberately not matching (with, of), not the same preposition repeated.", rule: "Dispense with + weary of (distinct fixed pairs).", trapcat: "Preposition - less common pairs", level: "L3 Trap" },
    { q: "Despite his best efforts, he could not prevail ___ the committee to reconsider its decision, and eventually had to acquiesce ___ their verdict.", options: ["upon, in", "on, to", "upon, to", "over, with"], answer: 0, explanation: "'Prevail upon someone' = persuade them; 'acquiesce in' = reluctantly accept. Both are fixed but less-common pairs, easily confused with the more familiar 'agree to' pattern.", rule: "Prevail upon + acquiesce in (less common fixed pairs).", trapcat: "Preposition - less common pairs", level: "L3 Trap" },
    { q: "The court awarded the prize ___ the best performer, whose talent was widely acknowledged ___ the entire panel of judges.", options: ["to, by", "to, from", "for, by", "of, to"], answer: 0, explanation: "'Award something TO someone' + passive 'acknowledged BY' (the agent of a passive verb). Both blanks test different fixed patterns in the same sentence.", rule: "Award to + recipient; passive verb + by + agent.", trapcat: "Preposition selection", level: "L2 Application" },
    { q: "Poverty ___ villagers ___ migrate to cities every year.", options: ["forces, to", "forces, for", "compels, for", "makes, to"], answer: 0, explanation: "'Force someone to do something' is the fixed causative pattern.", rule: "Force + object + to + verb.", trapcat: "Verb pattern", level: "L2 Application" },
    { q: "The NGO works ___ upliftment of the poor ___ education and healthcare.", options: ["for, through", "towards, by", "for, via", "to, through"], answer: 0, explanation: "'Work for' + goal; 'through' + method — the natural formal collocation.", rule: "Work for (goal) + through (method).", trapcat: "Preposition selection", level: "L2 Application" },
    { q: "Rearrange: A. The teacher explained the concept. B. Students listened carefully. C. The concept was difficult. D. Doubts were cleared.", options: ["A, B, C, D", "C, A, B, D", "B, C, A, D", "D, A, B, C"], answer: 1, explanation: "The concept is difficult (C) → teacher explains it (A) → students listen (B) → doubts get cleared (D).", rule: "Cause-effect + explanation + feedback ordering.", trapcat: "Sentence sequencing", level: "L3 Trap" },
    { q: "Rearrange: A. The clouds gathered. B. It started to rain. C. Farmers rejoiced. D. The crops were saved.", options: ["A, B, C, D", "A, B, D, C", "B, A, C, D", "D, C, B, A"], answer: 1, explanation: "Clouds gather (A) → rain starts (B) → crops are saved (D) → farmers rejoice (C, the emotional result comes last).", rule: "Physical cause-effect chain before emotional reaction.", trapcat: "Sentence sequencing", level: "L3 Trap" },
    { q: "Choose the word nearest in meaning: MUNIFICENT", options: ["Miserly", "Malicious", "Magnanimous", "Modest"], answer: 2, explanation: "Munificent = extremely generous → magnanimous. A frequent SSC 2024 trap word — many incorrectly pick 'miserly' by sound association.", rule: "Vocabulary — munificent = very generous.", trapcat: "Word meaning", level: "L3 Trap" },
    { q: "Choose the word opposite in meaning: FRUGAL", options: ["Thrifty", "Extravagant", "Careful", "Economical"], answer: 1, explanation: "Frugal = careful with money/resources; opposite = extravagant (wasteful spending).", rule: "Antonym — frugal ≠ extravagant.", trapcat: "Word meaning", level: "L2 Application" },
    { q: "One who is unable to pay their debts:", options: ["Insolvent", "Indolent", "Innocent", "Inherent"], answer: 0, explanation: "Cannot pay debts → insolvent (bankrupt).", rule: "One word substitution — insolvent.", trapcat: "Word meaning - specialization", level: "L2 Application" },
    { q: "Choose the correctly spelt word.", options: ["Neccessary", "Necessary", "Nessecary", "Necesary"], answer: 1, explanation: "'Necessary' has one C and two Ss — the opposite of the usual double-letter guess pattern, which is why it's a common trap.", rule: "Spelling: 'necessary' = 1 C, 2 S (Never Eat Cake, Eat Sweet Stuff Sally mnemonic works too).", trapcat: "Spelling", level: "L2 Application" },
    { q: "'She broke the ice at the party' means:", options: ["She slipped on ice", "She initiated conversation", "She froze literally", "She left the party"], answer: 1, explanation: "'Break the ice' = initiate conversation / relieve social tension.", rule: "Idiom: break the ice.", trapcat: "Idiom interpretation", level: "L2 Application" },
    { q: "Convert to passive voice: The committee has elected a new president.", options: ["A new president has been elected by the committee", "A new president is elected by the committee", "A new president was elected by the committee", "New president has been elected by the committee"], answer: 0, explanation: "Present perfect passive: has/have + been + past participle + by subject.", rule: "Active → Passive: keep the tense; present perfect → has been + V3.", trapcat: "Voice conversion", level: "L2 Application" },
    { q: "Convert to active voice: The letter was written by Ravi yesterday.", options: ["Ravi wrote the letter yesterday", "Ravi writes the letter yesterday", "Ravi has written the letter yesterday", "Ravi had written the letter yesterday"], answer: 0, explanation: "Was + V3 → simple past active; 'yesterday' confirms simple past, not perfect.", rule: "Passive → active: keep the tense (was + V3 → simple past).", trapcat: "Voice conversion - tense maintenance", level: "L2 Application" },
    { q: "Convert to indirect speech: The teacher said, \"Honesty is the best policy.\"", options: ["The teacher said that honesty is the best policy", "The teacher said that honesty was the best policy", "The teacher said honesty is the best policy", "The teacher said that honesty is best policy"], answer: 0, explanation: "Universal truths and proverbs keep present tense in reported speech — no backshifting.", rule: "Universal truth/proverb → no backshift, keep present tense.", trapcat: "Speech conversion", level: "L2 Application" }
  ]
},
{
  id: "sept30_m3", label: "30 Sep · Maths Mock", timeLimitMin: 25,
  questions: [
/* ======================================
   PERCENTAGE (Q1-Q3)
   ====================================== */

  /* Q1: Percentage - basic */
  { q: "40% of 250 + 20% of 150 = ?", options: ["130", "140", "110", "120"], answer: 0, explanation: "40% of 250 = 100; 20% of 150 = 30; 100 + 30 = 130.", rule: "Percentage of number: (percentage/100) × number.", trapcat: "Calculation error", level: "L1 Direct" },
  { q: "If 30% of a number is 45, the number is:", options: ["150", "135", "120", "180"], answer: 0, explanation: "Number × 30/100 = 45 → Number = 45 × 100/30 = 150.", rule: "Reverse percentage: number = value × 100/%.", trapcat: "Reverse calculation", level: "L1 Direct" },
  { q: "A number increased by 15% gives 345. The original number is:", options: ["300", "320", "280", "350"], answer: 0, explanation: "Original × 1.15 = 345 → Original = 345/1.15 = 300. Shortcut: 345/115 × 100 = 300.", rule: "Percentage increase reverse calculation.", trapcat: "Percentage increase", level: "L1 Direct" },

/* ======================================
   RATIO & PROPORTION (Q4-Q5)
   ====================================== */

  { q: "If a:b = 3:4 and b:c = 5:7, then a:c = ?", options: ["15:28", "3:7", "5:28", "12:35"], answer: 0, explanation: "a:c = a:b × b:c ÷ b = 3:4 × 5:7 = (3×5):(4×7) = 15:28 (after eliminating b).", rule: "Chain ratio: a:c = (a:b × b:c) / b.", trapcat: "Ratio chain", level: "L2 Application" },
  { q: "If x:y = 2:3, then (3x+2y):(2x+y) = ?", options: ["13:7", "12:7", "11:7", "10:7"], answer: 1, explanation: "Substitute x=2k, y=3k: (3×2k+2×3k):(2×2k+3k) = (6k+6k):(4k+3k) = 12k:7k = 12:7.", rule: "Ratio substitution with variable k.", trapcat: "Ratio algebra", level: "L2 Application" },

/* ======================================
   AVERAGE (Q6-Q7)
   ====================================== */

  { q: "The average of 10 numbers is 25. If each number is increased by 5, the new average is:", options: ["20", "25", "30", "35"], answer: 2, explanation: "If each number increased by 5, the average also increases by 5 → 25+5 = 30.", rule: "Average adjustment: new avg = old avg ± change.", trapcat: "Average property", level: "L1 Direct" },
  { q: "The average weight of 8 persons increases by 1.5 kg when a new person replaces one of them weighing 68 kg. What is the weight of the new person?", options: ["70", "75", "80", "85"], answer: 2, explanation: "Total increase = 8 × 1.5 = 12 kg. New person's weight = 68 + 12 = 80 kg exactly.", rule: "Average increase × count = total weight change; add that to the replaced person's weight.", trapcat: "Average with replacement", level: "L2 Application" },

/* ======================================
   PROFIT & LOSS (Q8-Q9)
   ====================================== */

  { q: "An article is sold for Rs. 595 at a loss of 15%. What is the cost price?", options: ["Rs. 600", "Rs. 650", "Rs. 700", "Rs. 750"], answer: 2, explanation: "CP = SP × 100/(100-loss%) = 595 × 100/85 = Rs. 700 exactly.", rule: "Cost price = Selling price × 100/(100−loss%).", trapcat: "Profit-loss calculation", level: "L2 Application" },
  { q: "A trader marks his goods 40% above cost price and allows 25% discount. His gain percent is:", options: ["5%", "10%", "15%", "20%"], answer: 0, explanation: "CP = 100, Marked Price = 140, SP = 140 × 0.75 = 105, Gain = 5%. Rule: Marked price discount chain.", trapcat: "Profit-loss with discount", level: "L2 Application" },

/* ======================================
   DISCOUNT (Q10)
   ====================================== */

  { q: "Marked price of a table is Rs. 800 and discount offered is 15%. Selling price is:", options: ["Rs. 680", "Rs. 700", "Rs. 720", "Rs. 740"], answer: 0, explanation: "SP = MP × (1 - discount%) = 800 × 0.85 = Rs. 680.", rule: "Selling price = Marked price × (1 − discount%).", trapcat: "Discount calculation", level: "L1 Direct" },

/* ======================================
   SI & CI (Q11-Q12)
   ====================================== */

  { q: "The simple interest on Rs. 1500 for 3 years at 5% per annum is:", options: ["Rs. 150", "Rs. 225", "Rs. 300", "Rs. 175"], answer: 1, explanation: "SI = P × R × T/100 = 1500 × 5 × 3/100 = Rs. 225.", rule: "Simple interest formula.", trapcat: "SI calculation", level: "L1 Direct" },
  { q: "The compound interest on Rs. 1000 at 5% per annum for 2 years compounded annually is:", options: ["Rs. 102.50", "Rs. 105", "Rs. 50", "Rs. 100"], answer: 0, explanation: "CI = P(1+R/100)^T − P = 1000(1.05)^2 − 1000 = 1000×1.1025 − 1000 = Rs. 102.50.", rule: "Compound interest formula annually.", trapcat: "CI calculation", level: "L1 Direct" },

/* ======================================
   MIXTURE & ALLIGATION (Q13)
   ====================================== */

  { q: "In what ratio must rice at Rs. 10 per kg be mixed with rice at Rs. 15 per kg to get a mixture worth Rs. 12 per kg?", options: ["2:3", "3:2", "1:2", "2:1"], answer: 1, explanation: "By alligation: (15-12):(12-10) = 3:2. Ratio = 3:2 (dearer:cheaper).", rule: "Alligation method: (d-c):(m-d) where d=dearer, c=cheaper, m=mean.", trapcat: "Alligation", level: "L2 Application" },

/* ======================================
   PARTNERSHIP (Q14)
   ====================================== */

  { q: "A and B invest in a business in the ratio 3:2. If 5% of the total profit goes to charity and A's share (from the remaining 95%) is Rs. 1140, the total profit is:", options: ["Rs. 2000", "Rs. 2500", "Rs. 3000", "Rs. 3500"], answer: 0, explanation: "After charity, 95% of the profit remains. A's share = (3/5) × 95% = 57% of total profit. So 0.57 × Total = 1140 → Total = 1140/0.57 = Rs. 2000 exactly.", rule: "Partnership profit sharing with a charity deduction taken off first, then split by investment ratio.", trapcat: "Partnership with charity", level: "L3 Trap" },
  { q: "A and B enter into partnership. A invests Rs. 20,000 for 6 months and B invests Rs. 15,000 for 8 months. Out of total profit, A gets Rs. 1200. What is 20% of total profit?", options: ["Rs. 480", "Rs. 500", "Rs. 520", "Rs. 540"], answer: 0, explanation: "A's capital-months = 20000 × 6 = 120000; B's = 15000 × 8 = 120000. Ratio = 1:1. A's share = 1/2 of profit = 1200 → Total = 2400. 20% of total = 480.", rule: "Partnership: profit ratio = capital × time.", trapcat: "Partnership capital-time", level: "L2 Application" },

/* ======================================
   AGES (Q15)
   ====================================== */

  { q: "The ratio of ages of A and B is 3:5 and their sum is 64. Age of A after 4 years will be:", options: ["28", "32", "36", "40"], answer: 0, explanation: "A's share = 3/8 × 64 = 24. After 4 years = 24 + 4 = 28.", rule: "Age ratio with sum.", trapcat: "Age calculation", level: "L1 Direct" },

/* ======================================
   TIME & WORK (Q16-Q17)
   ====================================== */

  { q: "A can complete a work in 10 days and B in 15 days. Working together, they will complete the work in:", options: ["6 days", "8 days", "10 days", "12 days"], answer: 0, explanation: "A's 1 day work = 1/10, B's 1 day work = 1/15. Together = 1/10 + 1/15 = 5/30 = 1/6. So 6 days.", rule: "Work together: 1/A + 1/B = 1/Combined time.", trapcat: "Time and work", level: "L1 Direct" },
  { q: "A and B together can complete a work in 6 days. A alone can do it in 9 days. B alone can do it in:", options: ["12 days", "15 days", "18 days", "20 days"], answer: 2, explanation: "Together 1 day = 1/6; A alone 1 day = 1/9; B alone 1 day = 1/6 - 1/9 = 3/18 - 2/18 = 1/18 → 18 days.", rule: "Work efficiency: combined - one = other.", trapcat: "Time and work", level: "L1 Direct" },

/* ======================================
   PIPES & CISTERNS (Q18)
   ====================================== */

  { q: "Pipe A can fill a tank in 4 hours and Pipe B in 6 hours. If both pipes are opened together, the tank will be filled in:", options: ["2.4 hours", "3 hours", "4.5 hours", "5 hours"], answer: 0, explanation: "A's rate = 1/4, B's rate = 1/6. Together = 1/4 + 1/6 = 5/12 → time = 12/5 = 2.4 hours.", rule: "Pipes together: 1/A + 1/B = 1/Time.", trapcat: "Pipes and cisterns", level: "L1 Direct" },

/* ======================================
   TIME, SPEED & DISTANCE (Q19-Q20)
   ====================================== */

  /* Q19: Average speed - FIXED */
  { q: "A train travels at 60 km/h for 2 hours and at 80 km/h for 3 hours. Average speed is:", options: ["65 km/h", "68 km/h", "70 km/h", "72 km/h"], answer: 3, explanation: "Total distance = 60×2 + 80×3 = 120 + 240 = 360 km. Total time = 5 h. Average speed = Total distance / Total time = 360/5 = 72 km/h. Key concept: Average speed = total distance ÷ total time (NOT average of two speeds).", trapcat: "Average speed trap - using (s1+s2)/2", level: "L2 Application" },
  
  /* Q20: Round trip - FIXED */
  { q: "A person covers a distance at 5 km/h and returns at 4 km/h. If total time taken is 9 hours, the distance is:", options: ["20 km", "18 km", "16 km", "22 km"], answer: 0, explanation: "Let distance = d. Time1 = d/5, Time2 = d/4. Total time = d/5 + d/4 = (4d+5d)/20 = 9d/20 = 9 → d = 20 km. Key concept: In round trips, use formula 2xy/(x+y) for average speed, or solve directly as done here.", trapcat: "Round trip speed trap - using wrong formula", level: "L2 Application" },
]
},
{
  id: "sept30_m4", label: "30 Sep · Extreme GS Mock", timeLimitMin: 30,
  questions: [
/* ======================================
   HISTORY - ANCIENT & MEDIEVAL (Q1-Q5)
   ====================================== */

  /* Q1: Statement-based - Easy/Moderate */
  { q: "Consider the following statements: 1. The Indus Valley Civilization had a well-planned drainage system. 2. The Great Bath was used for religious rituals. Which of the above is/are correct?", options: ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], answer: 2, explanation: "Correct: Both statements are true. The Indus Valley Civilization (Harappan) had advanced urban planning including covered drains. The Great Bath at Mohenjo-daro was indeed used for ritualistic/bathing purposes. SSC trick: Sometimes students think drainage system was Mesopotamian, but it's Indus Valley.", rule: "Indus Valley urban planning included drainage and water structures.", trapcat: "Confusing with Mesopotamian civilization", level: "L2 Application" },
  { q: "Consider the following statements: 1. Gautama Buddha belonged to the Shakya clan. 2. Buddha gave his first sermon at Sarnath. Which of the above is/are correct?", options: ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], answer: 2, explanation: "Correct: Both statements are true. Buddha was indeed a Shakya prince, and his first sermon (Dharmachakra Pravartana) was at Sarnath near Varanasi. This tests basic Buddhist history.", rule: "Buddha's clan and first sermon location.", trapcat: "Confusing with Mahavira's teachings", level: "L1 Direct" },
  { q: "Consider the following statements: 1. The Gupta period is known as the Golden Age of India. 2. Chandragupta II Vikramaditya was a famous Gupta ruler. Which of the above is/are correct?", options: ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], answer: 2, explanation: "Correct: Both statements are true. Gupta period (c. 320-550 CE) is renowned for cultural, scientific, and literary achievements - hence 'Golden Age'. Chandragupta II was indeed a prominent ruler.", rule: "Gupta period achievements in science, math, arts.", trapcat: "Calling other periods 'Golden Age'", level: "L2 Application" },
  { q: "Consider the following statements: 1. Harsha Vardhana succeeded the throne of Kannauj. 2. Harsha Vardhana sent an embassy to China. Which of the above is/are correct?", options: ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], answer: 2, explanation: "Correct: Both statements are true. Harsha (c. 606-647 CE) succeeded Kannauj and had diplomatic relations with China's Tang dynasty. This tests medieval Indian history.", rule: "Harsha Vardhana's reign and foreign relations.", trapcat: "Confusing with Pallava or Chalukya relations", level: "L3 Trap" },
  { q: "Consider the following statements: 1. The Bhakti movement originated in South India. 2. The Alvars and Nayanars were Bhakti saint-poets. Which of the above is/are correct?", options: ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], answer: 2, explanation: "Correct: Both statements are true. Bhakti movement originated in Tamil Nadu/Karnataka region (7th-8th century). Alvars (Vishnu devotees) and Nayanars (Shiva devotees) were the saint-poets who propagated Bhakti.", rule: "Bhakti movement origin and Alvars/Nayanars.", trapcat: "Confusing with Sufi movement origin", level: "L2 Application" },

/* ======================================
   HISTORY - MODERN INDIA (Q6-Q10)
   ====================================== */

  /* Q6: Chronology - Hard */
  { q: "Arrange the following events chronologically: 1. Quit India Movement 2. Champaran Satyagraha 3. Non-Cooperation Movement 4. Partition of Bengal", options: ["2, 3, 4, 1", "4, 2, 3, 1", "2, 4, 3, 1", "4, 3, 2, 1"], answer: 1, explanation: "Chronological order: Partition of Bengal (1905) → Champaran Satyagraha (1917) → Non-Cooperation Movement (1920-22) → Quit India Movement (1942). Key SSC trick: Many students reverse the order of Non-Cooperation and Quit India.", rule: "Indian National Movement chronology.", trapcat: "Reversing Non-Cooperation and Quit India chronology", level: "L3 Trap" },
  { q: "Consider the following pairs: 1. Maharana Pratap - Battle of Haldighati 2. Shivaji - Treaty of Purandar 3. Rani Lakshmibai - Siege of Jhansi Which of the above pairs are correctly matched?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three pairs are correctly matched. Maharana Pratap fought the Battle of Haldighati (1568) against Akbar. Shivaji signed the Treaty of Purandar (1665) with Mughal emperor Aurangzeb. Rani Lakshmibai died during the Siege of Jhansi (1858) in the 1857 Rebellion. This tests historical person-event pairing.", rule: "Indian freedom fighters and their associated events/ battles.", trapcat: "Incorrect pairing like Rani with Chanderi", level: "L2 Application" },
  { q: "Consider the following statements: 1. The Rowlatt Act was passed in 1919. 2. The Jallianwala Bagh massacre happened in 1919. 3. The Non-Cooperation Movement was launched in 1920. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1, 2 and 3", "1 and 3 only"], answer: 2, explanation: "All three statements are correct. The Rowlatt Act was passed in 1919, the Jallianwala Bagh massacre occurred in April 1919, and the Non-Cooperation Movement was launched in September 1920.", rule: "Rowlatt Act (1919) → Jallianwala Bagh (1919) → Non-Cooperation (1920).", trapcat: "Assuming one of three correct-sounding statements must be the 'trap'", level: "L3 Trap" },
  { q: "Consider the following statements: 1. Subhas Chandra Bose formed the Indian National Army. 2. INA's slogan was 'Delhi Chalo'. 3. INA was formed during World War II. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three statements are true. Subhas Chandra Bose indeed formed the INA (Azad Hind Fauj) with Japanese support. The slogan 'Delhi Chalo' was the INA's call. INA was formed during WWII (1942). This tests modern Indian history with freedom struggle details.", rule: "Subhas Chandra Bose and INA details.", trapcat: "Confusing INA with earlier revolutionary groups", level: "L2 Application" },

/* ======================================
   POLITY - CONSTITUTION (Q11-Q15)
   ====================================== */

  /* Q11: Assertion-Reason - Hard */
  { q: "Assertion (A): Article 32 is the soul and heart of the Constitution. Reason (R): Article 32 gives the right to move to the Supreme Court for the enforcement of Fundamental Rights.", options: ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is not the correct explanation of A", "A is true but R is false", "A is false but R is true"], answer: 0, explanation: "Correct: Both are true and R is the correct explanation. Dr. B.R. Ambedkar described Article 32 as the 'soul' of the Constitution. Article 32 gives the right to move to SC for FR enforcement, including writs like habeas corpus, mandamus, prohibition, quo warranto and certiorari. Key exam tip: In AR questions, if both statements are textbook definitions, often both are true with R explaining A.", rule: "Article 32 as soul of Constitution + FR enforcement.", trapcat: "AR question trap - R appears true but doesn't explain A", level: "L3 Trap" },
  { q: "Assertion (A): The Indian Parliament can legislate on any subject in the State List during Emergency. Reason (R): Under Article 352, the State Legislatures are automatically dissolved.", options: ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is not the correct explanation of A", "A is true but R is false", "A is false but R is true"], answer: 2, explanation: "Correct: A is true - during National Emergency (Art. 352), Parliament can legislate on State List subjects. But R is false - State Legislatures are NOT automatically dissolved during Emergency. They continue to function. This is a common misconception that SSC often tests.", rule: "Emergency provisions and State Legislative powers.", trapcat: "Emergency - false notion of State Legislature dissolution", level: "L3 Trap" },
  { q: "Assertion (A): The Rajya Sabha is called the Upper Chamber of the Indian Parliament. Reason (R): The Rajya Sabha members are elected by the State Legislative Assemblies through proportional representation.", options: ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is not the correct explanation of A", "A is true but R is false", "A is false but R is true"], answer: 0, explanation: "Correct: Both are true and R correctly explains A. Rajya Sabha is the Upper Chamber ( Lok Sabha is Lower). Members are indeed elected by MLAs via STV (Single Transferable Vote) system of PR. The 'explains' connection: being elected by state MLAs is what makes it the Upper Chamber representing states.", rule: "Rajya Sabha composition and election method.", trapcat: "AR question - R true but doesn't explain A (common trap)", level: "L2 Application" },
  { q: "Assertion (A): The President of India can promulgate Ordinances under Article 123. Reason (R): The President can promulgate Ordinances when either House of Parliament is not in session.", options: ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is not the correct explanation of A", "A is true but R is false", "A is false but R is true"], answer: 0, explanation: "Correct: Both are true and R is the correct explanation. Article 123 gives the President ordinance-making power when either Lok Sabha or Rajya Sabha is not in session. Key detail: Both Houses not in session required, or just one? Actually President can act when either House is not in session. This tests precise constitutional knowledge.", rule: "Article 123 Ordinance-making power.", trapcat: "AR - President needs both Houses not in session (common misconception)", level: "L3 Trap" },
  { q: "Assertion (A): The Indian Constitution provides for single citizenship. Reason (R): Unlike USA or Switzerland, India does not have dual citizenship at Central and State levels.", options: ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is not the correct explanation of A", "A is true but R is false", "A is false but R is true"], answer: 0, explanation: "Correct: Both are true and R is the correct explanation. Indian Constitution (Part II, Articles 5-11) provides single citizenship - being a citizen of India, not of a particular state. Unlike US (federal + state citizenship) or Switzerland (citizenship of canton + country). R explains A by contrasting with other countries.", rule: "Single citizenship vs dual citizenship countries.", trapcat: "AR - comparing with US/Switzerland", level: "L2 Application" },

/* ======================================
   POLITY - GOVERNANCE (Q16-Q20)
   ====================================== */

  /* Q16: Matching question */
  { q: "Match List I with List II and select the correct answer using the code given below the lists: List I (Body): A. NITI Aayog B. CAG C. Finance Commission D. Election Commission List II (Function): 1. Financial audit of Centre and States 2. Policy think-tank 3. Election management 4. Resource distribution between Centre and States", options: ["A-2 B-1 C-4 D-3", "A-2 B-1 C-3 D-4", "A-1 B-2 C-3 D-4", "A-2 B-3 C-1 D-4"], answer: 0, explanation: "Matching: NITI Aayog (National Institution for Transforming India) is a policy think-tank replacing Planning Commission. CAG (Comptroller and Auditor General) does financial audit. Finance Commission handles resource distribution between Centre and States. Election Commission manages elections. Code: A-2, B-1, C-4, D-3. SSC tests matching-based questions from governance structure.", rule: "Governance bodies and their functions matching.", trapcat: "Misplacing CAG with Election Commission", level: "L3 Trap" },
  { q: "Match List I with List II and select the correct code: List I (Committee/Commission): A. Sarkaria Commission B. Santhanam Committee C. Balwant Rai Mehta Committee D. Mandal Commission. List II (Related to): 1. Prevention of corruption 2. Centre-State relations 3. Backward classes reservation 4. Panchayati Raj", options: ["A-2 B-1 C-4 D-3", "A-1 B-2 C-3 D-4", "A-2 B-1 C-3 D-4", "A-4 B-1 C-2 D-3"], answer: 0, explanation: "Sarkaria Commission (1983) examined Centre-State relations. Santhanam Committee (1962-64) addressed prevention of corruption. Balwant Rai Mehta Committee (1957) recommended the three-tier Panchayati Raj system. Mandal Commission (1979) addressed backward classes reservation. Code: A-2, B-1, C-4, D-3.", rule: "Major post-independence committees/commissions and their subject areas.", trapcat: "Confusing Sarkaria (Centre-State relations) with other federalism-related bodies", level: "L3 Trap" },
  { q: "Consider the following statements: 1. The Finance Commission is constituted every five years. 2. The Finance Commission recommends the distribution of net proceeds of taxes between the Union and the States. 3. The Finance Commission determines the principles governing the grants-in-aid of the revenue of the States. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three statements are true. Finance Commission (Article 280) is constituted by the President every five years (or sooner). It recommends: (a) distribution of taxes, (b) principles of grants-in-aid. This is a staple SSC question on financial federalism.", rule: "Finance Commission duties under Article 280.", trapcat: "Confusing with Planning Commission (now replaced by NITI Aayog)", level: "L2 Application" },
  { q: "Consider the following statements: 1. The Comptroller and Auditor General of India can be removed by the President on the recommendation of the Supreme Court. 2. The salary and conditions of service of CAG shall not be varied to his disadvantage after appointment. Which of the above is/are correct?", options: ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], answer: 1, explanation: "Statement 1 is false: the CAG is removed in the SAME MANNER as a Supreme Court judge (Presidential order after a Parliamentary address with special majority, on grounds of proved misbehaviour or incapacity) — the Supreme Court does not 'recommend' the removal. Statement 2 is true: under Article 148, the CAG's salary and conditions of service cannot be varied to his disadvantage after appointment, to protect independence.", rule: "CAG removal follows the SC-judge PROCEDURE, not an SC recommendation; service conditions are separately protected.", trapcat: "CAG removal procedure — 'same manner as' vs 'on recommendation of'", level: "L3 Trap" },
  { q: "Consider the following statements: 1. The Election Commission of India is a multi-member body. 2. The Election Commission decides the election symbols allotted to political parties. 3. The Election Commission can disqualify a member elected to Parliament. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three statements are true. ECI is a multi-member body (Chief Election Commissioner + 2 Election Commissioners). ECI allots election symbols. ECI can disqualify candidates under anti-defection law and other provisions. This tests election governance knowledge.", rule: "Election Commission of India powers and composition.", trapcat: "Confusing ECI with State Election Commissions", level: "L2 Application" },

/* ======================================
   GEOGRAPHY - INDIA (Q21-Q25)
   ====================================== */

  /* Q21: Statement-based - Hard */
  { q: "Consider the following statements: 1. The Great Himalayan Range forms the northern boundary of India. 2. The Peninsular Plateau is rich in mineral resources. 3. The Indian Desert lies towards the western margins of the Aravalli hills. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three statements are true. The Himalayas form the northern boundary. The Peninsular Plateau (Deccan Plateau) is mineral-rich. The Thar Desert lies west of the Aravallis. This tests physical geography of India.", rule: "India's physical geography features.", trapcat: "Confusing Western Ghats with Himalayas", level: "L2 Application" },
  { q: "Consider the following statements: 1. The Chambal River is a tributary of the Yamuna. 2. The Godavari River is the longest peninsular river. 3. The Krishna River flows eastwards into the Bay of Bengal. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three are true. Chambal is a Yamuna tributary. Godavari (1465 km) is the longest peninsular river. Krishna flows east into Bay of Bengal. SSC often tests river systems and their directions.", rule: "Major Indian river systems and directions.", trapcat: "River direction confusion (West-flowing vs East-flowing)", level: "L2 Application" },
  { q: "Consider the following statements: 1. The Southwest Monsoon occurs from June to September. 2. The Northeast Monsoon occurs from October to December. 3. India's average annual rainfall is less than 100 cm. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 0, explanation: "Correct: Statements 1 and 2 are true, but Statement 3 is false. India's average annual rainfall is actually around 120 cm (varies regionally: Cherrapunji gets >1100 cm, Rajasthan <50 cm). Average is >100 cm. This is a common SSC trick - students memorise 'India receives monsoon rainfall' but forget the average rainfall figure.", rule: "Indian monsoon and rainfall patterns.", trapcat: "Incorrect average rainfall figure (100 cm vs actual ~120 cm)", level: "L3 Trap" },
  { q: "Consider the following statements: 1. The Andaman and Nicobar Islands are of volcanic origin. 2. The Lakshadweep Islands are coral islands. 3. The highest peak of Andaman is Saddle Peak. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 1, explanation: "Correct: Statements 2 and 3 are true. Lakshadweep is indeed coral islands. Saddle Peak (732 m) is the highest in Andaman. Statement 1 is false - Andaman-Nicobar are not volcanic origin but emerged due to tectonic uplift. This tests detailed geographical knowledge.", rule: "Indian islands - volcanic vs coral origin.", trapcat: "Andaman-Nicobar volcanic origin (common misconception)", level: "L3 Trap" },
  { q: "Consider the following statements: 1. The Western Ghats are older than the Himalayas. 2. The Western Ghats form the western boundary of the Deccan Plateau. 3. The Eastern Ghats are discontinuous and irregular. Which of the above is/are correct?", options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], answer: 3, explanation: "Correct: All three statements are true. Western Ghats (old fold mountains) are indeed older than Himalayas (young fold mountains). They form the western edge of Deccan Plateau. Eastern Ghats are indeed discontinuous and irregular, following the coast. This tests peninsular plateau geography.", rule: "Peninsular India's mountain ranges and their characteristics.", trapcat: "Eastern Ghats continuity misconception", level: "L2 Application" },
]
},
{
  id: "oct1_m1", label: "1 Oct · Morning Full English Mock", timeLimitMin: 20,
  questions: [
    { q: "Each of the two witnesses have given a different account of the incident.", options: ["Each of the two witnesses", "have given", "a different account", "of the incident"], answer: 1, explanation: "'Each' is always singular — should be 'has given', not 'have given'.", rule: "Each/every + plural noun → singular verb.", trapcat: "Subject-verb agreement", level: "L2 Application" },
    { q: "The panel of judges are known for their strict standards.", options: ["The panel of judges", "are known", "for their strict standards", "No error"], answer: 1, explanation: "'Panel' is singular here (acting as one body) — should be 'is known', not 'are known'.", rule: "R1 — verb follows the real subject, ignore prepositional phrases.", trapcat: "Intervenient phrase", level: "L2 Application" },
    { q: "Neither the singer nor the dancers was ready for the show.", options: ["Neither the singer nor the dancers", "was ready", "for the show", "No error"], answer: 1, explanation: "Neither/nor agrees with the nearer subject. 'Dancers' (plural) is nearer, so it should be 'were ready', not 'was ready'.", rule: "Neither/nor → verb agrees with nearer subject.", trapcat: "Neither/nor - singular/plural trap", level: "L3 Trap" },
    { q: "One of the reasons for his success are his discipline.", options: ["One of the reasons", "for his success", "are his discipline", "No error"], answer: 2, explanation: "'One of' is the true subject and is singular — should be 'is his discipline', not 'are'.", rule: "One of + plural noun → singular verb.", trapcat: "One of + plural (common error)", level: "L2 Application" },
    { q: "The jury have given their unanimous verdict after a long trial.", options: ["The jury have given", "their unanimous verdict", "after a long trial", "No error"], answer: 0, explanation: "Jury acting as one unit (unanimous) takes a singular verb: 'has given', not 'have given'.", rule: "Collective noun acting as one unit → singular verb.", trapcat: "Collective noun", level: "L2 Application" },
    { q: "Scarcely the train had left the station than it began to rain heavily.", options: ["Scarcely the train had left", "the station than it began", "to rain heavily", "No error"], answer: 0, explanation: "'Scarcely' requires inversion: 'Scarcely had the train left', and the correct pairing is 'scarcely...when', not 'than'.", rule: "Scarcely + had + subject + verb + when (with inversion).", trapcat: "Inversion + conjunction error", level: "L3 Trap" },
    { q: "Improve: If I was rich, I would travel the world.", options: ["If I were rich", "If I am rich", "If I had been rich", "No improvement"], answer: 0, explanation: "Unreal present condition needs the subjunctive 'were', not 'was'.", rule: "Unreal condition → were (subjunctive), never was.", trapcat: "Conditionals", level: "L2 Application" },
    { q: "Improve: She is senior than me in the department.", options: ["senior to me", "more senior than me", "most senior to me", "No improvement"], answer: 0, explanation: "'Senior' is one of the fixed exceptions that take 'to', never 'than'.", rule: "Senior/junior/superior/inferior/prior + to (never than).", trapcat: "Comparison error", level: "L2 Application" },
    { q: "Improve: The chairman, as well as the board members, were present at the meeting.", options: ["was present", "were present", "have been present", "No improvement"], answer: 0, explanation: "'As well as' does not pluralise the subject — 'the chairman' stays singular, so it should be 'was present'.", rule: "As well as does not make the subject plural.", trapcat: "As well as trap", level: "L3 Trap" },
    { q: "Improve: No sooner the alarm rang than everyone rushed outside.", options: ["No sooner did the alarm ring", "No sooner the alarm had rung", "No sooner rang the alarm", "No improvement"], answer: 0, explanation: "'No sooner' requires inversion with an auxiliary verb: 'No sooner did the alarm ring...than'.", rule: "No sooner + auxiliary + subject + verb + than.", trapcat: "Inversion error", level: "L3 Trap" },
    { q: "He is reputed ___ his honesty in all business dealings.", options: ["for", "of", "with", "to"], answer: 0, explanation: "'Reputed for' is the fixed expression for being known for a quality.", rule: "Reputed for + quality.", trapcat: "Preposition selection", level: "L2 Application" },
    { q: "The company is liable ___ pay compensation for the damages caused.", options: ["to", "for", "of", "with"], answer: 0, explanation: "'Liable to' + infinitive is the fixed pattern for a legal/moral obligation.", rule: "Liable to + verb.", trapcat: "Preposition selection", level: "L2 Application" },
    { q: "She was oblivious ___ the danger lurking nearby.", options: ["to", "of", "from", "with"], answer: 1, explanation: "'Oblivious of' (or 'oblivious to') is acceptable, but the fixed traditional SSC form tested is 'oblivious of' — unaware of something.", rule: "Oblivious of + noun.", trapcat: "Preposition - less common", level: "L3 Trap" },
    { q: "The economy managed to recover ___ the recession within two years.", options: ["from", "of", "by", "with"], answer: 0, explanation: "'Recover from' + setback/illness is the fixed expression.", rule: "Recover from + adversity.", trapcat: "Preposition selection", level: "L2 Application" },
    { q: "Rearrange: A. The fire spread rapidly through the building. B. Firefighters arrived within minutes. C. A short circuit triggered the blaze. D. Everyone was evacuated safely.", options: ["C,A,B,D", "A,C,B,D", "C,B,A,D", "A,B,C,D"], answer: 0, explanation: "Cause (short circuit, C) → effect (fire spreads, A) → response (firefighters arrive, B) → outcome (evacuated safely, D).", rule: "Cause before effect before response before outcome.", trapcat: "Sentence sequencing", level: "L3 Trap" },
    { q: "Rearrange: A. The negotiations broke down. B. Both sides refused to compromise. C. Talks had continued for weeks. D. A strike was declared.", options: ["C,B,A,D", "C,A,B,D", "B,C,A,D", "C,B,D,A"], answer: 0, explanation: "Talks continue (C) → both sides refuse to compromise (B) → negotiations break down (A) → strike declared (D).", rule: "Chronological cause-effect chain.", trapcat: "Sentence sequencing", level: "L3 Trap" },
    { q: "Choose the word nearest in meaning: AUDACIOUS", options: ["Bold", "Timid", "Quiet", "Careful"], answer: 0, explanation: "Audacious = showing bold, daring confidence, often recklessly so.", rule: "Vocabulary — audacious = bold.", trapcat: "Word meaning", level: "L2 Application" },
    { q: "Choose the word OPPOSITE in meaning: VERBOSE", options: ["Concise", "Wordy", "Talkative", "Lengthy"], answer: 0, explanation: "Verbose = using more words than needed; opposite = concise (brief and clear). Wordy/Talkative/Lengthy are all synonyms of verbose, placed as traps.", rule: "Antonym — verbose ≠ concise.", trapcat: "Word meaning - synonym traps", level: "L3 Trap" },
    { q: "One who is unable to read or write:", options: ["Illiterate", "Illegible", "Indolent", "Incoherent"], answer: 0, explanation: "Illiterate = unable to read or write. Illegible = hard to read (of handwriting), Indolent = lazy, Incoherent = not making logical sense.", rule: "One word substitution — illiterate.", trapcat: "Word meaning - close pairs", level: "L3 Trap" },
    { q: "'To add insult to injury' means:", options: ["To make a bad situation even worse", "To apologize sincerely", "To injure someone physically", "To insult someone directly"], answer: 0, explanation: "'Add insult to injury' = to make an already bad situation worse.", rule: "Idiom: add insult to injury.", trapcat: "Idiom interpretation", level: "L2 Application" },
    { q: "'To get cold feet' means:", options: ["To become nervous and back out of a plan", "To feel physically cold", "To become angry suddenly", "To lose interest permanently"], answer: 0, explanation: "'Get cold feet' = to become nervous or hesitant and back out of a commitment at the last moment.", rule: "Idiom: get cold feet.", trapcat: "Idiom interpretation", level: "L2 Application" },
    { q: "Convert to passive voice: The board will announce the results tomorrow.", options: ["The results will be announced by the board tomorrow", "The results are announced by the board tomorrow", "The results were announced by the board tomorrow", "The board will be announced the results tomorrow"], answer: 0, explanation: "Future simple passive: object + will + be + past participle + by subject.", rule: "Active → Passive: future tense → will be + V3.", trapcat: "Voice conversion", level: "L2 Application" },
    { q: "Convert to indirect speech: He said, \"I am feeling unwell today.\"", options: ["He said that he was feeling unwell that day", "He said that he is feeling unwell today", "He said that he was feeling unwell today", "He said he is feeling unwell that day"], answer: 0, explanation: "Present continuous backshifts to past continuous (am feeling → was feeling); 'today' shifts to 'that day' in reported speech.", rule: "Backshift tense + shift time reference (today → that day).", trapcat: "Tense + time-reference backshift", level: "L3 Trap" },
    { q: "Choose the correctly spelt word.", options: ["Questionnaire", "Questionaire", "Questionnairre", "Quiestionnaire"], answer: 0, explanation: "'Questionnaire' is correctly spelt with double N — a commonly misspelt word.", rule: "Spelling: questionnaire has double N.", trapcat: "Spelling", level: "L2 Application" },
    { q: "Select the part with an error: The two twins looked so identical that even their own mother could not tell them apart.", options: ["The two twins looked", "so identical that", "even their own mother", "could not tell them apart"], answer: 0, explanation: "'Twins' already means two — 'two twins' is redundant.", rule: "Redundancy: twins already implies two.", trapcat: "Redundancy", level: "L3 Trap" }
  ]
},
{
  id: "oct1_m2", label: "1 Oct · Evening Full English Mock", timeLimitMin: 20,
  questions: [
    { q: "The list of new employees are posted on the notice board.", options: ["The list of new employees", "are posted", "on the notice board", "No error"], answer: 1, explanation: "'The list' is the true singular subject — should be 'is posted', not 'are posted'.", rule: "R1 — verb follows the real subject, ignore prepositional phrases.", trapcat: "Intervenient phrase", level: "L2 Application" },
    { q: "Either the workers or the supervisor were responsible for the delay.", options: ["Either the workers or the supervisor", "were responsible", "for the delay", "No error"], answer: 1, explanation: "Either/or agrees with the nearer subject. 'Supervisor' (singular) is nearer, so it should be 'was responsible'.", rule: "Either/or → verb agrees with nearer subject.", trapcat: "Either/or - nearer trap", level: "L3 Trap" },
    { q: "One of the students who is always punctual was awarded a prize.", options: ["One of the students who is always punctual", "was awarded a prize", "No error"], answer: 0, explanation: "'One of the students who...' — 'who' refers to 'students' (plural), so it should be 'who are always punctual', not 'is'.", rule: "One of + plural + who → plural verb after who.", trapcat: "One of + who error", level: "L3 Trap" },
    { q: "The number of complaints have decreased significantly this month.", options: ["The number of complaints", "have decreased significantly", "this month", "No error"], answer: 1, explanation: "'The number of' is a singular subject — should be 'has decreased', not 'have decreased'.", rule: "The number of → singular verb (contrast: A number of → plural).", trapcat: "The number of vs a number of", level: "L3 Trap" },
    { q: "Each and every student have submitted their assignment on time.", options: ["Each and every student", "have submitted", "their assignment on time", "No error"], answer: 1, explanation: "'Each and every' is emphatically singular — should be 'has submitted', not 'have submitted'.", rule: "Each and every + noun → singular verb.", trapcat: "Each and every", level: "L2 Application" },
    { q: "Improve: If she would have studied harder, she would have passed the exam.", options: ["If she had studied harder", "If she studied harder", "If she would study harder", "No improvement"], answer: 0, explanation: "Third conditional (past unreal) needs 'if + had + V3', never 'if + would have'.", rule: "Third conditional: If + had + V3, would + have + V3.", trapcat: "Conditional error - would have in if-clause", level: "L3 Trap" },
    { q: "Improve: This is one of the most unique solution to the problem.", options: ["one of the most unique solutions", "one of the unique solution", "the most unique solution", "No improvement"], answer: 0, explanation: "'One of the' always takes a plural noun — should be 'solutions', not 'solution'.", rule: "One of the + plural noun.", trapcat: "One of + singular error", level: "L2 Application" },
    { q: "Improve: The teacher, together with her students, were preparing for the annual function.", options: ["was preparing", "were preparing", "have been preparing", "No improvement"], answer: 0, explanation: "'Together with' does not pluralise the subject — 'the teacher' stays singular, so it should be 'was preparing'.", rule: "Together with does not make subject plural.", trapcat: "Together with trap", level: "L3 Trap" },
    { q: "Improve: Hardly he had reached home when the phone rang.", options: ["Hardly had he reached home", "Hardly he reached home", "Hardly had he reach home", "No improvement"], answer: 0, explanation: "'Hardly' at the start of a sentence requires inversion: 'Hardly had he reached', not 'Hardly he had reached'.", rule: "Hardly + had + subject + V3 (inversion).", trapcat: "Inversion error", level: "L3 Trap" },
    { q: "Improve: The committee members was divided on the new proposal.", options: ["were divided", "was divided", "have been divide", "No improvement"], answer: 0, explanation: "'Committee members' (plural, referring to individuals) takes a plural verb: 'were divided', not 'was divided'.", rule: "Collective noun members acting individually → plural verb.", trapcat: "Collective noun - individual action", level: "L2 Application" },
    { q: "The witness was reluctant ___ reveal the identity of the culprit.", options: ["to", "for", "in", "of"], answer: 0, explanation: "'Reluctant to' + infinitive is the fixed pattern.", rule: "Reluctant to + verb.", trapcat: "Preposition selection", level: "L2 Application" },
    { q: "The new policy is aimed ___ reducing traffic congestion in the city.", options: ["at", "to", "for", "on"], answer: 0, explanation: "'Aimed at' + gerund is the fixed pattern.", rule: "Aimed at + gerund.", trapcat: "Preposition selection", level: "L2 Application" },
    { q: "He is adept ___ handling difficult clients with patience.", options: ["at", "in", "with", "to"], answer: 0, explanation: "'Adept at' is the fixed expression meaning skilled at something.", rule: "Adept at + gerund/noun.", trapcat: "Preposition - less common", level: "L3 Trap" },
    { q: "The organization is committed ___ improving employee welfare.", options: ["to", "for", "in", "with"], answer: 0, explanation: "'Committed to' + gerund is the fixed pattern.", rule: "Committed to + gerund.", trapcat: "Preposition selection", level: "L2 Application" },
    { q: "Rearrange: A. Sales dropped sharply the following quarter. B. The company launched a new product. C. Customer complaints about quality rose. D. The design proved to be flawed.", options: ["B,D,C,A", "B,C,D,A", "D,B,C,A", "B,D,A,C"], answer: 0, explanation: "Company launches product (B) → design proves flawed (D) → complaints rise (C) → sales drop (A).", rule: "Launch → flaw discovered → complaints → consequence.", trapcat: "Sentence sequencing", level: "L3 Trap" },
    { q: "Rearrange: A. The plant wilted within days. B. She forgot to water it regularly. C. She bought a new plant for her balcony. D. She felt guilty about neglecting it.", options: ["C,B,A,D", "C,A,B,D", "B,C,A,D", "C,B,D,A"], answer: 0, explanation: "Buys plant (C) → forgets to water (B) → plant wilts (A) → feels guilty (D).", rule: "Action → neglect → consequence → emotional reaction.", trapcat: "Sentence sequencing", level: "L3 Trap" },
    { q: "Choose the word nearest in meaning: PRUDENT", options: ["Wise", "Reckless", "Careless", "Foolish"], answer: 0, explanation: "Prudent = showing care and good judgment, especially about practical matters; closest to 'wise'.", rule: "Vocabulary — prudent = wise.", trapcat: "Word meaning", level: "L2 Application" },
    { q: "Choose the word OPPOSITE in meaning: AMIABLE", options: ["Hostile", "Friendly", "Pleasant", "Cordial"], answer: 0, explanation: "Amiable = friendly and pleasant; opposite = hostile. Friendly/Pleasant/Cordial are synonyms, placed as traps.", rule: "Antonym — amiable ≠ hostile.", trapcat: "Word meaning - synonym traps", level: "L3 Trap" },
    { q: "One who loves and collects books:", options: ["Bibliophile", "Bibliography", "Biography", "Bibliophobe"], answer: 0, explanation: "Bibliophile = a lover/collector of books. Bibliophobe (opposite, fear of books), Bibliography (list of sources), Biography (life story) are all close-sounding traps.", rule: "One word substitution — bibliophile.", trapcat: "Word meaning - close pairs", level: "L3 Trap" },
    { q: "'To turn a blind eye' means:", options: ["To deliberately ignore something wrong", "To become blind suddenly", "To look away in fear", "To refuse to help someone"], answer: 0, explanation: "'Turn a blind eye' = to deliberately ignore or pretend not to notice something wrong.", rule: "Idiom: turn a blind eye = deliberately ignore.", trapcat: "Idiom interpretation", level: "L2 Application" },
    { q: "'To be in the same boat' means:", options: ["To be in the same difficult situation as others", "To travel together", "To agree completely", "To compete against each other"], answer: 0, explanation: "'In the same boat' = facing the same difficult situation or circumstances as someone else.", rule: "Idiom: in the same boat = shared situation.", trapcat: "Idiom interpretation", level: "L2 Application" },
    { q: "Convert to passive voice: They have completed the survey successfully.", options: ["The survey has been completed successfully by them", "The survey was completed successfully by them", "The survey is completed successfully by them", "The survey has completed successfully"], answer: 0, explanation: "Present perfect passive: has/have + been + past participle.", rule: "Active → Passive: present perfect → has been + V3.", trapcat: "Voice conversion", level: "L2 Application" },
    { q: "Convert to indirect speech: The manager said, \"I will review your proposal tomorrow.\"", options: ["The manager said that he would review my proposal the next day", "The manager said that he will review my proposal tomorrow", "The manager said he would review my proposal tomorrow", "The manager said that he would review my proposal today"], answer: 0, explanation: "Will backshifts to would; 'tomorrow' shifts to 'the next day' in reported speech.", rule: "Backshift modal (will→would) + time reference (tomorrow→the next day).", trapcat: "Modal + time-reference backshift", level: "L3 Trap" },
    { q: "Choose the correctly spelt word.", options: ["Maintenance", "Maintainance", "Maintenence", "Maintaenance"], answer: 0, explanation: "'Maintenance' is correctly spelt — note it drops the second 'ai' pattern from 'maintain', a common source of error.", rule: "Spelling: maintenance (not maintainance).", trapcat: "Spelling", level: "L2 Application" },
    { q: "Select the part with an error: He returned back to his hometown after completing his studies abroad.", options: ["He returned back", "to his hometown", "after completing his studies", "abroad"], answer: 0, explanation: "'Return' already means 'come back' — 'returned back' is redundant.", rule: "Redundancy: return already means come back.", trapcat: "Redundancy", level: "L2 Application" }
  ]
},
{
  id: "oct1_m3", label: "1 Oct · Maths Mock", timeLimitMin: 25,
  questions: [
    { q: "35% of 320 + 25% of 200 = ?", options: ["162", "150", "170", "155"], answer: 0, explanation: "35% of 320 = 112; 25% of 200 = 50; 112+50 = 162.", rule: "Percentage of number: (percentage/100) × number.", trapcat: "Calculation", level: "L1 Direct" },
    { q: "If 40% of a number is 68, the number is:", options: ["170", "160", "180", "150"], answer: 0, explanation: "Number × 40/100 = 68 → Number = 68 × 100/40 = 170.", rule: "Reverse percentage: number = value × 100/%.", trapcat: "Reverse calculation", level: "L1 Direct" },
    { q: "A number increased by 20% gives 372. The original number is:", options: ["310", "300", "320", "295"], answer: 0, explanation: "Original × 1.20 = 372 → Original = 372/1.20 = 310.", rule: "Percentage increase reverse calculation.", trapcat: "Percentage increase", level: "L2 Application" },
    { q: "If a:b = 5:6 and b:c = 4:7, then a:c = ?", options: ["10:21", "5:7", "20:42", "9:13"], answer: 0, explanation: "a:c = (5×4):(6×7) = 20:42 = 10:21 in simplest form.", rule: "Chain ratio, then simplify.", trapcat: "Ratio chain - simplification", level: "L3 Trap" },
    { q: "The average of 12 numbers is 30. If each number is increased by 3, the new average is:", options: ["33", "30", "36", "27"], answer: 0, explanation: "If each number increases by 3, the average also increases by 3 → 30+3 = 33.", rule: "Average adjustment: new avg = old avg ± change.", trapcat: "Average property", level: "L1 Direct" },
    { q: "The average weight of 10 persons increases by 2 kg when a new person replaces one of them weighing 55 kg. What is the weight of the new person?", options: ["75 kg", "70 kg", "65 kg", "80 kg"], answer: 0, explanation: "Total increase = 10 × 2 = 20 kg. New person's weight = 55+20 = 75 kg.", rule: "Total increase = count × avg change; add to replaced person's weight.", trapcat: "Average with replacement", level: "L2 Application" },
    { q: "An article is sold for Rs.720 at a loss of 10%. What is the cost price?", options: ["Rs.800", "Rs.750", "Rs.780", "Rs.820"], answer: 0, explanation: "CP = SP/(1-loss%) = 720/0.90 = Rs.800.", rule: "CP = SP / (1 - loss%).", trapcat: "Profit-loss calculation", level: "L2 Application" },
    { q: "A trader marks his goods 40% above cost price and allows a 20% discount. His gain percent is:", options: ["12%", "10%", "15%", "20%"], answer: 0, explanation: "CP=100, MP=140, SP=140×0.8=112, Gain=12%.", rule: "Marked price + discount chain.", trapcat: "Profit-loss with discount", level: "L2 Application" },
    { q: "Marked price of an item is Rs.600, discount offered is 10%. Selling price is:", options: ["Rs.540", "Rs.560", "Rs.520", "Rs.550"], answer: 0, explanation: "SP = MP × (1-discount%) = 600×0.90 = Rs.540.", rule: "SP = MP × (1 - discount%).", trapcat: "Discount calculation", level: "L1 Direct" },
    { q: "The simple interest on Rs.2000 for 4 years at 6% per annum is:", options: ["Rs.480", "Rs.450", "Rs.500", "Rs.460"], answer: 0, explanation: "SI = P×R×T/100 = 2000×6×4/100 = Rs.480.", rule: "Simple interest formula.", trapcat: "SI calculation", level: "L1 Direct" },
    { q: "The compound interest on Rs.2000 at 10% per annum for 2 years, compounded annually, is:", options: ["Rs.420", "Rs.400", "Rs.440", "Rs.410"], answer: 0, explanation: "CI = 2000×(1.10)^2 - 2000 = 2420-2000 = Rs.420.", rule: "Compound interest formula.", trapcat: "CI calculation", level: "L2 Application" },
    { q: "In what ratio must tea worth Rs.20/kg be mixed with tea worth Rs.25/kg to get a mixture worth Rs.22/kg?", options: ["3:2", "2:3", "1:2", "3:1"], answer: 0, explanation: "By alligation: (25-22):(22-20) = 3:2 (dearer:cheaper).", rule: "Alligation: (d-c):(m-c) inverted for ratio of cheaper:dearer amounts — here (d-m):(m-c) = 3:2.", trapcat: "Alligation", level: "L2 Application" },
    { q: "A and B invest in a business in the ratio 2:3. If the total profit is Rs.1200, find B's share.", options: ["Rs.720", "Rs.480", "Rs.600", "Rs.700"], answer: 0, explanation: "Total parts = 5. B's share = (3/5)×1200 = Rs.720.", rule: "Partnership: share = (ratio part/total parts) × profit.", trapcat: "Partnership", level: "L1 Direct" },
    { q: "The ratio of ages of two brothers is 2:3, and their sum is 50. Find the older brother's age after 5 years.", options: ["35", "30", "33", "28"], answer: 0, explanation: "Older brother's share = (3/5)×50 = 30. After 5 years = 30+5 = 35.", rule: "Age ratio with sum, then add years.", trapcat: "Age calculation", level: "L1 Direct" },
    { q: "A can do a piece of work in 12 days, B in 20 days. Working together, they will complete the work in:", options: ["7.5 days", "8 days", "9 days", "10 days"], answer: 0, explanation: "Combined rate = 1/12+1/20 = 5/60+3/60=8/60=2/15. Time = 15/2 = 7.5 days.", rule: "Work together: 1/A + 1/B = 1/Combined time.", trapcat: "Time and work", level: "L2 Application" },
    { q: "A and B together can complete a work in 12 days. A alone can do it in 20 days. B alone can do it in:", options: ["30 days", "25 days", "28 days", "24 days"], answer: 0, explanation: "Together rate=1/12; A alone=1/20; B alone=1/12-1/20=5/60-3/60=2/60=1/30 → 30 days.", rule: "Work efficiency: combined - one = other.", trapcat: "Time and work", level: "L2 Application" },
    { q: "Pipe A can fill a tank in 5 hours and Pipe B in 20 hours. If both are opened together, the tank fills in:", options: ["4 hours", "3.5 hours", "4.5 hours", "5 hours"], answer: 0, explanation: "Combined rate=1/5+1/20=4/20+1/20=5/20=1/4 → 4 hours.", rule: "Pipes together: 1/A + 1/B = 1/Time.", trapcat: "Pipes and cisterns", level: "L1 Direct" },
    { q: "A train running at 54 km/h crosses a pole in 10 seconds. Find the length of the train.", options: ["150 m", "140 m", "160 m", "145 m"], answer: 0, explanation: "Speed = 54×5/18=15 m/s. Length = speed×time = 15×10 = 150 m.", rule: "Crossing a pole = covering the train's own length.", trapcat: "Train problems", level: "L2 Application" },
    { q: "A car travels a distance at 40 km/h and returns the same distance at 60 km/h. Find its average speed for the entire journey.", options: ["48 km/h", "50 km/h", "45 km/h", "52 km/h"], answer: 0, explanation: "Average speed = 2xy/(x+y) = 2×40×60/100 = 48 km/h (harmonic mean, not arithmetic mean).", rule: "Equal distances → harmonic mean 2xy/(x+y).", trapcat: "Average speed trap", level: "L2 Application" },
    { q: "A boat's upstream speed is 6 km/h and downstream speed is 8 km/h. Find the speed of the stream.", options: ["1 km/h", "2 km/h", "1.5 km/h", "0.5 km/h"], answer: 0, explanation: "Stream speed = (Downstream - Upstream)/2 = (8-6)/2 = 1 km/h.", rule: "Stream speed = (Downstream-Upstream)/2.", trapcat: "Boats and streams", level: "L1 Direct" },
    { q: "The HCF of two numbers is 12 and their LCM is 240. If one number is 48, find the other.", options: ["60", "50", "54", "56"], answer: 0, explanation: "Product = HCF×LCM = 12×240=2880. Other number = 2880/48 = 60.", rule: "Number1 × Number2 = HCF × LCM.", trapcat: "HCF-LCM", level: "L2 Application" },
    { q: "Find the largest 4-digit number exactly divisible by 12.", options: ["9996", "9988", "9992", "9984"], answer: 0, explanation: "9999/12 = 833 remainder 3, so 9999-3 = 9996.", rule: "Subtract (N mod divisor) from N.", trapcat: "Divisibility", level: "L1 Direct" },
    { q: "The angles of a triangle are in the ratio 2:3:4. Find the largest angle.", options: ["80 degrees", "90 degrees", "75 degrees", "85 degrees"], answer: 0, explanation: "Total parts=9. Largest = (4/9)×180 = 80 degrees.", rule: "Triangle angle sum = 180; divide by total parts.", trapcat: "Geometry", level: "L1 Direct" },
    { q: "The area of a circle is 154 sq cm. Find its radius. (Use pi = 22/7)", options: ["7 cm", "6 cm", "8 cm", "7.5 cm"], answer: 0, explanation: "Area = pi×r^2 → 154 = (22/7)×r^2 → r^2 = 154×7/22 = 49 → r = 7 cm.", rule: "Reverse area formula: r = sqrt(Area × 7/22).", trapcat: "Mensuration - reverse", level: "L2 Application" },
    { q: "Simplify: (5/6 + 1/3) divided by (1/2 - 1/6)", options: ["3.5", "3", "4", "2.5"], answer: 0, explanation: "Numerator: 5/6+1/3=5/6+2/6=7/6. Denominator: 1/2-1/6=3/6-1/6=2/6=1/3. Result=(7/6)/(1/3)=(7/6)×3=7/2=3.5.", rule: "Convert to single fractions, then divide by multiplying by reciprocal.", trapcat: "Simplification", level: "L2 Application" }
  ]
},
{
  id: "oct1_m4", label: "1 Oct · GS Mock", timeLimitMin: 30,
  questions: [
    { q: "Which Article of the Indian Constitution abolishes untouchability?", options: ["Article 17", "Article 15", "Article 21", "Article 23"], answer: 0, explanation: "Article 17 abolishes untouchability and forbids its practice in any form.", rule: "Article 17 — abolition of untouchability.", trapcat: "Fundamental Rights", level: "L2 Application" },
    { q: "The 'Doctrine of Basic Structure' of the Indian Constitution was propounded in which case?", options: ["Kesavananda Bharati case (1973)", "Golaknath case (1967)", "Minerva Mills case (1980)", "Maneka Gandhi case (1978)"], answer: 0, explanation: "The Kesavananda Bharati case (1973) established that Parliament cannot amend the 'basic structure' of the Constitution.", rule: "Kesavananda Bharati — Basic Structure Doctrine.", trapcat: "Landmark cases", level: "L3 Trap" },
    { q: "Who was the first Speaker of the Lok Sabha?", options: ["G.V. Mavalankar", "Sardar Hukam Singh", "N. Sanjiva Reddy", "K.S. Hegde"], answer: 0, explanation: "G.V. Mavalankar was the first Speaker of the Lok Sabha, serving from 1952.", rule: "First Lok Sabha Speaker — G.V. Mavalankar.", trapcat: "Constitutional history", level: "L2 Application" },
    { q: "The Battle of Plassey (1757), which laid the foundation of British rule in India, was fought between the British and:", options: ["Siraj-ud-Daulah, Nawab of Bengal", "Tipu Sultan", "Mir Qasim", "Shuja-ud-Daulah"], answer: 0, explanation: "The Battle of Plassey (1757) was fought between the British East India Company and Siraj-ud-Daulah, the last independent Nawab of Bengal.", rule: "Battle of Plassey — Siraj-ud-Daulah.", trapcat: "British colonial history", level: "L2 Application" },
    { q: "Which Mughal emperor is associated with the 'Din-i-Ilahi', a syncretic religious movement?", options: ["Akbar", "Jahangir", "Shah Jahan", "Aurangzeb"], answer: 0, explanation: "Akbar founded Din-i-Ilahi in 1582, blending elements of various religions.", rule: "Din-i-Ilahi — founded by Akbar.", trapcat: "Mughal history", level: "L2 Application" },
    { q: "The Tropic of Cancer passes through how many Indian states?", options: ["8", "7", "9", "6"], answer: 0, explanation: "The Tropic of Cancer passes through 8 Indian states: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura, and Mizoram.", rule: "Tropic of Cancer — 8 Indian states.", trapcat: "Physical geography", level: "L3 Trap" },
    { q: "Which is the largest freshwater lake in India?", options: ["Wular Lake (Jammu & Kashmir)", "Chilika Lake (Odisha)", "Dal Lake (Jammu & Kashmir)", "Sambhar Lake (Rajasthan)"], answer: 0, explanation: "Wular Lake in Jammu & Kashmir is the largest freshwater lake in India. Chilika is the largest BRACKISH-water lagoon, a commonly confused distinction.", rule: "Wular = largest freshwater; Chilika = largest brackish-water lagoon.", trapcat: "Freshwater vs brackish lake trap", level: "L3 Trap" },
    { q: "Which state has the highest installed solar power capacity in India (among traditionally leading states)?", options: ["Rajasthan", "Gujarat", "Karnataka", "Tamil Nadu"], answer: 0, explanation: "Rajasthan, with its vast arid land and high solar insolation, has consistently led India in installed solar power capacity.", rule: "Rajasthan — leading solar power capacity.", trapcat: "Renewable energy geography", level: "L2 Application" },
    { q: "The Reserve Bank of India's monetary policy committee (MPC) has how many members?", options: ["6", "5", "7", "4"], answer: 0, explanation: "The Monetary Policy Committee (MPC) has 6 members — 3 from RBI and 3 external members appointed by the government.", rule: "MPC — 6 members (3 RBI + 3 external).", trapcat: "Monetary policy structure", level: "L3 Trap" },
    { q: "'Disinvestment' in the context of the Indian economy refers to:", options: ["The sale of government equity/stake in public sector enterprises", "The government investing more money into public enterprises", "Foreign companies withdrawing investment from India", "Reduction in overall government expenditure"], answer: 0, explanation: "Disinvestment means the government selling or liquidating its equity stake in public sector undertakings (PSUs).", rule: "Disinvestment — government selling PSU stake.", trapcat: "Economic terminology", level: "L2 Application" },
    { q: "Which vitamin deficiency causes the disease 'Rickets' in children?", options: ["Vitamin D", "Vitamin A", "Vitamin C", "Vitamin B12"], answer: 0, explanation: "Vitamin D deficiency causes Rickets (soft, weak bones) in children.", rule: "Vitamin D deficiency — Rickets.", trapcat: "Nutritional deficiency diseases", level: "L2 Application" },
    { q: "Which gas is most responsible for the depletion of the ozone layer?", options: ["Chlorofluorocarbons (CFCs)", "Carbon dioxide", "Methane", "Sulphur dioxide"], answer: 0, explanation: "Chlorofluorocarbons (CFCs), once widely used in refrigerants and aerosols, are the primary cause of ozone layer depletion.", rule: "CFCs — primary ozone depletion cause.", trapcat: "Environmental chemistry", level: "L2 Application" },
    { q: "The process by which plants lose water in the form of vapour through their leaves is called:", options: ["Transpiration", "Respiration", "Photosynthesis", "Osmosis"], answer: 0, explanation: "Transpiration is the loss of water vapour from plant leaves through stomata.", rule: "Transpiration — water loss from leaves.", trapcat: "Plant physiology", level: "L1 Direct" },
    { q: "Who is credited with founding the Indian National Congress in 1885?", options: ["A.O. Hume", "Dadabhai Naoroji", "W.C. Bonnerjee", "Surendranath Banerjee"], answer: 0, explanation: "A.O. Hume, a retired British civil servant, is credited with founding the Indian National Congress in 1885. W.C. Bonnerjee was its first President, a commonly confused distinction.", rule: "A.O. Hume founded INC; W.C. Bonnerjee was its first President.", trapcat: "Founder vs first president trap", level: "L3 Trap" },
    { q: "The 'Poona Pact' (1932) was signed between Mahatma Gandhi and:", options: ["B.R. Ambedkar", "Muhammad Ali Jinnah", "Subhas Chandra Bose", "Madan Mohan Malaviya"], answer: 0, explanation: "The Poona Pact (1932) was signed between Gandhi and Ambedkar, replacing separate electorates for the Depressed Classes with reserved seats in a joint electorate.", rule: "Poona Pact — Gandhi and Ambedkar.", trapcat: "Freedom movement agreements", level: "L2 Application" },
    { q: "Which Indian state is the largest producer of coffee?", options: ["Karnataka", "Kerala", "Tamil Nadu", "Andhra Pradesh"], answer: 0, explanation: "Karnataka (particularly the Kodagu/Coorg region) is India's largest coffee-producing state.", rule: "Karnataka — largest coffee producer.", trapcat: "Agricultural geography", level: "L2 Application" },
    { q: "The 'Sangam' literature belongs to which period and region?", options: ["Ancient Tamil Nadu (roughly 300 BCE - 300 CE)", "Medieval Bengal", "Ancient Gujarat", "Medieval Karnataka"], answer: 0, explanation: "Sangam literature is a body of ancient Tamil poetic works composed roughly between 300 BCE and 300 CE.", rule: "Sangam literature — ancient Tamil Nadu.", trapcat: "Ancient literature", level: "L2 Application" },
    { q: "Which of the following is NOT one of the three organs of the State as per the doctrine of Separation of Powers?", options: ["Bureaucracy", "Legislature", "Executive", "Judiciary"], answer: 0, explanation: "The classical Separation of Powers doctrine identifies three organs: Legislature, Executive, and Judiciary. Bureaucracy is part of the Executive machinery, not a separate fourth organ.", rule: "Three organs: Legislature, Executive, Judiciary (Bureaucracy is part of Executive).", trapcat: "Political theory", level: "L2 Application" },
    { q: "The 'Simon Commission' (1928), which visited India to review constitutional reforms, was boycotted primarily because:", options: ["It did not include any Indian members", "It proposed to abolish provincial autonomy", "It recommended separate electorates for all communities", "It was formed without British parliamentary approval"], answer: 0, explanation: "The Simon Commission was boycotted with 'Simon Go Back' protests because it had no Indian members despite reviewing India's constitutional future.", rule: "Simon Commission boycotted — all-British composition, no Indians.", trapcat: "Freedom movement protests", level: "L2 Application" },
    { q: "Which layer of the atmosphere contains the ozone layer that protects Earth from harmful UV radiation?", options: ["Stratosphere", "Troposphere", "Mesosphere", "Thermosphere"], answer: 0, explanation: "The ozone layer is located in the stratosphere, roughly 15-35 km above Earth's surface.", rule: "Ozone layer — located in the stratosphere.", trapcat: "Atmospheric layers", level: "L2 Application" },
    { q: "The 'Gini Coefficient' is a statistical measure used to represent:", options: ["Income or wealth inequality within a nation", "Rate of inflation", "Gross Domestic Product growth rate", "Literacy rate"], answer: 0, explanation: "The Gini Coefficient measures income or wealth inequality within a population, ranging from 0 (perfect equality) to 1 (perfect inequality).", rule: "Gini Coefficient — measure of inequality.", trapcat: "Economic indicators", level: "L2 Application" },
    { q: "Which Indian classical dance form originated in Tamil Nadu and is traditionally associated with temple worship?", options: ["Bharatanatyam", "Kathak", "Odissi", "Manipuri"], answer: 0, explanation: "Bharatanatyam originated in Tamil Nadu temples, traditionally performed by devadasis as a form of worship.", rule: "Bharatanatyam — Tamil Nadu classical dance.", trapcat: "Classical dance forms", level: "L2 Application" },
    { q: "Which committee recommended the establishment of NITI Aayog to replace the Planning Commission?", options: ["No committee — it was a direct Cabinet decision in 2015", "Ashok Chawla Committee", "Bibek Debroy Committee (post-facto review only)", "C. Rangarajan Committee"], answer: 0, explanation: "NITI Aayog was established via a direct Union Cabinet resolution on 1 January 2015, not through a formal recommending committee — a fact that itself is often tested as a trap since most institutional changes DO follow committee recommendations.", rule: "NITI Aayog — direct Cabinet decision, not committee-recommended.", trapcat: "Institutional history - direct decision trap", level: "L3 Trap" },
    { q: "The 'Namami Gange' programme is primarily aimed at:", options: ["Conservation and rejuvenation of the Ganga river", "Afforestation along the Himalayan foothills", "Rural electrification in the Gangetic plains", "Flood control in the Brahmaputra basin"], answer: 0, explanation: "Namami Gange is a flagship programme for the conservation and rejuvenation of the National River Ganga, covering pollution abatement and river-front development.", rule: "Namami Gange — Ganga conservation programme.", trapcat: "Government schemes", level: "L1 Direct" },
    { q: "Which blood vessel carries oxygenated blood from the lungs back to the heart?", options: ["Pulmonary vein", "Pulmonary artery", "Aorta", "Vena cava"], answer: 0, explanation: "The pulmonary vein carries oxygenated blood from the lungs to the heart's left atrium — the one vein in the body that carries oxygen-rich blood (veins usually carry deoxygenated blood).", rule: "Pulmonary vein — the exception that carries oxygenated blood.", trapcat: "Circulatory system - vein/artery exception", level: "L3 Trap" }
  ]
}
];
