/* LESSONS-B — voice, vocabulary, exam skills. Same step schema as lessons-a. */
const LESSONS_B = {
eng_voice: { title: "Active ↔ Passive Voice", sub: "Same tense. Swap sides. Add be + V3.",
hook: "Voice is a swap-machine, not English literature. Object and subject exchange chairs; the verb puts on a be + V3 uniform. The tense NEVER changes — and that single fact kills two options in most questions.",
paperNote: "Paper proof (2024): FIVE voice Qs across shifts — and they ran BOTH directions, including negatives ('Sonam does not like bananas' → are not liked, 9 Sept S1). Tense-match alone solves most. 2–3 marks, nearly free.",
steps: [
{ k: "coach", h: "The swap in 10 seconds", html: "Active: <i>She (who) + writes (does) + a letter (what)</i>. Passive: the WHAT becomes the subject — <i>A letter <b>is written</b> by her.</i> Steps: <b>1.</b> new subject = old object, <b>2.</b> verb = same-tense be + V3, <b>3.</b> old subject goes to by-phrase." },
{ k: "table", h: "The only table you need", html: "<table class='lt'><tr><th>Active</th><th>Passive</th></tr><tr><td>writes</td><td>is written</td></tr><tr><td>wrote</td><td>was written</td></tr><tr><td>is writing</td><td>is <b>being</b> written</td></tr><tr><td>has written</td><td>has <b>been</b> written</td></tr><tr><td>will write / can write</td><td>will/can <b>be</b> written</td></tr></table>" },
{ k: "try", h: "Try it — real paper (negative!)", q: { q: "Passive: Sonam does not like bananas.", options: ["Banana is not liked by Sonam.", "Bananas have not been liked by Sonam.", "Bananas are not liked by Sonam.", "Bananas had not been liked by Sonam."], answer: 2, explanation: "Negative present → are + not + V3; bananas stays plural. Asked 9 Sept 2024.", rule: "Negatives keep tense.", elim: "Present → are; plural kills A.", trap: "Singular-banana + tense-shift traps.", trapcat: "Negatives", level: "L1" } },
{ k: "trap", h: "Trap autopsy: the missing be", html: "'The results will announced.' Sounds fast, scores zero — future passive NEEDS 'be': <i>will <b>be</b> announced</i>. Whenever continuous/perfect/modal/future appears, hunt for being/been/be FIRST — its absence is the error." },
{ k: "pick", h: "Beat the examiner", stem: "'People know Stellenbosch for its greenery.' Three options shift the tense (was/have/had been known). Why does the examiner print three tense-traps and one correct answer?", options: ["To test vocabulary", "Because tense-shift is the #1 error students make", "To fill option space"], answer: 1, why: "Correct: 'is known'. The examiner knows students convert voice AND tense together. Rule drilled: convert voice, FREEZE tense. Tense-match first, everything else second." },
{ k: "card", h: "Master card", html: "<b>Core:</b> tense frozen; swap + be + V3. <b>2-min:</b> continuous→being • perfect→been • modal/future→be • who→by whom." },
],
revision: { min2: "Freeze tense. being/been/be per table.", lastmin: "Match tense, find being/been/be." } },

eng_narration: { title: "Direct → Indirect Speech", sub: "Backshift, connector, pointer. Three moves.",
hook: "Narration is also a machine with three levers: push the tense back, pick the right connector, shift the pointers. And the 2024 paper proved narration hides OUTSIDE narration questions too.",
paperNote: "Paper proof: 'Do you know WHERE DOES SHE RESIDE?' → where she resides (18 Sept S3). That is reported-question grammar tested as sentence improvement. Learn narration = free improvement marks. 2–3 marks per paper.",
steps: [
{ k: "coach", h: "The three levers", html: "<b>1. Backshift</b> (said + past): is→was, will→would, past→had + V3. <b>2. Connector:</b> statement→that, yes/no→if, wh→the wh-word, order→to. <b>3. Pointers:</b> today→that day, tomorrow→next day, here→there. Says (present) → NO shift." },
{ k: "rule", h: "Questions lose their shape", html: "Reported questions are NOT questions: no inversion, no question mark logic. <i>'Are you coming?' → he asked <b>if I was coming</b>.</i> <i>'Where do you live?' → she asked <b>where I lived</b>.</i> Inversion left behind = error." },
{ k: "try", h: "Try it — real paper grammar", q: { q: "Improve: Do you know where does she reside?", options: ["where she resides?", "where do she reside?", "where she reside?", "where does she resides?"], answer: 0, explanation: "Statement order + agreement: she resides. Asked 18 Sept 2024.", rule: "Reported wh: no inversion.", elim: "Kill inverted options; kill resides mismatch.", trap: "Direct-order trap.", trapcat: "Reported questions", level: "L1" } },
{ k: "trap", h: "Trap autopsy: auto-backshift", html: "'He SAYS he was tired.' Says (present) → NO backshift allowed: <i>He says he IS tired.</i> The examiner counts on your backshift reflex firing blindly. First look at the REPORTING verb, then decide." },
{ k: "card", h: "Master card", html: "<b>Core:</b> said+past→shift; says→freeze. <b>2-min:</b> that/if-wh/to • no inversion • tomorrow→next day." },
],
revision: { min2: "Said→shift, says→freeze. Connector first.", lastmin: "Connector? Inversion out? Pointers?" } },

eng_vocab: { title: "Synonyms + Antonyms", sub: "SSC tests words INSIDE sentences. Train that way.",
hook: "Forget word-list murders. In 2024, synonyms came as bold words inside sentences, bracketed words for blanks, underlined words in context. The examiner tests whether you feel the word's charge — positive or negative — not whether you memorised a dictionary.",
paperNote: "Paper proof: judicious→prudent, decency→courtesy, immense→huge, brittle→fragile (all in-sentence, Sept 2024). And the killer: munificent — most marked 'miserly', key says 'magnanimous' (26 Sept). Charge-checking would have saved that mark.",
steps: [
{ k: "coach", h: "Charge first, meaning second", html: "Read the sentence, feel positive or negative, kill the two opposite-charge options. Then pick by fit. Charge alone clears half the options in most 2024 sets — including munificent (giving = positive; miserly dies instantly)." },
{ k: "rule", h: "The 4 real formats", html: "<b>1.</b> Bold word in sentence → synonym. <b>2.</b> Bracketed word → fill blank with synonym. <b>3.</b> Underlined word → antonym from sentence. <b>4.</b> Contrast blank (but/yet) → antonym. Practise all four — the paper mixes them." },
{ k: "table", h: "2024's own wordlist (learn THESE first)", html: "judicious–prudent • decency–courtesy • immense–huge • brittle–fragile • cherish–nurture • adequate–sufficient • munificent–magnanimous • unsure–certain • hot–frigid • envious–generous • grudge–benevolence • barbarity–compassion • active–inert • large–tiny. Fourteen words, seven real marks." },
{ k: "try", h: "Try it — the 2024 killer", q: { q: "Synonym of: Munificent.", options: ["Miserly", "Malicious", "Underappreciated", "Magnanimous"], answer: 3, explanation: "Very generous → magnanimous. Most 2024 candidates marked miserly.", rule: "Generosity sense.", elim: "Giving-positive → kill miserly/malicious.", trap: "Miserly opposite-root trap.", trapcat: "Synonyms", level: "L1" } },
{ k: "pick", h: "Beat the examiner", stem: "Antonym of 'unsure': options Certain / Doubtful / Thoughtful / Interested. Which is the designed trap?", options: ["Doubtful — feels antonym-ish", "Certain — too obvious", "Interested — random"], answer: 0, why: "'Doubtful' is a SYNONYM wearing an antonym's clothes — the examiner's favourite disguise. For antonyms, first strike the word that means nearly the SAME. (Real 2024 Q, 25 Sept S3.)" },
{ k: "card", h: "Master card", html: "<b>Core:</b> charge → POS → intensity. <b>2-min:</b> kill opposite charge; strike same-meaning options in antonyms; learn the 2024 list above." },
],
revision: { min2: "Charge first. Antonym: strike synonyms first.", lastmin: "Feel +/−, kill 2, pick fit." } },

eng_ows: { title: "One-Word Substitution + Spelling", sub: "Hooks for OWS. Three formats for spelling.",
hook: "OWS is a hook-matching game: fear→phobia, killing→cide, all→omni. And spelling is NOT one question type — 2024 used THREE formats. Students who practised only 'find the misspelt word' dropped the other two marks.",
paperNote: "Paper proof: alliteration for repeated sounds, affidavit for sworn statement, blasphemy, omnipotent (all 2024). Spelling: find-misspelt (Exhilerate, Preceed), rectify-in-sentence (acknowlege), fill-blank (colloquial). All three formats inside — practise all three below.",
steps: [
{ k: "coach", h: "OWS hooks", html: "fear→<b>-phobia</b> • killing→<b>-cide</b> • lover→<b>-phile</b> • all→<b>omni-</b> • cannot→<b>in-/il-/im-</b> • government→<b>-cracy</b> • sound→<b>audi-</b> • oath→<b>affi-</b>. Warning: SSC asks LITERARY terms too (alliteration, 2024) — not just people-words." },
{ k: "rule", h: "Spelling: the 3 formats", html: "<b>1. Find misspelt</b> (4 words, pick the wrong one). <b>2. Rectify in sentence</b> (correct the underlined wrong spelling). <b>3. Fill blank</b> with correct spelling. Same word-lists, three doors — walk through each in Practice." },
{ k: "table", h: "2024's own spelling list", html: "exhilarate • precede (but exceed/proceed/succeed) • acknowledge • moment • colloquial • removal • attributes • prevailed • atrocious • embarrass • occurrence • accommodate. Twelve words, six real marks." },
{ k: "try", h: "Try it — real paper", q: { q: "Substitute: The line uses repetition of initial consonant sounds in neighbouring words.", options: ["alliteration", "epithet", "allegory", "simile"], answer: 0, explanation: "Repeated initial sounds → alliteration. Asked 25 Sept 2024.", rule: "Hook: repeated sounds.", elim: "Sound-repetition → alliteration.", trap: "Literary-term cluster.", trapcat: "OWS", level: "L1" } },
{ k: "trap", h: "Trap autopsy: the -ceed family", html: "Exceed, proceed, succeed — but PRECEDE. The examiner lines up the whole -ceed family and swaps one vowel. Rule: pre + CEDE (go before). Spot the odd family member." },
{ k: "card", h: "Master card", html: "<b>Core:</b> hooks match; 3 spelling doors. <b>2-min:</b> -phobia/-cide/omni • precede≠-ceed • acknowledge/moment/colloquial." },
],
revision: { min2: "Hooks: fear/kill/all/oath. Precede. Acknowledge.", lastmin: "Hook? Which door? Odd one out?" } },

eng_idioms: { title: "Idioms & Phrases", sub: "Used in sentences — learn them in sentences.",
hook: "SSC stopped asking 'what does X mean' in isolation. Idioms now arrive inside sentences, and the sentence's mood points at the answer. Learn each idiom as a mini-story, then test it inside a sentence.",
paperNote: "Paper proof (2024): cards-close-to-chest, fish-out-of-water, hit-the-roof, creature-of-habit, bad-patch, off-and-on — ALL inside sentences. Six idioms, six sentence-contexts. Story + context = full marks.",
steps: [
{ k: "coach", h: "Story, then sentence", html: "Fish out of water = a misfit gasping → uncomfortable somewhere new. Cards close to chest = poker face → hidden plans. Hit the roof = explosion → fury. Learn the PICTURE; the sentence then confirms it." },
{ k: "table", h: "2024's own idiom list", html: "<table class='lt'><tr><th>Idiom</th><th>Story → meaning</th></tr><tr><td>off and on</td><td>flickering switch → now and then</td></tr><tr><td>cards close to chest</td><td>poker face → hidden plans</td></tr><tr><td>fish out of water</td><td>misfit → uncomfortable</td></tr><tr><td>hit the roof</td><td>explosion → very angry</td></tr><tr><td>creature of habit</td><td>same track → routine-bound</td></tr><tr><td>a bad patch</td><td>rough ground → period of troubles</td></tr></table>" },
{ k: "try", h: "Try it — real paper", q: { q: "Bincy's mother kept her cards close to her chest. Meaning?", options: ["Kept her plans and thoughts hidden", "Kept all cards safe", "Kept her money by herself", "Showed more affection"], answer: 0, explanation: "Hidden cards → hidden plans. Asked 26 Sept 2024.", rule: "Story + sentence mood.", elim: "Kill literal card/money options.", trap: "Literal traps.", trapcat: "Idioms", level: "L1" } },
{ k: "pick", h: "Beat the examiner", stem: "'Hit the roof' — options: destruct a building / play joyfully / jump high / very angry. Which two are built from the WORDS, not the meaning?", options: ["destruct + jump — literal roof/body", "play joyfully — random", "very angry — too direct"], answer: 0, why: "The examiner builds wrong options from the idiom's WORDS (roof→building, hit→jump). Rule: any option that could illustrate the words literally is bait. Think picture-story, not words." },
{ k: "card", h: "Master card", html: "<b>Core:</b> story → sentence confirms. <b>2-min:</b> the 6 real idioms above; kill literal options." },
],
revision: { min2: "Six 2024 idioms. Kill literal options.", lastmin: "Picture? Sentence mood?" } },

eng_error: { title: "Mixed Error Detection", sub: "Name the topic first. Fix second.",
hook: "Error-spotting is not a topic — it is a CRIME SCENE where SVA, tense, preposition and modifier clues lie mixed. Detectives who name the crime first solve it; those who stare at the sentence drown.",
paperNote: "Paper proof: superior-THAN, ran-QUICK, team-ANTICIPATE, talks-FOR (all Sept 2024). Four errors, four different topics — one skill: 4-pass scan. This topic converts ALL your grammar into marks.",
steps: [
{ k: "coach", h: "The 4-pass scan", html: "<b>Pass 1 — SVA:</b> bracket subject, check verb. <b>Pass 2 — tense/markers.</b> <b>Pass 3 — pairs/articles/case.</b> <b>Pass 4 — modifiers + parallelism</b> (and/but/or join SAME forms). Same order, every sentence, 30 seconds." },
{ k: "rule", h: "Parallelism (the bonus rule)", html: "Items joined by and/but/or/not-only must MATCH form: <i>singing, dancing and swimming</i> — never <i>to swim</i>. SSC hides one odd item at the END of lists." },
{ k: "try", h: "Try it — scan it", q: { q: "Find the error: Each of the students have submitted their project.", options: ["Each of the students", "have submitted", "their project", "No error"], answer: 1, explanation: "Pass 1 SVA: each → has.", rule: "Each + singular.", elim: "Name it: SVA → each → has.", trap: "Students-proximity.", trapcat: "SVA in errors", level: "L1" } },
{ k: "trap", h: "Trap autopsy: the legal suspect", html: "'The number of cases have increased.' TWO suspects: 'cases' (plural!) and 'the number' (singular!). The examiner makes the WRONG suspect look guiltier. Rule: the-number = singular → has. Arrest the grammar, not the proximity." },
{ k: "pick", h: "Beat the examiner", stem: "Error sentence with 'No error' as option D. When is D the trap vs the answer?", options: ["D is always a trap", "D is the answer when all 4 passes clear", "D is never correct in SSC"], answer: 1, why: "Examiners punish students who MUST find an error — they plant clean sentences. If your 4 passes find nothing, choose No error with full confidence. Forcing an error is the real trap." },
{ k: "card", h: "Master card", html: "<b>Core:</b> scan SVA→tense→pairs→modifiers. <b>2-min:</b> name topic first; parallelism matches; No-error is real." },
],
revision: { min2: "4-pass scan. Name topic first.", lastmin: "SVA? Tense? Pair? Modifier? Else No-error." } },

eng_improve: { title: "Sentence Improvement + Fillers", sub: "Best option wins. No-improvement is brave — and often right.",
hook: "Improvement questions punish perfectionists: they refuse to pick 'No improvement' even when the sentence is flawless. And fillers punish half-readers who fill from half a sentence. Both habits are fixable today.",
paperNote: "Paper proof: 'owing PRIMARILY to a RISE' beat casual options (23 Sept S1) — register matters. 'Have been renovating' (18 Sept S3) and the row/roe homonym double-blank (23 Sept S1) show fillers = tense + vocab + logic. 4–5 marks here.",
steps: [
{ k: "coach", h: "Improvement: 3 checks", html: "<b>1. Grammar</b> (tense/SVA/pair?) → <b>2. Redundancy</b> (return back, more better — always wrong) → <b>3. Register</b> (formal wins: owing primarily). Pass all three? Choose <b>No improvement</b> proudly." },
{ k: "rule", h: "Fillers: full sentence first", html: "Read the WHOLE sentence. Then: grammar slot? collocation (pay attention, bear fruit)? charge (+/−)? cause-effect? In double blanks, solve the SURE blank first and strike options that fail it." },
{ k: "try", h: "Try it — real paper register", q: { q: "Substitute: The industry has grown dramatically, chiefly because of a boost in cases.", options: ["pretty much entirely because of a boil-down", "contextually because of a spark", "owing primarily to a rise", "casually due to a growth"], answer: 2, explanation: "Formal register: owing primarily to a rise. Asked 23 Sept 2024.", rule: "Register + collocation.", elim: "Kill unnatural pairings.", trap: "Casual-synonym trap.", trapcat: "Collocation", level: "L1" } },
{ k: "trap", h: "Trap autopsy: homonym double blank", html: "2024 asked row/roe/row-sequence in ONE question. Method: fill each slot by sense separately (action→row verb; sequence→row noun), then match the pair code. Never match codes first." },
{ k: "card", h: "Master card", html: "<b>Core:</b> No-improvement is real; full-sentence fillers. <b>2-min:</b> kill redundancy; formal register; sure-blank-first." },
],
revision: { min2: "Redundancy dies. Formal wins. Full sentence.", lastmin: "3 checks? Sure blank?" } },

eng_cloze_rc: { title: "Cloze Test — The Passage Section", sub: "Tier-1's only passage. Grammar + vocab + story logic.",
hook: "Big truth first: Tier-1 2024 had NO separate reading-comprehension passage. The cloze passage (5 blanks) IS your passage section — 5 marks, 10% of English. And the real one was LITERARY (O. Henry style, 9 Sept S1) — descriptive, vocab-heavy. Train on passages below, not single sentences.",
paperNote: "Paper proof: the 9 Sept S1 cloze told a story about an old artist's sacrifice — blanks tested presentation/style words (prone…), sympathy, heroism. Lesson: cloze = read the STORY first; blanks second. Tone and logic decide as much as grammar.",
steps: [
{ k: "coach", h: "Blank-by-blank battle plan", html: "<b>1.</b> Read the whole passage — never fill blank 1 blind. <b>2.</b> Grammar slot (noun? tense? prep after it?). <b>3.</b> Collocation (which word lives with neighbours?). <b>4.</b> Story logic (but/however FLIP the charge). Four passes per blank." },
{ k: "rule", h: "Contrast words are gold", html: "But, however, although, yet, despite — everything after them reverses charge. In cloze, the blank AFTER a contrast word almost always needs the opposite-feeling word. Circle contrasts before options." },
{ k: "try", h: "Try it", q: { q: "He ___ his request with evidence, so the officer approved it.", options: ["ignored", "supported", "hid", "opposed"], answer: 1, explanation: "Cause (evidence) → effect (approved) needs positive supported.", rule: "Cause-effect logic.", elim: "Approved-effect kills negatives.", trap: "Grammar-fits-logic-breaks trap.", trapcat: "Cloze logic", level: "L1" } },
{ k: "trap", h: "Trap autopsy: the grammar-fit liar", html: "An option can fit the grammar slot PERFECTLY and still be wrong because it breaks the story (e.g., 'ignored' fits grammatically above). Grammar is a filter, logic is the judge. Check both, in that order." },
{ k: "card", h: "Master card", html: "<b>Core:</b> full read → slot → collocation → logic. <b>2-min:</b> circle contrasts; cause-effect; literary tone ready." },
],
revision: { min2: "Read all. Slot, collocation, logic.", lastmin: "Contrast circled? Story charge?" } },

eng_jumble: { title: "Para Jumbles (PQRS)", sub: "Two free marks. Links, not luck.",
hook: "Jumbles are the most under-practised 2 marks in Tier-1. No vocabulary needed, no grammar — just follow the LINKS between sentences like a detective following footprints.",
paperNote: "Paper proof: EVERY Sept 2024 shift carried 2 jumble Qs (sentence-order like 18 Sept S3's set + paragraph coherence). Two marks for pronoun-tracking. The method below solves all of them.",
steps: [
{ k: "coach", h: "Follow the links", html: "<b>Pronouns</b> (it/he/they) point BACKWARD — their noun must come first. <b>Connectors</b> (however/but/so) pivot — however needs a claim before it. <b>Chronology</b> (cause→effect→response) orders events. <b>Topic sentence</b> (general, no pronouns) opens." },
{ k: "rule", h: "Mandatory pairs", html: "Cause→effect (failed monsoon → withered crops). Problem→solution. Theme→example. General→specific. Find ONE certain pair first — it kills two options instantly." },
{ k: "try", h: "Try it — real paper", q: { q: "Order the sentence: A: new facts and advanced / B: but my opinion is / C: he has discovered / D: unchanged / E: new arguments.", options: ["BDAEC", "EBDCA", "DACBE", "CAEBD"], answer: 3, explanation: "S-V-O core first (C-A-E), but-clause (B-D) last. Asked 18 Sept 2024.", rule: "Core first, but-clause last.", elim: "C opens (subject); B closes.", trap: "But-first trap.", trapcat: "Sentence order", level: "L1" } },
{ k: "pick", h: "Beat the examiner", stem: "Options: PQRS / PRQS / QPRS / PSQR. You found that Q (However…) must follow P. How many options die?", options: ["Zero — keep checking", "Two — kill Q-first options", "All but one"], answer: 1, why: "QPRS and Q-first options die immediately — however cannot open. One certain link kills half the options. Jumbles are elimination questions wearing arrangement clothes." },
{ k: "card", h: "Master card", html: "<b>Core:</b> pronouns back, however pivots, chronology orders. <b>2-min:</b> find one certain pair → kill 2 options." },
],
revision: { min2: "Links: pronouns, however, chronology.", lastmin: "One certain pair → kill 2." } },
};
