/* PASSAGES — cloze passages (Tier-1's passage section). 5 blanks each.
   Blank Qs use the same schema + psg (passage id) so the engine shows text. */
const PASSAGES = [
{ id: "cz1", title: "The Last Leaf (literary, O. Henry style)", note: "Descriptive-literary — exactly the flavour of the 9 Sept 2024 cloze.",
text: "The old artist lived in a (1)___ little room above the street. He had painted for forty years without fame, yet his neighbours loved him for his (2)___ heart. One winter, a young girl fell ill and lost the will to live, counting the ivy leaves as they fell. 'When the last leaf falls, I shall go too,' she whispered. That night, a storm (3)___ the city, and by morning every leaf was gone — (4)___ one, painted on the wall by the old artist in the rain. The girl saw it and smiled; her hope (5)___ with the sunrise. The artist caught pneumonia that night and never rose again.",
blanks: [
{ q: "Blank 1: a ___ little room", options: ["spacious", "tiny", "luxurious", "noisy"], answer: 1, explanation: "Poor old artist → tiny fits the story.", rule: "Story logic: poverty.", elim: "Poor artist kills spacious/luxurious.", trap: "Positive-word trap.", trapcat: "Cloze logic", level: "L1" },
{ q: "Blank 2: his ___ heart", options: ["cold", "generous", "weak", "proud"], answer: 1, explanation: "Loved by neighbours + final sacrifice → generous.", rule: "Character logic.", elim: "Sacrifice-ending → generous.", trap: "Weak (illness) trap.", trapcat: "Cloze logic", level: "L2" },
{ q: "Blank 3: a storm ___ the city", options: ["visited", "lashed", "missed", "ignored"], answer: 1, explanation: "Storm + leaves stripped → lashed (collocation: storm lashed).", rule: "Collocation: lashed.", elim: "Storm-verb → lashed.", trap: "Mild-verb trap.", trapcat: "Cloze vocab", level: "L2" },
{ q: "Blank 4: every leaf was gone — ___ one", options: ["besides", "except", "without", "among"], answer: 1, explanation: "All gone but one → except.", rule: "Exception logic.", elim: "All-but-one → except.", trap: "Besides (addition) trap.", trapcat: "Cloze logic", level: "L2" },
{ q: "Blank 5: her hope ___ with the sunrise", options: ["faded", "returned", "slept", "feared"], answer: 1, explanation: "Smiled + sunrise → hope returned.", rule: "Cause-effect: smile → return.", elim: "Positive turn → returned.", trap: "Faded (illness drag) trap.", trapcat: "Cloze logic", level: "L3" },
] },
{ id: "cz2", title: "The Monsoon Postman (narrative)", note: "Story passage — sequence + prepositions.",
text: "Ravi had carried letters through the village for twenty years, in heat and rain (1)___. The monsoon of 2019 tested him like never before: the river rose (2)___ the bridge, and the road to the hills vanished. Yet every morning he tied his bag in plastic, (3)___ his bicycle, and rode out. 'Letters do not wait for sunshine,' he laughed. The villagers waited (4)___ him at the banyan tree, and children ran (5)___ him shouting his name. When the district office honoured him that winter, he simply said the road had taught him patience.",
blanks: [
{ q: "Blank 1: in heat and rain ___", options: ["alike", "likely", "alone", "apart"], answer: 0, explanation: "Fixed phrase: heat and rain alike (= both equally).", rule: "Collocation.", elim: "Alike completes the pair.", trap: "Alone (loneliness) trap.", trapcat: "Cloze vocab", level: "L1" },
{ q: "Blank 2: the river rose ___ the bridge", options: ["above", "under", "beside", "behind"], answer: 0, explanation: "Flood → water above the bridge.", rule: "Place logic.", elim: "Rose + flood → above.", trap: "Under (river default) trap.", trapcat: "Cloze logic", level: "L2" },
{ q: "Blank 3: ___ his bicycle, and rode out", options: ["mounted", "counted", "painted", "lifted"], answer: 0, explanation: "Rode out needs mounted.", rule: "Verb logic.", elim: "Ride → mount.", trap: "Lifted (bag confusion) trap.", trapcat: "Cloze vocab", level: "L2" },
{ q: "Blank 4: waited ___ him", options: ["to", "for", "at", "on"], answer: 1, explanation: "Wait for a person.", rule: "Fixed pair: wait for.", elim: "Person → for.", trap: "At (place) trap.", trapcat: "Cloze grammar", level: "L1" },
{ q: "Blank 5: ran ___ him shouting", options: ["after", "towards", "from", "against"], answer: 1, explanation: "Joyful greeting → ran towards him.", rule: "Direction logic.", elim: "Welcome → towards.", trap: "After (chase) trap.", trapcat: "Cloze logic", level: "L3" },
] },
{ id: "cz3", title: "The Wonder of Millets (informative)", note: "Fact passage — the UPSC/SSC favourite genre.",
text: "Millets, once called coarse grains, are making a (1)___ comeback on Indian plates. These tiny grains need very little water and grow even in poor soils, which makes them ideal (2)___ dry regions. Nutritionists praise them because they release energy slowly and keep a person full (3)___ longer. The government has pushed millet missions, and chefs now serve millet dosas and salads (4)___ pride. What was once poor man's food is (5)___ becoming smart food.",
blanks: [
{ q: "Blank 1: making a ___ comeback", options: ["silent", "strong", "secret", "slow"], answer: 1, explanation: "Missions + chefs + plates everywhere → strong.", rule: "Evidence logic.", elim: "Wide revival → strong.", trap: "Slow (grains grow slow) trap.", trapcat: "Cloze logic", level: "L1" },
{ q: "Blank 2: ideal ___ dry regions", options: ["to", "for", "of", "at"], answer: 1, explanation: "Ideal for + purpose/place.", rule: "Fixed pair: ideal for.", elim: "Ideal → for.", trap: "To-infinitive trap.", trapcat: "Cloze grammar", level: "L2" },
{ q: "Blank 3: keep a person full ___ longer", options: ["for", "since", "from", "by"], answer: 0, explanation: "Duration → for longer.", rule: "For + period.", elim: "Longer-duration → for.", trap: "Since (needs point) trap.", trapcat: "Cloze grammar", level: "L2" },
{ q: "Blank 4: serve dosas and salads ___ pride", options: ["with", "by", "in", "of"], answer: 0, explanation: "Do with pride (collocation).", rule: "Collocation: with pride.", elim: "Pride → with.", trap: "In-pride trap.", trapcat: "Cloze vocab", level: "L2" },
{ q: "Blank 5: is ___ becoming smart food", options: ["now", "never", "hardly", "seldom"], answer: 0, explanation: "Revival in progress → now.", rule: "Tense logic.", elim: "Comeback → now.", trap: "Negative-word traps.", trapcat: "Cloze logic", level: "L1" },
] },
{ id: "cz4", title: "Why We Forget (abstract)", note: "Idea passage — inference-style blanks.",
text: "Forgetting is not a failure of memory but a (1)___ of it. The brain deletes routine details — where you kept your keys, what you ate Tuesday — to protect space for what matters. Scientists (2)___ that each time we recall an event, we rebuild it slightly differently, which is why two witnesses remember the same accident in (3)___ ways. Students should therefore test themselves often: every recall (4)___ the memory trace a little deeper. Forgetting, in short, is the mind's way of (5)___ the irrelevant so the important can shine.",
blanks: [
{ q: "Blank 1: not a failure but a ___", options: ["feature", "mistake", "disease", "joke"], answer: 0, explanation: "Contrast with failure → positive feature.", rule: "Not-X-but-Y contrast.", elim: "But → positive → feature.", trap: "Mistake (echoes failure) trap.", trapcat: "Cloze logic", level: "L2" },
{ q: "Blank 2: Scientists ___ that each recall rebuilds", options: ["doubt", "deny", "argue", "forget"], answer: 2, explanation: "Research claim → argue (maintain).", rule: "Reporting verb.", elim: "Claim → argue.", trap: "Deny/doubt (negative) traps.", trapcat: "Cloze vocab", level: "L2" },
{ q: "Blank 3: remember in ___ ways", options: ["similar", "different", "perfect", "brilliant"], answer: 1, explanation: "Rebuilt differently → different.", rule: "Logic carry-over.", elim: "Differently above → different.", trap: "Perfect-memory myth trap.", trapcat: "Cloze logic", level: "L1" },
{ q: "Blank 4: every recall ___ the trace deeper", options: ["erases", "carves", "weakens", "paints"], answer: 1, explanation: "Test-yourself advice → strengthens; carves deeper fits.", rule: "Metaphor logic.", elim: "Deeper + positive → carves.", trap: "Erases (forget-theme) trap.", trapcat: "Cloze vocab", level: "L3" },
{ q: "Blank 5: way of ___ the irrelevant", options: ["keeping", "framing", "filtering", "counting"], answer: 2, explanation: "Deleting routine details → filtering.", rule: "Summary logic.", elim: "Remove-noise → filtering.", trap: "Keeping (opposite) trap.", trapcat: "Cloze logic", level: "L2" },
] },
];
