/* PYQ.js — REAL SSC CGL Tier-1 2024 questions (official answer-key papers).
   src = paper label. Only verbatim-or-near-verbatim Qs carry src.
   Merged into BANK by app.js on `topic`. */
const PYQ = [
/* ---------- ERROR DETECTION (real 2024 errors) ---------- */
{ topic: "eng_error", q: "Identify the segment with the error: Mrs. Sreelakshmi's musical intelligence / is superior than / Mrs. Suma's.", options: ["Mrs. Sreelakshmi's", "musical intelligence", "is superior than", "Mrs. Suma's"], answer: 2, explanation: "Superior always takes TO, never than — the error sits in segment 3.", rule: "Superior/inferior/junior/senior + to (never than).", elim: "See superior → expect to; than exposes the error.", trap: "Than-by-comparison habit.", trapcat: "Pairs in errors", level: "L4 PYQ", src: "CGL 2024 · 9 Sept S1" },
{ topic: "eng_error", q: "Select the option that corrects the error: He ran quick to catch the bus.", options: ["quiet", "rapid", "insipid", "quickly"], answer: 3, explanation: "Ran is an action verb — it needs the adverb quickly, not the adjective quick.", rule: "Action verb + adverb (-ly).", elim: "Verb + modifier → adverb; only quickly qualifies.", trap: "Adjective-for-verb trap — the exact mistake SSC planted.", trapcat: "Modifiers", level: "L4 PYQ", src: "CGL 2024 · 9 Sept S1" },
{ topic: "eng_error", q: "Find the error: The team always anticipate a victory in every match.", options: ["The team", "always anticipate", "a victory", "No error"], answer: 1, explanation: "Team (singular) + always (habit, present) → anticipates.", rule: "SVA + habitual present.", elim: "Subject team singular → verb needs -s.", trap: "Plural-idea trap (a team feels plural).", trapcat: "SVA in errors", level: "L4 PYQ", src: "CGL 2024 · 13 Sept S1" },
{ topic: "eng_error", q: "Identify the segment with the grammatical error: He never talks / for anybody. / He is alone / all day.", options: ["He never talks", "for anybody", "He is alone", "all day"], answer: 1, explanation: "Talk TO a person, not for — wrong preposition with the verb.", rule: "Verb + fixed preposition: talk to.", elim: "Talks + person → to; for is the planted error.", trap: "For/to blur trap.", trapcat: "Pairs in errors", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
/* ---------- SENTENCE IMPROVEMENT (real 2024) ---------- */
{ topic: "eng_improve", q: "Substitute the underlined segment: The food intolerance industry has grown dramatically, chiefly because of a boost in cases.", options: ["pretty much entirely because of a boil-down", "contextually because of a spark", "owing primarily to a rise", "casually due to a growth"], answer: 2, explanation: "Formal register wins: owing primarily to a rise. The rest are unnatural collocations.", rule: "Formal collocation + register.", elim: "Kill unnatural pairings (boil-down, spark, casually) — formal tone decides.", trap: "Casual-synonym trap.", trapcat: "Collocation", level: "L4 PYQ", src: "CGL 2024 · 23 Sept S1" },
{ topic: "eng_improve", q: "Substitute the underlined segment: Gourav was no good than a foolish person.", options: ["no better", "not good", "no best", "No improvement"], answer: 0, explanation: "Comparison of two → comparative: no better than.", rule: "Double -er ban; comparison → comparative.", elim: "Than signals comparison → comparative form.", trap: "Double-form confusion.", trapcat: "Redundancy", level: "L4 PYQ", src: "CGL 2024 · 9 Sept S1" },
{ topic: "eng_improve", q: "Substitute the underlined segment: The team always anticipate a bowling friendly pitch on their easy victory.", options: ["pitch over their easy victory", "pitch to their easy victory", "pitch for their easy victory", "pitch of their easy victory"], answer: 1, explanation: "Anticipate + to (expect in relation to the victory).", rule: "Verb + fixed preposition.", elim: "Anticipate → to.", trap: "Any-preposition trap.", trapcat: "Fixed pairs", level: "L4 PYQ", src: "CGL 2024 · 13 Sept S1" },
{ topic: "eng_improve", q: "Substitute the underlined word: Satya is always great to his friends who helped him.", options: ["grateful", "no substitution", "thanked", "greatful"], answer: 0, explanation: "Great = big; grateful = thankful. Sense needs grateful.", rule: "Confused pair: great vs grateful.", elim: "Thankful sense → grateful.", trap: "Lookalike trap (greatful is not even a word).", trapcat: "Confused words", level: "L4 PYQ", src: "CGL 2024 · 13 Sept S1" },
{ topic: "eng_improve", q: "Substitute the underlined segment: Sanat requests Raghu to help him find an appropriate location.", options: ["a suitable elevation", "a rented accommodation", "a proper junction", "an allocation recommendation"], answer: 1, explanation: "A newcomer on transfer needs a rented accommodation — the only natural collocation.", rule: "Collocation + context.", elim: "Transfer + stay → accommodation.", trap: "Fancy-word trap (allocation recommendation).", trapcat: "Collocation", level: "L4 PYQ", src: "CGL 2024 · 23 Sept S1" },
{ topic: "eng_improve", q: "Substitute the underlined segment: If I was the queen, I would give a handsome sum.", options: ["If I was the queen", "If I were the queen", "If I am the queen", "No improvement"], answer: 1, explanation: "Imaginary if → subjunctive were, never was.", rule: "Unreal condition → were.", elim: "Would in result → were in condition.", trap: "Was-agreement trap.", trapcat: "Conditionals", level: "L4 PYQ", src: "CGL 2024 · 9 Sept S1" },
/* ---------- NARRATION / REPORTED GRAMMAR (real 2024) ---------- */
{ topic: "eng_narration", q: "Substitute the underlined segment: Do you know where does she reside?", options: ["where she resides?", "where do she reside?", "where she reside?", "where does she resides?"], answer: 0, explanation: "Reported question → statement order (no inversion), verb agrees: she resides.", rule: "Reported wh-question: no inversion.", elim: "Kill every inverted option; kill resides mismatch.", trap: "Direct-question-order trap.", trapcat: "Reported questions", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
/* ---------- PRONOUNS (real 2024) ---------- */
{ topic: "eng_pronouns", q: "Substitute the underlined segment: A computer can't function without it's mother board.", options: ["its", "it is", "their", "his"], answer: 0, explanation: "Possessive → its (no apostrophe); it's = it is.", rule: "its (possessive) vs it's (it is).", elim: "Possession → its.", trap: "Apostrophe trap.", trapcat: "Its/it's", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
/* ---------- VOICE (real 2024, both directions) ---------- */
{ topic: "eng_voice", q: "Express in ACTIVE voice: His father's arm was bandaged by the kind nurse.", options: ["The kind nurse bandaged his father's arm.", "The kind nurse bandages his father's arm.", "The kind nurse has bandaged his father's arm.", "The kind nurse had bandaged his father's arm."], answer: 0, explanation: "Was + V3 → simple past active. Tense never changes.", rule: "Passive→active: keep tense.", elim: "Was → past → bandaged only.", trap: "Tense-shift trap (3 of 4 options shift tense).", trapcat: "Tense match", level: "L4 PYQ", src: "CGL 2024 · 25 Sept S3" },
{ topic: "eng_voice", q: "Express in PASSIVE voice: The team will announce the winner tomorrow.", options: ["The winner will be announced by the team tomorrow.", "The winner will announce tomorrow by the team.", "Tomorrow will be announced the winner by the team.", "The team will announce tomorrow the winner."], answer: 0, explanation: "Future → will be + V3; winner becomes subject.", rule: "Future → will be + V3.", elim: "Needs will be + announced — only A.", trap: "Missing-be / scrambled-order traps.", trapcat: "Being/been", level: "L4 PYQ", src: "CGL 2024 · 13 Sept S1" },
{ topic: "eng_voice", q: "Express in PASSIVE voice: Sonam does not like bananas.", options: ["Banana is not liked by Sonam.", "Bananas have not been liked by Sonam.", "Bananas are not liked by Sonam.", "Bananas had not been liked by Sonam."], answer: 2, explanation: "Negative simple present → are + not + V3; plural subject stays plural.", rule: "Negatives keep do-support as not + be.", elim: "Present → are; bananas plural kills A.", trap: "Singular-banana + tense-shift traps.", trapcat: "Negatives", level: "L4 PYQ", src: "CGL 2024 · 9 Sept S1" },
{ topic: "eng_voice", q: "Express in PASSIVE voice: People know Stellenbosch for its greenery and delicious street foods.", options: ["Stellenbosch was known to people for its greenery and delicious street foods.", "Stellenbosch have been known to people for its greenery and delicious street foods.", "Stellenbosch had been known to people for its greenery and delicious street foods.", "Stellenbosch is known to people for its greenery and delicious street foods."], answer: 3, explanation: "Simple present → is + V3; place phrase rides along unchanged.", rule: "Present → is + V3.", elim: "Present → is; kill was/have/had.", trap: "Triple tense-shift trap.", trapcat: "Tense match", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
{ topic: "eng_voice", q: "Express in PASSIVE voice: Someone has taken my secret diary.", options: ["My secret diary had been taken by someone.", "My secret diary has to be taken by someone.", "My secret diary has been taken by someone.", "My secret diary will have been taken by someone."], answer: 2, explanation: "Present perfect → has been + V3.", rule: "Perfect → been.", elim: "Has → has been.", trap: "Modal/future substitution traps.", trapcat: "Being/been", level: "L4 PYQ", src: "CGL 2024 · 9 Sept S1" },
/* ---------- SYNONYMS in sentences (real 2024) ---------- */
{ topic: "eng_vocab", q: "Synonym of the word in bold: The choice was judicious as further events proved.", options: ["hasty", "ridiculous", "prudent", "silly"], answer: 2, explanation: "Judicious = wise in judgment → prudent.", rule: "Root + sense: judgment → prudent.", elim: "Positive charge kills hasty/ridiculous/silly.", trap: "Formal-word intimidation.", trapcat: "Synonyms", level: "L4 PYQ", src: "CGL 2024 · 25 Sept S3" },
{ topic: "eng_vocab", q: "Synonym of the underlined word: It was his decency that he employed him.", options: ["Deception", "Courtesy", "Rudeness", "Perversion"], answer: 1, explanation: "Decency = polite conduct → courtesy.", rule: "Sense in sentence.", elim: "Positive act → courtesy.", trap: "Deception lookalike trap.", trapcat: "Synonyms", level: "L4 PYQ", src: "CGL 2024 · 25 Sept S3" },
{ topic: "eng_vocab", q: "Synonym of the word in bold: The city has immense coal piers.", options: ["diminutive", "trifling", "huge", "set"], answer: 2, explanation: "Immense = vast → huge.", rule: "Size sense.", elim: "Big-meaning → huge; small words die.", trap: "Formal-word trap.", trapcat: "Synonyms", level: "L4 PYQ", src: "CGL 2024 · 23 Sept S1" },
{ topic: "eng_vocab", q: "Synonym of the given word: Brittle.", options: ["Furtive", "Fatal", "Fragile", "Fickle"], answer: 2, explanation: "Brittle = breaks easily → fragile.", rule: "Material sense.", elim: "Breakable → fragile.", trap: "F-lookalike cluster trap.", trapcat: "Synonyms", level: "L4 PYQ", src: "CGL 2024 · 23 Sept S1" },
{ topic: "eng_vocab", q: "Synonym of the given word: Cherish.", options: ["Neglect", "Afflict", "Nurture", "Breach"], answer: 2, explanation: "Cherish = care for deeply → nurture.", rule: "Care sense.", elim: "Loving → nurture; harsh words die.", trap: "Opposite-as-option trap.", trapcat: "Synonyms", level: "L4 PYQ", src: "CGL 2024 · 23 Sept S1" },
{ topic: "eng_vocab", q: "Synonym of the given word: Adequate.", options: ["Hidden", "Sufficient", "Reconcile", "Evaluate"], answer: 1, explanation: "Adequate = enough → sufficient.", rule: "Enough sense.", elim: "Enough → sufficient.", trap: "Verb-form traps (reconcile/evaluate).", trapcat: "Synonyms", level: "L4 PYQ", src: "CGL 2024 · 23 Sept S1" },
{ topic: "eng_vocab", q: "Synonym of the given word: Munificent.", options: ["Miserly", "Malicious", "Underappreciated", "Magnanimous"], answer: 3, explanation: "Munificent = very generous → magnanimous. Many marked miserly — the official key says magnanimous.", rule: "Generosity sense.", elim: "Giving → magnanimous.", trap: "Miserly opposite-root trap (the 2024 killer).", trapcat: "Synonyms", level: "L4 PYQ", src: "CGL 2024 · 26 Sept" },
/* ---------- ANTONYMS (real 2024) ---------- */
{ topic: "eng_vocab", q: "Antonym of the underlined word: I am quite unsure about the risks involved.", options: ["Interested", "Certain", "Doubtful", "Thoughtful"], answer: 1, explanation: "Unsure ≠ certain.", rule: "Direct reversal.", elim: "Unsure → certain; doubtful is a synonym.", trap: "Synonym-as-option trap (doubtful).", trapcat: "Antonyms", level: "L4 PYQ", src: "CGL 2024 · 25 Sept S3" },
{ topic: "eng_vocab", q: "Antonym of the underlined word: Coffee was too hot; it burnt my tongue.", options: ["Balmy", "Scorching", "Frigid", "Subtle"], answer: 2, explanation: "Hot ≠ frigid (intensely cold).", rule: "Intensity-aware reversal.", elim: "Burnt → cold extreme → frigid.", trap: "Mild-opposite trap (balmy is warm, not opposite).", trapcat: "Antonyms", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
{ topic: "eng_vocab", q: "Antonym of the given word: Envious.", options: ["Suspicious", "Generous", "Untrustworthy", "Malicious"], answer: 1, explanation: "Envious (resenting others' good) ≠ generous (giving freely).", rule: "Attitude reversal.", elim: "Giving ↔ resenting.", trap: "Negative-cluster trap.", trapcat: "Antonyms", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
{ topic: "eng_vocab", q: "Antonym of the word in bold: His mother never held a grudge against his father.", options: ["benevolence", "malevolence", "rancour", "revulsion"], answer: 0, explanation: "Grudge (ill-will) ≠ benevolence (goodwill).", rule: "Will-sense reversal.", elim: "Ill-will → good-will.", trap: "Malevolence synonym trap.", trapcat: "Antonyms", level: "L4 PYQ", src: "CGL 2024 · 13 Sept S1" },
{ topic: "eng_vocab", q: "Antonym of the given word: Barbarity.", options: ["Rivalry", "Callous", "Compassion", "Compromise"], answer: 2, explanation: "Barbarity (cruelty) ≠ compassion.", rule: "Cruelty reversal.", elim: "Cruel ↔ kind.", trap: "Callous synonym trap.", trapcat: "Antonyms", level: "L4 PYQ", src: "CGL 2024 · 13 Sept S1" },
{ topic: "eng_vocab", q: "Fill the blank with the antonym: He is always active in a party but ___ in the class.", options: ["angry", "inert", "careless", "naughty"], answer: 1, explanation: "Active ≠ inert (lifeless/inactive) — and but signals contrast.", rule: "Contrast-word + reversal.", elim: "But → opposite of active → inert.", trap: "Behaviour-word traps (naughty/careless fit class, not the contrast).", trapcat: "Antonyms", level: "L4 PYQ", src: "CGL 2024 · 26 Sept" },
{ topic: "eng_vocab", q: "Antonym of the underlined word: An elephant is a large mammal.", options: ["Bumper", "Gigantic", "Tiny", "Heroic"], answer: 2, explanation: "Large ≠ tiny.", rule: "Size reversal.", elim: "Big ↔ small.", trap: "Gigantic synonym trap.", trapcat: "Antonyms", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
/* ---------- ONE-WORD SUBSTITUTION (real 2024) ---------- */
{ topic: "eng_ows", q: "Substitute the underlined segment: The betrayer of the country was at last unmasked.", options: ["theist", "traitor", "truant", "transgressor"], answer: 1, explanation: "Country-betrayer → traitor.", rule: "Hook: betray country.", elim: "Betray → traitor.", trap: "Transgressor (rule-breaker, not betrayer) trap.", trapcat: "OWS", level: "L4 PYQ", src: "CGL 2024 · 25 Sept S3" },
{ topic: "eng_ows", q: "Substitute the group of words: Loud enough to be heard.", options: ["Audit", "Audacity", "Audacious", "Audible"], answer: 3, explanation: "Hearable → audible.", rule: "Hook: heard → audi-.", elim: "Hear-root → audible.", trap: "Aud-prefix cluster trap.", trapcat: "OWS", level: "L4 PYQ", src: "CGL 2024 · 26 Sept" },
{ topic: "eng_ows", q: "Substitute the underlined segment: The line uses the repetition of initial consonant sounds in neighbouring words.", options: ["alliteration", "epithet", "allegory", "simile"], answer: 0, explanation: "Repeated initial sounds → alliteration (SSC tests literary terms too).", rule: "Hook: repeated sounds.", elim: "Sound-repetition → alliteration.", trap: "Literary-term cluster trap.", trapcat: "OWS", level: "L4 PYQ", src: "CGL 2024 · 25 Sept S3" },
{ topic: "eng_ows", q: "Substitute the group of words: Speaking disrespectfully about sacred or religious things.", options: ["Mystic", "Atheist", "Blasphemy", "Theist"], answer: 2, explanation: "Disrespect toward sacred → blasphemy.", rule: "Hook: sacred + disrespect.", elim: "Sacred-disrespect → blasphemy.", trap: "Atheist (disbelief, not disrespect) trap.", trapcat: "OWS", level: "L4 PYQ", src: "CGL 2024 · 23 Sept S1" },
{ topic: "eng_ows", q: "Substitute the group of words: A false idea or belief.", options: ["Reticence", "Atrophy", "Fallacy", "Entropy"], answer: 2, explanation: "False belief → fallacy.", rule: "Hook: false belief.", elim: "False → fallacy.", trap: "Formal-word cluster trap.", trapcat: "OWS", level: "L4 PYQ", src: "CGL 2024 · 9 Sept S1" },
{ topic: "eng_ows", q: "Substitute the group of words: Having unlimited power.", options: ["Omnipotent", "Omnivorous", "Omnipresence", "Omniscient"], answer: 0, explanation: "All-powerful → omnipotent.", rule: "Hook: power → -potent.", elim: "Power → potent.", trap: "Omni-cluster trap.", trapcat: "OWS", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
{ topic: "eng_ows", q: "Substitute the group of words: Cannot be corrected.", options: ["Incorrigible", "Illegible", "Incredible", "Ineligible"], answer: 0, explanation: "Uncorrectable → incorrigible.", rule: "Hook: correct → corrigible.", elim: "Correct-root → incorrigible.", trap: "In- cluster trap.", trapcat: "OWS", level: "L4 PYQ", src: "CGL 2024 · 13 Sept S1" },
{ topic: "eng_ows", q: "Substitute the group of words: A short stay while on a longer journey.", options: ["Tent", "Refugee", "Stopover", "Saga"], answer: 2, explanation: "Journey-break → stopover.", rule: "Hook: journey + halt.", elim: "Halt → stopover.", trap: "Tent (stay, not journey-break) trap.", trapcat: "OWS", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
{ topic: "eng_ows", q: "Substitute the group of words: A written statement made under oath.", options: ["Statement", "Testimony", "Affirmation", "Affidavit"], answer: 3, explanation: "Sworn written statement → affidavit.", rule: "Hook: oath + written.", elim: "Oath → affidavit.", trap: "Testimony (spoken) trap.", trapcat: "OWS", level: "L4 PYQ", src: "CGL 2024 · 13 Sept S1" },
/* ---------- IDIOMS in sentences (real 2024) ---------- */
{ topic: "eng_idioms", q: "Meaning of the idiom: Off and on.", options: ["Now and then", "Know something thoroughly", "Object to", "Remind"], answer: 0, explanation: "Off and on = intermittently → now and then.", rule: "Story: switch flickering.", elim: "Occasional sense → now and then.", trap: "Know-thoroughly formal trap.", trapcat: "Idioms", level: "L4 PYQ", src: "CGL 2024 · 23 Sept S1" },
{ topic: "eng_idioms", q: "Meaning of the underlined idiom: Bincy's mother kept her cards close to her chest.", options: ["Kept her plans and thoughts hidden", "Kept all cards safe", "Kept her money by herself", "Showed more affection"], answer: 0, explanation: "Hidden cards → hidden plans.", rule: "Story: poker face.", elim: "Chest-hidden → hidden plans.", trap: "Literal-card traps.", trapcat: "Idioms", level: "L4 PYQ", src: "CGL 2024 · 26 Sept" },
{ topic: "eng_idioms", q: "Meaning of the underlined idiom: In my new office everyone was different, so I felt like a fish out of water.", options: ["Uncomfortable in unfamiliar surroundings", "Enjoying a swim", "Catching fish fast", "Feeling thirsty"], answer: 0, explanation: "Fish ashore = misfit → uncomfortable.", rule: "Story: misfit.", elim: "New-office context → discomfort.", trap: "Literal-fish traps.", trapcat: "Idioms", level: "L4 PYQ", src: "CGL 2024 · 9 Sept S1" },
{ topic: "eng_idioms", q: "Meaning of the idiom: Hit the roof.", options: ["To destruct a building", "To play joyfully", "To jump high", "To become very angry"], answer: 3, explanation: "Anger exploding upward → very angry.", rule: "Story: explosion.", elim: "Extreme reaction → anger.", trap: "Literal-roof traps.", trapcat: "Idioms", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
{ topic: "eng_idioms", q: "Meaning of the idiom: Creature of habit.", options: ["One who does the same thing in the same way", "A mean person", "A faithful dog", "A bad habit"], answer: 0, explanation: "Routine-bound person.", rule: "Story: same track daily.", elim: "Habit → routine.", trap: "Creature-literal traps (dog).", trapcat: "Idioms", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
{ topic: "eng_idioms", q: "Meaning of the idiom: A bad patch.", options: ["A path that is untravelled", "A dangerous road", "A person who takes a difficult path", "A period of troubles"], answer: 3, explanation: "Rough phase of life → period of troubles.", rule: "Story: rough patch.", elim: "Phase sense → period.", trap: "Path-literal traps.", trapcat: "Idioms", level: "L4 PYQ", src: "CGL 2024 · 13 Sept S1" },
/* ---------- SPELLING, all 3 real formats ---------- */
{ topic: "eng_ows", q: "Select the INCORRECTLY spelt word.", options: ["Embarrass", "Occurrence", "Exhilerate", "Accommodate"], answer: 2, explanation: "Correct: exhilarate (ex-hil-arate). The double-letter gang is all correct.", rule: "Double-letter memory: embarrass/occurrence/accommodate.", elim: "Verify each double; exhilerate breaks.", trap: "Hili/hile blur trap.", trapcat: "Spelling", level: "L4 PYQ", src: "CGL 2024 · 9 Sept S1" },
{ topic: "eng_ows", q: "Select the INCORRECTLY spelt word.", options: ["Exceed", "Proceed", "Succeed", "Preceed"], answer: 3, explanation: "Correct: precede (pre + cede). The -ceed trio is right.", rule: "exceed/proceed/succeed vs preCEDE.", elim: "Pre + cede → precede.", trap: "-ceed-everywhere trap.", trapcat: "Spelling", level: "L4 PYQ", src: "CGL 2024 · 9 Sept S1" },
{ topic: "eng_ows", q: "Rectify the misspelt word: In our quest for power, we often fail to acknowlege others.", options: ["acknowledge", "accknowledge", "acknowlede", "acknowledje"], answer: 0, explanation: "ac-KNOW-ledge: -wledge ending.", rule: "Know-root spelling.", elim: "Know inside → acknowledge.", trap: "Double-c / -dge traps.", trapcat: "Spelling", level: "L4 PYQ", src: "CGL 2024 · 26 Sept" },
{ topic: "eng_ows", q: "Substitute the misspelt word: In any crisis, there is always one mument that stands out.", options: ["mumont", "mumunt", "moment", "momont"], answer: 2, explanation: "Correct: moment.", rule: "Vowel-memory: m-O-m-E-nt.", elim: "Only moment is a word.", trap: "U/O blur trap.", trapcat: "Spelling", level: "L4 PYQ", src: "CGL 2024 · 25 Sept S3" },
{ topic: "eng_ows", q: "Fill the blank with the correct spelling: Hiren loves to use ___ words while writing.", options: ["colloquial", "colloqual", "colloquil", "coloquial"], answer: 0, explanation: "colloqui + al → colloquial.", rule: "-quial ending.", elim: "Only A is a dictionary word.", trap: "Single/double-l trap.", trapcat: "Spelling", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
{ topic: "eng_ows", q: "Select the INCORRECTLY spelt word: Economics began with growth and removel of poverty.", options: ["Poverty", "Removel", "Grand", "Economics"], answer: 1, explanation: "Correct: removal (remove + al).", rule: "Remove → removal.", elim: "E-ending drops: removal.", trap: "Keep-the-e trap.", trapcat: "Spelling", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
{ topic: "eng_ows", q: "Select the INCORRECTLY spelt word.", options: ["Reinforcement", "Motivational", "Opportunity", "Atributes"], answer: 3, explanation: "Correct: attributes (at-trib-utes).", rule: "Double-t memory.", elim: "At-tributes.", trap: "Single-t trap.", trapcat: "Spelling", level: "L4 PYQ", src: "CGL 2024 · 13 Sept S1" },
{ topic: "eng_ows", q: "Select the MISSPELT word: In spite of the dilemma that preveiled, the committee remained committed.", options: ["dilemma", "preveiled", "committed", "amicable"], answer: 1, explanation: "Correct: prevailed (pre-vail-ed).", rule: "Vail-root: prevail.", elim: "Prevail, not preveil.", trap: "EI/IE blur trap.", trapcat: "Spelling", level: "L4 PYQ", src: "CGL 2024 · 13 Sept S1" },
{ topic: "eng_ows", q: "Select the INCORRECTLY spelt word.", options: ["Accessibility", "Apparatus", "Aptitude", "Atrocios"], answer: 3, explanation: "Correct: atrocious.", rule: "-cious ending.", elim: "Atro-cious.", trap: "S/C blur trap.", trapcat: "Spelling", level: "L4 PYQ", src: "CGL 2024 · 26 Sept" },
/* ---------- FILLERS (real 2024: tense + homonym double blank) ---------- */
{ topic: "eng_improve", q: "Fill the blank: They ___ their house for the past two months, and it is finally looking fantastic.", options: ["has renovated", "have been renovating", "were renovating", "will renovate"], answer: 1, explanation: "For + unfinished stretch continuing now → present perfect continuous.", rule: "For + ongoing → have been + -ing.", elim: "For two months + still true → have been renovating.", trap: "Simple-past trap (were).", trapcat: "Tense filler", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
{ topic: "eng_improve", q: "Fill the blanks (homonyms): The instructor commanded them to ___ in a ___. A=row (verb), B=roe, C=row (sequence).", options: ["A, C", "A, B", "C, A", "B, C"], answer: 0, explanation: "Row (verb, to row a boat) + in a row (sequence, one after another).", rule: "Homonym sense per slot.", elim: "Action → A; sequence → C.", trap: "Roe (fish eggs) absurdity trap.", trapcat: "Homonyms", level: "L4 PYQ", src: "CGL 2024 · 23 Sept S1" },
/* ---------- PARA JUMBLES (new topic; real 2024 pattern: 2Q) ---------- */
{ topic: "eng_jumble", q: "Arrange to form a meaningful sentence: A: new facts and advanced / B: but my opinion is / C: he has discovered / D: unchanged / E: new arguments.", options: ["BDAEC", "EBDCA", "DACBE", "CAEBD"], answer: 3, explanation: "He has discovered (C) new facts and advanced (A) new arguments (E) but my opinion is (B) unchanged (D) — subject-verb-object first, contrast clause last.", rule: "Build S-V-O core, park contrast (but) at the end.", elim: "C must start (subject); but-clause (B) closes.", trap: "But-first trap.", trapcat: "Sentence order", level: "L4 PYQ", src: "CGL 2024 · 18 Sept S3" },
{ topic: "eng_jumble", q: "First sentence of a paragraph: (P) Honesty is the foundation of trust. (Q) Without it, relationships crumble. (R) It must be practised even when inconvenient. (S) Children learn it by watching adults. Best order?", options: ["PQRS", "PSRQ", "PRSQ", "PQSR"], answer: 0, explanation: "Theme (P) → consequence (Q) → extension (R) → example (S).", rule: "Theme → elaborate → exemplify.", elim: "P opens; Q follows (it = honesty); S closes (example).", trap: "Example-first trap.", trapcat: "Paragraph order", level: "L3 Trap" },
{ topic: "eng_jumble", q: "Mandatory pair: (P) The monsoon failed. (Q) Crops withered in the fields. (R) Prices soared in the markets. (S) The government released buffer stocks. Best order?", options: ["PQRS", "QPRS", "PRQS", "SPQR"], answer: 0, explanation: "Cause → effect → effect → response. Chronology rules.", rule: "Chronology + cause-effect chain.", elim: "Failure first, response last.", trap: "Response-first trap.", trapcat: "Paragraph order", level: "L2 Application" },
{ topic: "eng_jumble", q: "Pronoun link: (P) Dr. Rao invented a low-cost filter. (Q) It removes arsenic from water. (R) He tested it in fifty villages. (S) The results changed state policy. Best order?", options: ["PQRS", "PRQS", "QPRS", "PSQR"], answer: 0, explanation: "It (Q) = filter (P); He (R) = Rao (P); S concludes.", rule: "Pronouns point backward — follow them.", elim: "Q needs P before it; R needs P.", trap: "Pronoun-first trap.", trapcat: "Paragraph order", level: "L2 Application" },
{ topic: "eng_jumble", q: "Connector test: (P) Many cities face water shortage. (Q) However, few harvest rainwater. (R) Rooftop harvesting is cheap. (S) It can refill groundwater. Best order?", options: ["PQRS", "PRQS", "QPRS", "PSQR"], answer: 0, explanation: "Problem (P) → contrast (Q, however) → solution (R) → benefit (S, it = harvesting).", rule: "However pivots problem→response.", elim: "Q must follow P (contrast needs a claim first).", trap: "Solution-first trap.", trapcat: "Paragraph order", level: "L3 Trap" },
{ topic: "eng_jumble", q: "Odd-one-out sense: (P) Exercise keeps the heart strong. (Q) The heart pumps blood day and night. (R) Morning walkers greet each other warmly. (S) A strong heart resists disease. Best order (drop the odd one)?", options: ["PQRS with R odd", "PQSR", "PQ S, R odd", "QPRS"], answer: 2, explanation: "R (greeting walkers) breaks the heart-theme chain; P-Q-S flow.", rule: "One theme per paragraph — drop the drifter.", elim: "R never mentions the heart-theme.", trap: "Forced-fit trap.", trapcat: "Paragraph order", level: "L4 SSC-pattern" },
];
